### ISSUE TITLE
JumpStatementsSpacing removes separated comments when immediately followed by statement

### ISSUE THREAD

**Issue by spaceemotion** [slevomat/coding-standard#1001]
I've got the following code snippet:

```php
$foo = 1;
$bar = 2;

// first comment

// second comment
return $foo + $bar;
```

With JumpStatementsSpacing enabled (using the default config) this removes both comments before the return (possibly due to the space in between).

```php
$foo = 1;
$bar = 2;

return $foo + $bar;
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/a39c387da8bd84e87a3ac7e8328916051921ba97
