### ISSUE TITLE
Benchmark for StaticClosureSniff

### ISSUE THREAD

**Issue by simonschaufi** [slevomat/coding-standard#1005]
@kukulich I'm trying to figure out why a static closure is better than a normal one. You created the StaticClosureSniff but do you also have some benchmarks why a static closure is better? I could hardly find the same recommendation from others in the internet. The only source was this one: https://stackoverflow.com/questions/1472721/performance-of-static-methods-vs-functions

**Comment by mmoll** [comment]
[PHP Inspections](https://plugins.jetbrains.com/plugin/10215-php-inspections-ea-ultimate-) cites [this example](https://github.com/Ocramius/GeneratedHydrator/pull/83).

**Comment by simonschaufi** [comment]
Thanx, this was helpful!
