### ISSUE TITLE
Require (not require-dev) Composer installer plugin

### ISSUE THREAD

**Issue by devfrey** [slevomat/coding-standard#1009]
I'm trying to setup a custom coding standard that automatically registers itself and its dependencies (SlevomatCodingStandard) with PHPCS. However, the [plugin that handles this](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) states:
> For [installation of all standards - yours and your dependencies] to work, make sure your external standard adds this plugin to the composer.json config via require, **not** require-dev.
> [(source)](https://github.com/Dealerdirect/phpcodesniffer-composer-installer#requiring-the-plugin-from-within-your-coding-standard)

With the current setup it does not register `SlevomatCodingStandard` as an installed standard (`phpcs -i`) for my project.

So would it be possible to move the `dealerdirect/phpcodesniffer-composer-installer` dependency from `require-dev` to `require`? Or are there downsides to that approach I'm not aware of?

Thanks in advance!

**Comment by kukulich** [comment]
I'm not sure about it but modified in master https://github.com/slevomat/coding-standard/commit/9e6958cf59b726062a4046c5e6abf342dd3a00ef
