### ISSUE TITLE
Problems with "unused" sniffs

### ISSUE THREAD

**Issue by WinterSilence** [slevomat/coding-standard#1015]
**1. Unused variables**
Current tests not so "pure" - passes tests with `compact()` successfully, but in real not all so good:

~~~php
function test(array $arr = ['a' => 'a'])
{
    $arr['b'] = 1;
    $c = "c{$arr['a']}";
    $all = get_defined_vars();
    return compact('arr', 'all');
}

function test2(array $arr = ['a' => 1])
{
    $arr['b'] = 1;
    $c = "c{$arr['a']}";
    /** @var array $all */
    return get_defined_vars();
}

function test3(array $arr = ['a' => 1])
{
    $arr['b'] = 1;
    $c = 'c!';
    return compact('arr', 'c');
}
~~~
as result:
~~~json
"errors": [
    {
        "line": 142,
        "message": "Unused variable $c.",
        "sourceClass": "SlevomatCodingStandard\\Sniffs\\Variables\\UnusedVariableSniff.UnusedVariable"
    },
    {
        "line": 150,
        "message": "Unused variable $c.",
        "sourceClass": "SlevomatCodingStandard\\Sniffs\\Variables\\UnusedVariableSniff.UnusedVariable"
    }
]
~~~

We can't keep all possible moments, but need append notice for functions with `compact()`, `get_defined_vars()` and etc. Users self check this "unuseful" variables.

**2. Unused methods**

Current fixes ignore abstract/inherit classes:

~~~php
abstract class AbstractTest
{
    private function innerMethod()
    {
        echo __METHOD__;
    }
}
class Test extends AbstractTest
{
    public function __construct()
    {
        $this->innerMethod();
    }
    protected function innerMethod()
    {
        echo __METHOD__;
    }
}
$t = new Test();
~~~

Method is 100% unused only when it's `finally` method.

Totally, need append notice like as "Check self before delete!" in this cases and update line numbers in response after removing/appending lines.

**Comment by kukulich** [comment]
1. Fixed in https://github.com/slevomat/coding-standard/commit/5019ae50b475f9b3f9c4965ee77aa63065ed954e

2. PHPCS does not know anything about parent classes, so it's not fixable.

**Comment by WinterSilence** [comment]
@kukulich you check `get_defined_vars()` not after variable defination.
