### ISSUE TITLE
Latest version breaks hard

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#1018]
src/Collection/functions.php (https://github.com/cakephp/cakephp/blob/master/src/Collection/functions.php)

> Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\DocCommentHelper::findDocCommentOpenToken() must be of the type int, null given, called in /cakephp/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/TypeHintHelper.php on line 106

TypeHintHelper:
```php
$classPointer = ClassHelper::getClassPointer($phpcsFile, $pointerToFindClass);
// returns int|null
$classDocCommentOpenPointer = DocCommentHelper::findDocCommentOpenToken($phpcsFile, $classPointer);
// only accepts int
```

Here you need to code more defensive, checking the return type and return early if needed.
You are running PHPStan level 7 I see, I wonder how this could have slipped through, then.

**Comment by akalongman** [comment]
I've reverted on 6.3.5

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/d023669dfedf9879b3f445636435985b0350b0a5
