### ISSUE TITLE
DisallowIncrementAndDecrementOperators enabled by default

### ISSUE THREAD

**Issue by ArtemKolychev** [slevomat/coding-standard#1019]
Hello.
I start use your coding standart.
Haw i can allow increment and dekrement operators?
You have it enable by default but have not parameter for disable it.
Thank you

**Comment by WinterSilence** [comment]
@ArtemKolychev it's extension of PHP_CodeSniffer
p.s `dekrement`:
> Like J, X, Q, and Z, the letter K is not used very frequently in English. It is the fifth least frequently used letter in the English language, with a frequency in words of about 0.8%.

**Comment by kukulich** [comment]
@ArtemKolychev You can just disable the snif.

**Comment by ArtemKolychev** [comment]
@kukulich 
How? In documentation exist only Disallow.
