### ISSUE TITLE
Undefined index: parenthesis_closer

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#1032]
Getting this in the first character of every PHP file, since the latest version of SlevomatCodingStandard:

```
An error occurred during processing; checking has been aborted.
The error message was: Undefined index: parenthesis_closer in
\vendor\slevomat\coding-standard\SlevomatCodingStandard\Sniffs\Functions\StrictCallSniff.php
on line 59 PHPCS(Internal.Exception)
```

**Comment by kukulich** [comment]
@ghnp5 Try verbose mode for PHPCS. This error does not make any sense.

**Comment by ghnp5** [comment]
Humm... I ran with full verbose in the command line, and it worked fine...

```
        *** END SNIFF PROCESSING REPORT ***
DONE in 1.41 secs (0 errors, 0 warnings)
Time: 1.59 secs; Memory: 16MB
```

But in VSCode (which I restarted, and ran again "composer update"), I'm getting the above error in every file... !

Searching for "Undefined index: parenthesis_closer", I do see other people having that error in random places, even since 2018.

Not sure what's happening. What else could I try?

Thank you very much.

**Comment by kukulich** [comment]
Can you post the file?

**Comment by ghnp5** [comment]
Ok... so this seems to happen only if the file has actual syntax errors. It appeared to be a bit random, but that's simply as I develop and "save" the file, while it has syntax errors.

I cannot post the file for privacy reasons, but I attempted to create an example dummy file where this can be reproduced:


```
<?php

					str_replace('{{g-f}}', $w['a']['t'],
					str_replace('{{g-f}}', $w['a']['t'] file_get_contents($aa);
			} else {

```

I saved this as a "test.php" in my workspace, and I get that error above.

If you cannot reproduce, then I might need to post my phpcs.xml file.

**Comment by kukulich** [comment]
Yes, file has to be valid PHP.

**Comment by ghnp5** [comment]
Well, this is a NEW error I'm getting with SlevomatCodingStandard. Before, it wasn't causing this with syntax errors. To me, it seems like a regression.

This error causes noise, when I should be seeing errors about the actual syntax problem, not a random "undefined variable".

> "Yes, file has to be valid PHP."

Yes, might as well make all your sniffs report random errors instead of reporting the actual sniff problem, since the file must be a valid PHP. What's the point of PHPCS, right? Our code must be perfect.

I don't understand your logic.

(as usual, you're quite arrogant in every reply of yours when people are trying to be helpful)

**Comment by kukulich** [comment]
See https://github.com/slevomat/coding-standard#installation

**Comment by ghnp5** [comment]
> Sniffs count on the processed code to be syntactically valid (no parse errors), otherwise they can behave unexpectedly. It is advised to run PHP-Parallel-Lint in your build tool before running PHP_CodeSniffer

Thank you.
I understand that about the builds, and I do run Lint before PHPCS on builds.

This Issue thread was more about using this on VSCode.

But no worries - I understand this is a limitation and at least now I know this happens when there are syntax problems.
