### ISSUE TITLE
Whitespaces.DuplicateSpaces Feature Request

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#1033]
I'd like to request an option to ignore spaces in method/function parameter lists, something like `ignoreSpacesInParameters`

We have code like the following and I'd like the option to leave the alignment alone.

```php
	public function UserAction(
		FooRollupMapper  $fooRollupMapper,
		Epoch            $epoch,
		BarHistoryMapper $barHistoryMapper,
		BazStatistics    $bazStatistics
	) {
		//...
	}
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/1ceef3a36dc925355da05ef5f1f68f4f14a39489
