### ISSUE TITLE
Incorrect "UnusedVariable" error for variables with post increment/decrement operator

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#1034]
The `SlevomatCodingStandard.Variables.UnusedVariable.UnusedVariable` sniff incorrectly shows error for the following:

1. https://github.com/cakephp/cakephp/blob/a2be9f3567a6bf9d6bcccde5f6585c7a66da2ad8/src/View/Helper/IdGeneratorTrait.php#L82
Error shown: `Unused variable $count.`

2. https://github.com/cakephp/cakephp/blob/a2be9f3567a6bf9d6bcccde5f6585c7a66da2ad8/src/Database/Query.php#L663
Error shown: `Unused variable $i.`

3. https://github.com/cakephp/cakephp/blob/a2be9f3567a6bf9d6bcccde5f6585c7a66da2ad8/src/Http/Client.php#L438
Error shown: `Unused variable $redirects.`

Version: 6.3.8

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/d433062ee6be8bf2b0700f207f7426efc5cb7f73
