### ISSUE TITLE
Make DocCommentSpacingSniff::checkLinesBetweenDifferentAnnotationsTypes consider Symfony's @Assert annotations as one type

### ISSUE THREAD

**Issue by egor-dev** [slevomat/coding-standard#1036]
Hi, thanks for the great package!

Please, make it possible to `DocCommentSpacingSniff::checkLinesBetweenDifferentAnnotationsTypes` to consider Symfony's `@Assert\*` annotations as one type. We want them to be grouped. Otherwise we get very tall annotations. Thank you.

![image](https://user-images.githubusercontent.com/13471770/84124244-29ec6b00-aa65-11ea-80d7-6a0c1a661f78.png)

**Comment by kukulich** [comment]
See documentation for option `annotationsGroups` https://github.com/slevomat/coding-standard#slevomatcodingstandardcommentingdoccommentspacing- :)

**Comment by egor-dev** [comment]
@kukulich thank you, man!
