### ISSUE TITLE
UselessIfConditionWithReturn will remove comments

### ISSUE THREAD

**Issue by gmponos** [slevomat/coding-standard#1040]
Hi..

Can you check this: https://github.com/doctrine/coding-standard/pull/208/files#diff-b67fca0df7d43e41d2ac5ceeb7ae7679R30

I think it's the `SlevomatCodingStandard.ControlStructures.UselessIfConditionWithReturn`

It removes the comment and also makes it a short return. I believe the rule should be either configurable or just report errors in these cases.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/de41b2a5bae8560de2671717ec36776ceb059f40
