### ISSUE TITLE
UselessSemicolon make cbf crash when no new line exists

### ISSUE THREAD

**Issue by gmponos** [slevomat/coding-standard#1041]
Hi.. 

When I run 

```
php vendor/bin/phpcbf tests/input/useless-semicolon.php  -s
```

I get the error attached

![image](https://user-images.githubusercontent.com/5675248/85222532-84ba8680-b3c4-11ea-8669-56aa1317dba2.png)

I discovered this while working [on this PR](https://github.com/doctrine/coding-standard/pull/208/files#diff-9023c633b2425ded52916bf44f88ede1R26)

Note that on the file above I added an extra line for now in order to be able to run the tests.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/e47a24f410dea65e0990bd3bdfb64900751c2e25
