### ISSUE TITLE
Mention Generic.Arrays.DisallowLongArraySyntax.Found next to ShortList sniff in README?

### ISSUE THREAD

**Issue by TysonAndre** [slevomat/coding-standard#1049]
That suggests using `[]` instead of `array()`, which was added in php 5.4 - https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax

This would help people who are looking to use short arrays everywhere and don't know about the generic sniff option, and can be enabled like this:

```xml
  <rule ref="Generic.Arrays.DisallowLongArraySyntax.Found" />
```

**Comment by kukulich** [comment]
Thanks you for your suggestion but the sniff is not part of this package so I don't want to add to the README.
