### ISSUE TITLE
`phpcbf` FAILED TO FIX

### ISSUE THREAD

**Issue by nguyenk** [slevomat/coding-standard#1057]
Hello !

I'm running into a problem :
![image](https://user-images.githubusercontent.com/2227554/88144218-e7d44e80-cbf8-11ea-9e59-ccd85173ee5c.png)

I first opened an issue in [squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/issues/3023)

After some discussions, it seems the problem comes from the slevomat coding standards, possibliy an inifinte loop.

**Comment by kukulich** [comment]
@nguyenk Could you try dev-master please? I've read the referenced issue and it may be already improved in master.

**Comment by kukulich** [comment]
No response - closing.
