### ISSUE TITLE
Add ProtectedToPrivate sniff

### ISSUE THREAD

**Issue by Slamdunk** [slevomat/coding-standard#1059]
```
Converts `protected` variables and methods to `private` where possible.

Fixing examples:
 * Example #1.
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ -1,9 +1,9 @@
    <?php
    final class Sample
    {
   -    protected $a;
   +    private $a;
    
   -    protected function test()
   +    private function test()
        {
        }
    }
   
   ----------- end diff -----------
```

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php for test cases.

**Comment by kukulich** [comment]
I'm sorry, PHPCS is not good for this.

**Comment by Slamdunk** [comment]
Hi, I'm completely ok with the `wontfix` label, but for the record the sniff asked here would be easy for PHPCS.

PHP-CS-Fixer and PHP_CodeSniffer are both single-file token analyzers, so everything one can do, the other can do too for sure.

**Comment by kukulich** [comment]
I missed the “final” keyword so yes, it’s possible with PHPCS.
