### ISSUE TITLE
Required version of phpstan/phpdoc-parser

### ISSUE THREAD

**Issue by fox91** [slevomat/coding-standard#1069]
Why the required version of `phpstan/phpdoc-parser` is 

```json
"phpstan/phpdoc-parser": "0.4.5 - 0.4.9"
```

instead of something less restrictive like:

```json
"phpstan/phpdoc-parser": "^0.4.5"
```

It caused issue in past that I can't find?

**Comment by kukulich** [comment]
Because each new version can add new annotations that need to be added here as well.

**Comment by fox91** [comment]
Thanks @kukulich for the explanation.

Is there an expected release date for the version that will allow us to use the version `0.4.9` of `phpstan/phpdoc-parser` instead of the `0.4.0 - 0.4.4` actually allowed by the version `6.3.10`?
As a workaround actually we are using `dev-master`.
