### ISSUE TITLE
SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff removes @expectedException

### ISSUE THREAD

**Issue by TomasVotruba** [slevomat/coding-standard#108]
### Code

![image](https://cloud.githubusercontent.com/assets/924196/23191929/c14de494-f8a0-11e6-925e-0fbf0a19ea43.png)

### Report

![image](https://cloud.githubusercontent.com/assets/924196/23191966/fbee6d62-f8a0-11e6-934e-b16be81d8dd3.png)

Is that intended? How to solve it?

Thank you

**Comment by ondrejmirtes** [comment]
You need to fill out usefulAnnotations property in this sniff. The new
sniffs do not yet have documentation, that's why we haven't released 2.0
yet.

**Comment by TomasVotruba** [comment]
What to se to `usefulAnnotations` to make it work?

**Comment by ondrejmirtes** [comment]
The name of your annotation including @ and type=array.

**Comment by kukulich** [comment]
See https://github.com/slevomat/coding-standard/blob/2.0-dev/ruleset.xml#L52

**Comment by TomasVotruba** [comment]
Thanks both. That's exactly what I was looking for.

I will try it later and confirm by closing.

Do you personally use other annotations there? Might be useful for me.

**Comment by ondrejmirtes** [comment]
@dataProvider, maybe @throws if you're a fan

**Comment by kukulich** [comment]
We use this in Slevomat repository:
```xml
	<property name="usefulAnnotations" type="array" value="
		@dataProvider,
		@deprecated,
		@internal,
		@see
	"/>
```

**Comment by TomasVotruba** [comment]
Works perfectly, thank you.
Also for `@dataProvider` tip!
