### ISSUE TITLE
When replacing `/** @var */`, `assert()` added inside closure that produces a value, rather than after it is used

### ISSUE THREAD

**Issue by Ocramius** [slevomat/coding-standard#1090]
Ported from https://github.com/squizlabs/PHP_CodeSniffer/issues/3097, originally opened by @DavideBicego 

Tested on `6.3.10`

TL;DR: The ` assert($response instanceof TestResponse)` code (replacement for `/** @var TestResponse $response */`) was introduced **inside** a closure that produces said value, rather than after the closure is called/used.

> **Bug description**
> phpcbf corrects the given code replacing a docblock with an assertion (and that's ok) but it also:
> 
>     * removes the variable cause a direct return can be done
> 
>     * move the assertion in a place where the variable can't be found anyway
> 
> 
> **Code sample**
> Pre **phpcbf** execution:
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> use Doctrine\ORM\EntityManagerInterface;
> 
> class TestResponse
> {
> }
> 
> class Test
> {
>     private EntityManagerInterface $em;
> 
>     public function __construct(
>         EntityManagerInterface $em
>     ) {
>         $this->em = $em;
>     }
> 
>     public function test(): TestResponse
>     {
>         /** @var TestResponse $response */
>         $response = $this->em->transactional(
>             function () use ($currentLicense, $command): TestResponse {
>                 // ...
>                 return new TestResponse();
>             }
>         );
> 
>         return $response;
>     }
> }
> ```
> 
> Post **phpcbf** execution:
> 
> ```
> ...
>     public function test(): TestResponse
>     {
>         return $this->em->transactional(
>             static function (): TestResponse {
>                 // ...
>                 return new TestResponse();
> 
>                 assert($response instanceof TestResponse);
>             }
>         );
>     }
> ...
> ```
> 
> **Custom ruleset**
> 
> ```
> <?xml version="1.0"?>
> <ruleset
>     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>     xsi:noNamespaceSchemaLocation="vendor/squizlabs/php_codesniffer/phpcs.xsd"
>     name="KanbanBOX"
> >
>     <arg name="basepath" value="."/>
>     <arg name="extensions" value="php"/>
>     <arg name="parallel" value="80"/>
>     <arg name="colors"/>
> 
>     
>     <arg value="np"/>
> 
>     <file>./src</file>
>     <file>./tests/src</file>
> 
>     <rule ref="Doctrine">
>         <exclude name="SlevomatCodingStandard.Classes.UnusedPrivateElements.UnusedConstant"/>
>     </rule>
> </ruleset>
> ```
> 
> **To reproduce**
> Steps to reproduce the behavior:
> 
>     1. Create a file called `test.php` with the pre phpcbf execution code sample above...
> 
>     2. Run `phpcbf test.php ...`
> 
>     3. Look at the changes
> 
> 
> **Expected behavior**
> I think the right correction should be :
> 
> ```
> public function test(): TestResponse
>     {
>         $result = $this->em->transactional(
>             static function (): TestResponse {
>                 // ...
>                 return new TestResponse();
>             }
>         );
>         assert($result instanceof TestResponse);
>         return $result;
>     }
> ```
> 
> **Versions:**
> 
>     * OS: Ubuntu 20.04
> 
>     * PHP: 7.4
> 
>     * PHPCS: 3.5.5
> 
>     * Standard: doctrine/coding-standard v8.1

**Comment by kukulich** [comment]
@Ocramius Could you please try 6.3.11?

It looks it's duplicate to https://github.com/slevomat/coding-standard/issues/1063 and the fix was released in 6.3.11.

**Comment by Ocramius** [comment]
@kukulich good call, we'll try it out :-)

**Comment by kukulich** [comment]
Any news? :)

**Comment by Ocramius** [comment]
@DavideBicego do you have time to give this another try?

**Comment by DavideBicego** [comment]
Tested on 6.4.0 and it works, thanks!
