### ISSUE TITLE
RequireTernaryOperator does not add spacing when needed

### ISSUE THREAD

**Issue by rjbrooksjr** [slevomat/coding-standard#1091]
When RequireTernaryOpertor is replacing a condition with `return` inside, it produces invalid code if spacing isn't correct around `if`. For example if I start with this:
```
<?php

define('MY_GLOBAL', 'something');

function foo() {
	if(MY_GLOBAL === 'something') {
		return 'one thing';
	} else {
		return 'another thing';
	}
}
```
The auto fix will change `foo()` to:
```
function foo() {
	returnMY_GLOBAL === 'something' ? 'one thing' : 'another thing';
}
```
If I change `if(MY_GLOBAL === 'something') {` to `if (MY_GLOBAL === 'something') {` (with a space after `if`), it works fine:
```
function foo() {
	return MY_GLOBAL === 'something' ? 'one thing' : 'another thing';
}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/8524d723c7c47c3fb0fb15c8644b3f2fa1b1c308
