### ISSUE TITLE
No way to enforce no trailing array comma

### ISSUE THREAD

**Issue by Pi-George** [slevomat/coding-standard#1092]
Seems like we have SlevomatCodingStandard.Arrays.TrailingArrayComma for forcing  trailing array comma, but nothing for the opposite standard

**Comment by Pi-George** [comment]
Same goes for trailing function call commas

**Comment by kukulich** [comment]
Added `DisallowTrailingCommaInDeclarationSniff` in https://github.com/slevomat/coding-standard/commit/40df709cfb33848bf9a065517e3a6fc708322970

But I don't plan to create sniff to disallow trailing commas in arrays.
