### ISSUE TITLE
Using private method as callable: SlevomatCodingStandard.Classes.UnusedPrivateElements.UnusedMethod

### ISSUE THREAD

**Issue by zlodes** [slevomat/coding-standard#1094]
Hi!

Sniff `SlevomatCodingStandard.Classes.UnusedPrivateElements.UnusedMethod` detects unused private method, but it is using as `callable` with array synax (e.g. `[$this, 'methodName']`).

### Error:
```
FILE: /home/vagrant/projects/secret-project/src/PrivateMethodDemo.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 23 | ERROR | Class PrivateMethodDemo contains unused private method
    |       | privateMethod().
    |       | (SlevomatCodingStandard.Classes.UnusedPrivateElements.UnusedMethod)
```

### Packages versions

squizlabs/php_codesniffer version: 3.5.6
slevomat/coding-standard version 6.4.0

### Code example:

```php
<?php

declare(strict_types=1);

namespace AI\B2TraderApi;

use Closure;

class PrivateMethodDemo
{
    public function getClosureFromPrivateMethod(): void
    {
        $closure = Closure::fromCallable([$this, 'privateMethod']);

        $closure();
    }

    public function callPrivateMethodUsingCallUserFuncArray(): void
    {
        call_user_func_array([$this, 'privateMethod'], []);
    }

    private function privateMethod(): void
    {
        // Do nothing
    }
}
```

P.S.: PhpStorm can detect that the private method is used.
![image](https://user-images.githubusercontent.com/1114387/94725583-ac769e80-0364-11eb-8170-c685d0b73be8.png)

![image](https://user-images.githubusercontent.com/1114387/94725479-7d602d00-0364-11eb-9261-49be2935dbfa.png)

**Comment by kukulich** [comment]
This sniff is marked as deprecated

**Comment by zlodes** [comment]
@kukulich what the alternative of it?

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/blob/740684135cf9729849c2516049a61696f8fdd3ae/SlevomatCodingStandard/Sniffs/Classes/UnusedPrivateElementsSniff.php#L61

**Comment by zlodes** [comment]
@kukulich thanks!
