### ISSUE TITLE
ParameterTypeHintSniff should inherit annotations by default

### ISSUE THREAD

**Issue by enumag** [slevomat/coding-standard#1113]
I have a case where ParameterTypeHintSniff reports that a parameter doesn't have a type but the type is specified in the interface's annotation. With `{@inheritdoc}` it shuts up but then there is another fixer who removes the `{@inheritdoc}`.

**Comment by kukulich** [comment]
I don’t see any error here. Everything works as expected in the limits of PHPCS.

**Comment by enumag** [comment]
Nevermind. I fixed it differently.
