### ISSUE TITLE
Use statements for PHP 8 attributes are consider unused

### ISSUE THREAD

**Issue by greg0ire** [slevomat/coding-standard#1118]
`SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` triggers on the following piece of code:

```php
<?php

namespace Doctrine\ORM\Mapping;

use Attribute;

#[Attribute(Attribute::TARGET_CLASS | Attribute::IS_REPEATABLE)]
final class AttributeOverride implements Annotation
{
}
```

It shouldn't.

**Comment by kukulich** [comment]
It needs to be implemented in PHPCS first.

I've found a workaround (https://github.com/slevomat/coding-standard/commit/93d7f6828aa473c52916f6a4277210a3fa358b47) but it's necessary to run PHPCS on PHP8.

**Comment by kukulich** [comment]
Improved in https://github.com/slevomat/coding-standard/issues/1137
