### ISSUE TITLE
Allow only booleans in if()

### ISSUE THREAD

**Issue by szepeviktor** [slevomat/coding-standard#1133]
Is there a rule that enforces booleans thus bans type juggling?
Thank you.

**Comment by kukulich** [comment]
I don’t think it’s possible with PHPCS. It can probably be solved with PHPStan

**Comment by szepeviktor** [comment]
Thank you.
Going to ask there.

**Comment by szepeviktor** [comment]
Go it: https://github.com/phpstan/phpstan-strict-rules/blob/70b84f65f2b55427785c470cf8c2cbea5470e3e2/rules.neon#L13-L19
