### ISSUE TITLE
MismatchingCaseSensitivity gets confused 

### ISSUE THREAD

**Issue by stefanfisk** [slevomat/coding-standard#1143]
`SlevomatCodingStandard.Namespaces.UnusedUses.MismatchingCaseSensitivity` gets confused when using a class and a function with the same name but with different capitalization.

For example, this generates `Case of reference name "Bar" and use statement "bar" does not match.` for the `@return Bar`:

```
<?php

use Foo\Bar;

use function Foo\bar;

/**
 * @return Bar
 */
function () {
    return bar();
}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/7c810e9dad5693a7e2958601d5bf09f171236cce
