### ISSUE TITLE
NullableTypeForNullDefaultValue incorrectly requires nullable mixed parameter

### ISSUE THREAD

**Issue by martin-heralecky** [slevomat/coding-standard#1147]
When the `SlevomatCodingStandard.TypeHints.NullableTypeForNullDefaultValue` sniff is applied to this piece of code, it produces a `NullabilitySymbolRequired` error saying _"Parameter $a has null default value, but is not marked as nullable."_.

```php
function foo(mixed $a = null): void
{
}
```

**Comment by kukulich** [comment]
@martin-heralecky what version do you use?

**Comment by martin-heralecky** [comment]
latest stable - 6.4.1

**Comment by kukulich** [comment]
@martin-heralecky you need to use dev-master
