### ISSUE TITLE
Composer conflicts in requirements when following README in download

### ISSUE THREAD

**Issue by thekabal** [slevomat/coding-standard#115]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - consistence/coding-standard 0.10 requires squizlabs/php_codesniffer ~2.5.0 -> satisfiable by squizlabs/php_codesniffer[2.5.0, 2.5.1].
    - consistence/coding-standard 0.10.1 requires squizlabs/php_codesniffer ~2.5.1 -> satisfiable by squizlabs/php_codesniffer[2.5.1].
    - Can only install one of: squizlabs/php_codesniffer[2.8.1, 2.5.0].
    - Can only install one of: squizlabs/php_codesniffer[2.8.1, 2.5.1].
    - slevomat/coding-standard 2.0 requires squizlabs/php_codesniffer ^2.8.1 -> satisfiable by squizlabs/php_codesniffer[2.8.1].
    - Installation request for slevomat/coding-standard ^2.0 -> satisfiable by slevomat/coding-standard[2.0].
    - Installation request for consistence/coding-standard ^0.10 -> satisfiable by consistence/coding-standard[0.10, 0.10.1].

**Comment by ondrejmirtes** [comment]
Please install the newest consistence/coding-standard, which is 0.13. We'll fix the instructions in the README.
