### ISSUE TITLE
UselessParenthesesSniff breaks match expression

### ISSUE THREAD

**Issue by rodolfoberrios** [slevomat/coding-standard#1150]
Hey there,

[UselessParenthesesSniff](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/PHP/UselessParenthesesSniff.php) is breaking PHP 8 match expression by removing the parentheses `()` which generates invalid syntax.

**Comment by kukulich** [comment]
Duplicate of #1138
