### ISSUE TITLE
Use PSR-12 indentation by default (4 spaces instead of tab)

### ISSUE THREAD

**Issue by mvorisek** [slevomat/coding-standard#1154]
citing https://www.php-fig.org/psr/psr-12/#24-indenting :
```
Code MUST use an indent of 4 spaces for each indent level, and MUST NOT use tabs for indenting.
```

4 spaces are already a golden standard in other PHP projects and CS fixers

**Comment by kukulich** [comment]
I don't understand. Where should we use it?

**Comment by mvorisek** [comment]
everywhere:

- in this repos sources
- in this repos sules (if they are based on/defines tab indentaton style)

**Comment by kukulich** [comment]
> in this repos sources

We like tabs.

> in this repos sules

It should be solved by your PHPCS settings.

**Comment by mvorisek** [comment]
> We like tabs.

can you please write why? 95% php world uses spaces now and using tabs is actually forbidded by the latest official PHP PSR-12 standard
