### ISSUE TITLE
Conditional return type is not supported in MissingTraversableTypeHintSpecification

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#1159]
```php
/**
 * @return (true is true ? array<int> : array<string>)
 */
function a(): array
{
    return [];
}
```

gives

> SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingTraversableTypeHintSpecification

**Comment by kukulich** [comment]
I think there's no support for this in https://github.com/phpstan/phpdoc-parser

**Comment by simPod** [comment]
Ah so the reason is phpstan parser don't know conditional types yet?

**Comment by kukulich** [comment]
Yes. The support has to be added to parser first, then to this repository.

**Comment by simPod** [comment]
Might be related to https://github.com/phpstan/phpstan/issues/3853 I guess

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/be7898df20714c0118b17562a626050207bb1940
