### ISSUE TITLE
Allow "$this" in closures for SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration

### ISSUE THREAD

**Issue by LastDragon-ru** [slevomat/coding-standard#1163]
PHPStrom allows defining type for `$this` that may be very useful for `Closures`:

```php
<?php declare(strict_types = 1);

namespace Bug;

use Closure;

class A {
    public function bug(): Closure {
        return function (): int {
            /** @var \Illuminate\Testing\TestResponse $this */

            return 1;
        };
    }
}
```

![image](https://user-images.githubusercontent.com/1329824/107870294-453f2e00-6eb0-11eb-8f50-66cd7e737979.png)

But seems there is no way to allow `$this` :( (?)

```
$ ./vendor/bin/phpcs ./packages/Bug.php

FILE: /project/packages/Bug.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 10 | ERROR | Missing variable $this before or after the documentation comment.
--------------------------------------------------------------------------------

Time: 657ms; Memory: 12MB
```

**Comment by kukulich** [comment]
@LastDragon-ru Did you tried all options of this sniff?

**Comment by LastDragon-ru** [comment]
@kukulich yep, and, unfortunately, it not always work.

![image](https://user-images.githubusercontent.com/1329824/107871972-dbc71b80-6ebf-11eb-94e3-200dc025c245.png)

**Comment by kukulich** [comment]
@LastDragon-ru As said in the documentation:

`allowAboveNonAssignment: Allows documentation comments above non-assigment if the line contains the right variable name.`

So move the `@var` above the `if`.

**Comment by LastDragon-ru** [comment]
> So move the @var above the if.

@kukulich, IMO, it is a bit ugly (in this case), but works) Thank you.
