### ISSUE TITLE
SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly.ReferenceViaFullyQualifiedName sniff can change behavior in the base namespace

### ISSUE THREAD

**Issue by ebrigham1** [slevomat/coding-standard#1164]
The `SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly.ReferenceViaFullyQualifiedName` Sniff can result in code behavior changes when run in a file with no namespace. Is this expected behavior?

```php
<?php

class Foo
{
    public function throwNamespacedException()
    {
        throw new \Some\Namespaced\Exception();
    }

    public function throwGenericException()
    {
        throw new Exception();
    }
}
```

Running the fixer will result in `import Some\Namespaced\Exception;` being added which will change what exception the  `throwGenericException` method actually throws.

**Comment by kukulich** [comment]
PHPCS works only on tokens and in one-file scope. It's difficult to solve this...

**Comment by ebrigham1** [comment]
I'm not sure the one-file scope is relevant since you only need the information in this file to tell that there is a collision when adding the import with the existing `Exception()` unless I'm missing something? However I don't know enough about PHPCS tokenization to know if that is relevant to making it a challenge to detect the collision and not apply the fix.

**Comment by ebrigham1** [comment]
It seems like using the `allowFullyQualifiedNameForCollidingClasses` option fixes this behavior due to building up the class reference index with all the references that would be needed to detect the collision, but reading the documentation it seems to be meant for colliding use statements. Also it won't show the error anymore, but just silence it completely rather than simply not fix it.

This block of code right here seems to accomplish the same thing when there is a collision with use statements where it does maintain the error but does not apply the fix automatically.

https://github.com/slevomat/coding-standard/blob/e4a5c4c929128153f8c18de074763d7a8c73f8d7/SlevomatCodingStandard/Sniffs/Namespaces/ReferenceUsedNamesOnlySniff.php#L382-L406

I think this is just an edge case where there isn't a use statement because we are in the root namespace yet we aren't using the fully qualified name with a preceding `\` again because we are in the root namespace.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/7368ec7e319331b2646a79bff8e54791c8488ad0

**Comment by ebrigham1** [comment]
Thanks for the quick fix @kukulich, much appreciated!
