### ISSUE TITLE
phpstan/phpdoc-parser v0.4.9 requires a deprecated package

### ISSUE THREAD

**Issue by tlsvda** [slevomat/coding-standard#1165]
This is already fixed in master, can this be released?

Current version (v6.4.1) I can only use: `"phpstan/phpdoc-parser": "0.4.5 - 0.4.9"`.
In master: `"phpstan/phpdoc-parser": "0.4.5 - 0.4.10"`.

And is there a reason you don't use `^0.4` ?

**Comment by kukulich** [comment]
> This is already fixed in master, can this be released?

https://github.com/slevomat/coding-standard/milestone/4

> And is there a reason you don't use ^0.4 ?

Yes :)
