### ISSUE TITLE
Namespaces\UnusedUsesSniff::class search ignoring #[Attribute] annotation

### ISSUE THREAD

**Issue by stanislav-janu** [slevomat/coding-standard#1168]
Hi.

First: Thanks for yours work!

`SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff::class` does not match PHP 8 annotation #[Attribute].

settings:
```php
	$services->set(SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff::class)
		->property('searchAnnotations', 'yes')
		->property('ignoredAnnotationNames', ['@testCase'])
		->property('ignoredAnnotations', ['@internal']);
```

php 8.0.2
scs 6.4.1

sample code:
```php

use Nette\DI\Attributes\Inject;

abstract class BasePresenter extends Presenter
{
	#[Inject]
	public Explorer $database;
}
```

**Comment by kukulich** [comment]
@stanislav-janu Try `dev-master`

**Comment by stanislav-janu** [comment]
If I tried dev-master, that error has been shown: [ERROR] Call to undefined method Symplify\SetConfigResolver\SetAwareConfigResolver::resolveSetFromInput()

I just tried change `nette/coding-standard` composer.json
```diff
{
	"name": "nette/coding-standard",
	"license": "MIT",
	"require": {
		"php": "^7.2 || ^8.0",
		"symplify/easy-coding-standard": "^9.0",
		"symplify/coding-standard": "^9.0",
-		"slevomat/coding-standard": "^6",
+		"slevomat/coding-standard": "dev-master",
		"drew/debug-statements-fixers": "^0.5.0"
	},
	"require-dev": {
		"tracy/tracy": "^2.5"
	},
	"autoload": {
		"classmap": ["src/"]
	},
	"extra": {
		"branch-alias": {
			"dev-master": "3-dev"
		}
-	}
+	},
+	"minimum-stability": "dev"
}
```

**Comment by kukulich** [comment]
@stanislav-janu Errors in `nette/coding-standard` should be reported there.

**Comment by stanislav-janu** [comment]
This sniff is `SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff::class` and not `NetteCodingStandard\Sniffs\Namespaces\UnusedUsesSniff::class`

**Comment by stanislav-janu** [comment]
@kukulich Ok. Maybe is support for PHP 8 in working process and I know nothing about it. Can you tell me about that? How much is done and when will be release approx.? Thank you.

**Comment by kukulich** [comment]
@stanislav-janu Yes, you can use “dev-master”. However it’s your choise to use “nette/coding-standard” so bugs in Nette coding standard (your second comment) should be reported there.
