### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dakorpar** [slevomat/coding-standard#1176]
Hi, thanks for great job you're doing here :+1: 
Do U have any ETA on releasing new version?
I have few issues with php 8 and 6.4.1 not really supporting few things...
Like unused use error when you have attribute 
  7 | ERROR | [x] Type Attribute is  not used in this file

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/milestone/4

**Comment by dakorpar** [comment]
thanks, didn't notice this :)
