### ISSUE TITLE
SlevomatCodingStandard.ControlStructures.RequireNullSafeObjectOperator produces breaking changes for expressions and conditions with logical OR

### ISSUE THREAD

**Issue by lptn** [slevomat/coding-standard#1182]
**Sniff and rule**: `SlevomatCodingStandard.ControlStructures.RequireNullSafeObjectOperator.RequiredNullSafeObjectOperator`

**version**: master (pre-3.0)

**code**:
```diff
-if ($user === null || $user->is_sign_up_completed) {}
+if ($user?->is_sign_up_completed) {}
```

what is, obviously, not equivalent

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/9e6619ccfb5590c02d9565ff877a0b99708e5628
