### ISSUE TITLE
UnusedParameter and constructor property promotion

### ISSUE THREAD

**Issue by redaxmedia** [slevomat/coding-standard#1184]
Hey,

is it possible that the `/Functions/UnusedParameter` sniff is not compatible with a constructor property promotion?

**Comment by kukulich** [comment]
@redaxmedia Have you tried `dev-master` ?

**Comment by redaxmedia** [comment]
Yeah, I am using the dev-master...

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/7d5ccdd83e3e1e9c613eb75e0922ca88ea9261a4

**Comment by redaxmedia** [comment]
@kukulich Awesome, I can confirm that it has been fixed.
