### ISSUE TITLE
Update phpstan/phpdoc-parser dependency to 0.5.2

### ISSUE THREAD

**Issue by simonschaufi** [slevomat/coding-standard#1186]
Hi, I'm using `rector/rector` and this package requires `phpstan/phpdoc-parser:^0.5.2` which is incompatible with the requirements of `slevomat/coding-standard`. Could you please update the dependency?

**Comment by kukulich** [comment]
It's already supported in `dev-master`.

**Comment by simonschaufi** [comment]
When can I expect a new release?

**Comment by stpnkcrk** [comment]
I believe it depends on PHPCS 3.6.0 based on https://github.com/slevomat/coding-standard/milestone/4
