### ISSUE TITLE
Unused Parameter in Arrow function

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#1188]
Hello,

This works fine:

	$found = in_array_cb($needle, $haystack, function($array, $needle) {
		return $array[2] === $needle;
	});

But in the bellow, SlevomatCodingStandard complains about "Unused parameter $needle" (`SlevomatCodingStandard.Functions.UnusedParameter.UnusedParameter`):

	$found = in_array_cb($needle, $haystack, fn($array, $needle) => $array[2] === $needle);

If I remove "[2]", SlevomatCodingStandard does not complain:

	$found = in_array_cb($needle, $haystack, fn($array, $needle) => $array === $needle);

**Comment by ghnp5** [comment]
Same issue reported to https://github.com/squizlabs/PHP_CodeSniffer/issues/3284
They fixed it in their side - in case it helps here too.

https://github.com/squizlabs/PHP_CodeSniffer/commit/3decd5ef0eb3a9c688f0dc29bd832b8bc3af4406

**Comment by kukulich** [comment]
Yes, it was bug in PHPCS.
