### ISSUE TITLE
Unused Parameter in Arrow function

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#1192]
Hello,

I updated SlevomatCodingStandard to 7.0.0, and SquizlabsPHPCS to 3.6.0.

While the issue in squizlabs/PHP_CodeSniffer#3284 is fixed, the issue in slevomat/coding-standard#1188 is not.

So, posting the bug here again...

This works fine:

	$found = in_array_cb($needle, $haystack, function($array, $needle) {
		return $array[2] === $needle;
	});

But in the bellow, SlevomatCodingStandard complains about "Unused parameter $needle" (`SlevomatCodingStandard.Functions.UnusedParameter.UnusedParameter`):

	$found = in_array_cb($needle, $haystack, fn($array, $needle) => $array[2] === $needle);

If I remove "[2]", SlevomatCodingStandard does not complain:

	$found = in_array_cb($needle, $haystack, fn($array, $needle) => $array === $needle);

![image](https://user-images.githubusercontent.com/57591332/114157454-8df8ed80-991b-11eb-920f-19932dade61e.png)

Thanks

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/7f4e95df27801addad20b81505d4185b2bc738ba
