### ISSUE TITLE
Multi-line function declaration trailing comma misunderstood when there is a comment

### ISSUE THREAD

**Issue by iquito** [slevomat/coding-standard#1193]
Using the new version `7.0.0`, the following code block gets misunderstood for `Functions.RequireTrailingCommaInDeclaration`:

```php
class SomeService
{
    public function __construct(
        private CustomerRepository $customerRepository,
        private InstanceService $instanceService, // some comment why this is included
    ) {
    }
}
```

Because of the comment on the same line as the last parameter, it thinks there is a comma missing, and when fixing this it adds another comma on the line after the last parameter, creating a syntax error in the file.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/c46fe7ee41adc842ec099a101ede35a4fba9b8b9
