### ISSUE TITLE
Constructor property promotion questions / feature requests

### ISSUE THREAD

**Issue by stpnkcrk** [slevomat/coding-standard#1199]
Good afternoon

First of all, thank you for this amazing library.

I have a couple of questions regarding constructor property promotion and its interaction with other sniffs.

1) Using CPP might leave the code with legit empty constructors but that clashes with `DisallowEmptyFunction`. Putting a comment in the constructor is indeed a solution, I'm just curious whether there could be support for these cases?

2) We're using combination of `RequireSingleLineCall` and `RequireMultiLineCall` which works perfectly for short and long definitions. However, we'd like to force the multiline call always for CPP, even if there's just one property. But that clashesh with `RequireSingleLineCall`. Any chance this could be supported?

Just to note, I'm not using `RequireConstructorPropertyPromotion` (yet) as I'm so far migrating our codebases to 8.0 so using it only "where applicable". Don't know whether that would solve any of my questions, but from reading the docs I doubt that.

Thank you very much

**Comment by kukulich** [comment]
@stpnkcrk 

1. Fixed in https://github.com/slevomat/coding-standard/commit/de69dbc16b8cb67bcbd28d5eae3ac83c85314539

2. I'm not sure about this feature...

**Comment by stpnkcrk** [comment]
@kukulich 

1. Thank you very much!

2. Not a problem at all, I understand. At least I know I wasn't overlooking some configuration.
