### ISSUE TITLE
DeclareStrictTypes fails with TypeError

### ISSUE THREAD

**Issue by lookyman** [slevomat/coding-standard#120]
```xml
<rule ref="SlevomatCodingStandard.TypeHints.DeclareStrictTypes">
    <properties>
        <property name="spacesCountAroundEqualsSign" value="1"/>
    </properties>
</rule>
```

TypeError: str_repeat() expects parameter 2 to be integer, string given in path/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/DeclareStrictTypesSniff.php on line 101

It works if you add an `(int)` cast to that line. ~But then there is also another problem with phpcbf, which cannot handle `spacesCountAroundEqualsSign=0` and ends with ERROR.~ *(caused by a conflicting sniff)*

I can prepare a PR if you want.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/37dfa4539433810f1059c2f500fe95edeb9b79d3. Thanks.
