### ISSUE TITLE
Fix #1096 in v6 too

### ISSUE THREAD

**Issue by rimas-kudelis** [slevomat/coding-standard#1208]
Hi!
#1096 has only been fixed in version 7.0.0, which has only been around for a few weeks.
Would you mind backporting the fix to 6.4 branch as well, so that those of us who are still on the older version don't have to use `// phpcs:ignore` or upgrade right away?

**Comment by kukulich** [comment]
I'm sorry but I don't want to backport anything.

**Comment by rimas-kudelis** [comment]
Would you accept a pull request?

I tried updating this package to lastest v7.0, but, since it's also a dependency of some other packages, where it's locked at `^6.0`, there's not much else I can do in my situation.

Furthermore, 7.0 has a list of BC breaks and we'd hit almost all of them. I'd rather avoid that for now.

**Comment by kukulich** [comment]
> Would you accept a pull request?

Only if you pay me :)

**Comment by rimas-kudelis** [comment]
Wow, okay, thanks, bye.
