### ISSUE TITLE
SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingNativeTypeHint suggests void union return type

### ISSUE THREAD

**Issue by skon-hh** [slevomat/coding-standard#1211]
I'm currently migrating one of my projects to php 8 (from php 7.4). I have a problem with following method:

```php
/**
 * @return object|void
 */
public function someMethod()
{

}
```
I get the following error:
` Method \App\SomeClass::someMethod() does not have native return type hint for its return value but it should be possible to add it based on @return annotation "object|void". (SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingNativeTypeHint)`

Since void return type can never be part of a union type ([RFC](https://wiki.php.net/rfc/union_types_v2)) I think this is a bug.

I'm using slevomat/coding-standard 7.0.6 and squizlabs/php_codesniffer 3.6.0.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/56288b52b14a60736c038ce494dbeff6819f3689
