### ISSUE TITLE
Problem mixing attributes and docblock

### ISSUE THREAD

**Issue by temp** [slevomat/coding-standard#1219]
We are still experiencing problems with slevomat 7.0.7, which contains the bugfix from #1205 .

This definition:
```
    /** @var DamageInput[]|null */
    #[Groups(['read', 'write'])]
    #[Valid]
    public ?array $damages = null;
```

results in this error:
```
 20 | ERROR | Invalid inline documentation comment format "@var DamageInput[]|null", expected "@var type $variable".
    |       | (SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.InvalidFormat)
```

Is there a preferred order of docblock/attributes? phpcs fails with this variant, phpstan the other way round.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/44bbe931b956b1fa9313f42f475d356c0090a1da
