### ISSUE TITLE
MultiLineArrayEndBracketPlacement conflicts with Squiz.Arrays.ArrayDeclaration

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#1221]
```php
$array = [[1 => 2],
];
$array = [[
	1 => 2,
	3 => 4,
],
];
```

becomes

```php
$array = [

    [1 => 2],
];
$array = [

    [
        1 => 2,
        3 => 4,
    ],
];
```

when run together with `Squiz.Arrays.ArrayDeclaration.ValueNoNewline`.

It should become

```php
$array = [
    [1 => 2],
];
$array = [
    [
        1 => 2,
        3 => 4,
    ],
];
```

**Comment by kukulich** [comment]
@simPod Where is the bug in our sniff?

**Comment by simPod** [comment]
TBH no idea. Do you think it's a bug of Squiz? Both sniffs work ok when used separately which makes selecting a responsible library a bit tricky.

**Comment by kukulich** [comment]
> Do you think it's a bug of Squiz?

I don't know but currently I don't see any bug in our sniff :)

**Comment by simPod** [comment]
You can assign the issue to me, I'll find the root cause.
