### ISSUE TITLE
[Suggestion] Improve release notes with a generator

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#1223]
Hey folks!

May I suggest something? Could you improve the notes for https://github.com/slevomat/coding-standard/releases with something like https://github.com/jwage/changelog-generator?

Doctrine, as an example, uses it for their projects and it's very easy to track what changed, and with PRs/issues are related to it: https://github.com/doctrine/collections/releases

It would require a change in your current flow of managing PRs, but I'm sure that would improve the notes a lot :)

**Comment by kukulich** [comment]
I'm not sure :D https://github.com/doctrine/cache/releases

**Comment by LastDragon-ru** [comment]
I can suggest look at [release-it](https://github.com/release-it/release-it) + [release-it/conventional-changelog](https://github.com/release-it/conventional-changelog) + [conventionalcommits](https://www.conventionalcommits.org/). It can generate changelog by commits and put generated tect into release message :)

![image](https://user-images.githubusercontent.com/1329824/120059409-71974880-c062-11eb-897e-00bea5563c8b.png)
