### ISSUE TITLE
Ability to disallow one-line phpDocs for class methods

### ISSUE THREAD

**Issue by ekinhbayar** [slevomat/coding-standard#1224]
Hi! First of all, my apologies if this is the wrong medium to ask and thank you so much for all your efforts and time put into this project, I mean that :heart:.

I'm trying to find a way to require phpDocs above every class method to be multi-line. I'm aware of something like this being possible for class properties, I'm already using `SlevomatCodingStandard.Commenting.RequireOneLinePropertyDocComment` and `SlevomatCodingStandard.Commenting.UselessFunctionDocComment` and they work great! Though, they don't help me in enforcing e.g. `/** @inheritDoc */` over its multi-line version (to be clear, it's not _just_ about inheritDoc). 

Having gone through the readme, I wasn't able to find out how this could be possible.  I'd appreciate any thoughts and ideas you might be able to share. Thank you!

**Comment by kukulich** [comment]
There’s no such sniff.
