### ISSUE TITLE
SlevomatCodingStandard.ControlStructures.RequireNullSafeObjectOperator still produces breaking changes for expressions and conditions with logical OR

### ISSUE THREAD

**Issue by jaroslavlibal** [slevomat/coding-standard#1227]
The issue https://github.com/slevomat/coding-standard/issues/1182 is fixed for most cases, but the problem still occurs when a strict equality comparison is used, either on the property or on the return value.

```diff
-if ($data === null || $data->size === 0) {}
+if ($data?->size === 0) {}
```
or
```diff
-if ($data === null || $data->size() === 0) {}
+if ($data?->size() === 0) {}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/bc16c42562b84d5a81ad270d7d711e3414bf100b
