### ISSUE TITLE
Arrays.SingleLineArrayWhitespace not working with short "list()", when optional items present

### ISSUE THREAD

**Issue by gregor-tb** [slevomat/coding-standard#1232]
Using one space:

```
    <rule ref="SlevomatCodingStandard.Arrays.SingleLineArrayWhitespace">
        <properties>
            <property name="spacesAroundBrackets" value="1"/>
        </properties>
    </rule>
```

code:

```
$a = [ null, 'use' ];

[ , $second ] = $a;
```

This requires a space at the beginning, but also disallows space before comma, so it ends up in a loop or requires to set an (used) variable here. Auto-Fix not working.

Using version 6.4.1, cannot tell if it is also present in 7.x branch.

**Comment by kukulich** [comment]
@gregor-tb Please test version 7.

**Comment by gregor-tb** [comment]
Sorry, I don't have budget to fight through the breaking changes right now, but the Sniff-Code is identical in master.

**Comment by gregor-tb** [comment]
Not sure why this is closed, but for anyone interesting in a quick solution:

vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Arrays/SingleLineArrayWhitespaceSniff.php line 189

```
        if ($tokens[$comma - 2]['code'] === T_COMMA) {
            return;
        }
```

change to

```
        if ($tokens[$comma - 2]['code'] === T_COMMA || $tokens[$comma - 2]['code'] === T_OPEN_SHORT_ARRAY) {
            return;
        }
```
