### ISSUE TITLE
Comma in last parameter of a function

### ISSUE THREAD

**Issue by tinyMeerkatRebel** [slevomat/coding-standard#1235]
Hello,

Thank you very much for all the work you've done - it is an amazing project!

Today, I was working with a new project and I discovered that I have an issue. Here is my example:

I have something similar to this:

```
\app('log')->critical(
            "{$this->signature} - error",
            [$exception->getMessage(), ['id' => $id]],
        );
```

and when I run CS I get 
```
 ERROR | [x] Trailing comma after the last parameter in function call is disallowed.
     |       |     (SlevomatCodingStandard.Functions.DisallowTrailingCommaInCall.DisallowedTrailingComma)
```

Then I fix it by removing the comma and I get this error:

```
[x] Multi-line function calls must have a trailing comma after the last parameter.
     |       |     (SlevomatCodingStandard.Functions.RequireTrailingCommaInCall.MissingTrailingComma)
```

I am not so sure what I should do there? If you could please have a look? Thank you.

**Comment by kukulich** [comment]
@tinyMeerkatRebel you just have to disable one of the sniffs.
