### ISSUE TITLE
DOCS: Reasons for such standards

### ISSUE THREAD

**Issue by yob-yob** [slevomat/coding-standard#1236]
I wanted to start a discussion, but it's not possible so I'll just make an issue instead...

I wanted to know what's the reason behind why disallow the use of `empty()`
found on `SlevomatCodingStandard\Sniffs\ControlStructures\DisallowEmptySniff`

I was using [PhpInsight](https://phpinsights.com/insights/code.html#disallow-continue-without-integer-operand-in-switch) on my project and found out about this.

I wanted to know since the Laravel Framework is currently using this function on one of its Class `app/Http/Middleware/RedirectIfAuthenticated.php:23`

is there a file I can check the reason for each `Sniffs`? or maybe a link?

**Comment by dereuromark** [comment]
We also discourage the use of empty in certain cases (not all!):
When the key or variable is known and expected to be present.
Here empty() would be cloaking - and hiding the fact that either the key/var was misspelled or something is really wrong.
Having a cloaking check here means you will never see or hear about the issue, and you can only hope a test case might find this hidden no-op.
For the other cases empty() usage is perfectly fine IMO. But I guess you could always use isset() + strict check instead.
That's maybe why some people like to remove it completely.

**Comment by kukulich** [comment]
https://twitter.com/phpstan/status/998663674196873216?lang=cs
