### ISSUE TITLE
RequireNonCapturingCatchSniff removes variable when used outside of the catch scope

### ISSUE THREAD

**Issue by mabar** [slevomat/coding-standard#1238]
I am using following pattern to delete file from FS in case storing file reference into database failed. Unfortunately `RequireNonCapturingCatchSniff` thinks `$exception` is unused and removes it.

```php
foreach ($files as $file) {
	try {
		$this->model->persistAndFlush($file);
	} catch (Throwable $exception) {
		$this->filePersister->delete($file);
	}
}

if (isset($exception)) {
	throw $exception;
}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/751e737f9b7b1d4e886ca9a61bc5d50aab4bc0e4
