### ISSUE TITLE
MissingNativeTypeHint creates invalid syntax for 'no-return'

### ISSUE THREAD

**Issue by jlherren** [slevomat/coding-standard#1239]
The annotation `@return no-return` is understood by some tools (PhpStorm, PHPStan) to indicate that a function/method never returns. However, `MissingNativeTypeHint` will complain about it and when fixing the code it creates invalid syntax, here's a diff:

```
--- tests/cypress/cypress.php
+++ PHP_CodeSniffer
@@ -30,7 +30,7 @@
      *
      * @return no-return
      */
-    private function success(string $message = 'Success') {
+    private function success(string $message = 'Success'): no - return {
         echo $message . "\n";
         exit(0);
     }
```

It would be nice if it would:
1. Ignore any return names that can't possible be a valid class name
2. Understand that `no-return` corresponds to a `void` return type

Some other return annotations for the same purpose that are likely to be used: `never`, `never-return`, `never-returns`

**Comment by kukulich** [comment]
Improved in https://github.com/slevomat/coding-standard/commit/4607562c9d217a1026c9effde4fc78065571fd19
