### ISSUE TITLE
Unable to disable native return type in different namespace

### ISSUE THREAD

**Issue by othercorey** [slevomat/coding-standard#1240]
When using the `SlevomatCodingStandard.TypeHints.ReturnTypeHint` sniff, native return types are added based on the `@return` annotation.

However, when that type is in a different namespace, it adds the fully qualified name as the return type. We require a `use` statement for all of these types. We would prefer to disallow auto-fixing these errors to avoid having to follow up.

```
/**
 @return Some\Namespace\Type
 */
function test()
{
}


function test(): \Some\Namespace\Type
{
}
```

**Comment by kukulich** [comment]
That’s correct. Thera are other sniffs that solve `use`.
