### ISSUE TITLE
ReturnTypeHint.MissingTraversableTypeHintSpecification doesn't understand array shape syntax

### ISSUE THREAD

**Issue by lptn** [slevomat/coding-standard#1243]
```php
/**
 * @see https://docs.coconut.co/api/jobs/notification
 * @return array{params: array{video_id: int}, type: "http", url: string}
 */
```

```
@return annotation of method CoconutTranscoder::getNotification() does not
    |       | specify type hint for items of its traversable return value.
    |       | (SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingTraversableTypeHintSpecification)
```

array shapes declared to be implemented here https://github.com/slevomat/coding-standard/commit/35446d2331feab750bb5019212f12057785eacbe

**Comment by kukulich** [comment]
@lptn What version of SlevomatCS do you use?

**Comment by lptn** [comment]
@kukulich 
>@lptn What version of SlevomatCS do you use?

7.0.9

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/4c3a1f3171d3031cdac6d1ee6d337952e950f236
