### ISSUE TITLE
Annotation for its traversable parameter

### ISSUE THREAD

**Issue by san4io** [slevomat/coding-standard#1250]
Hello, 

How can i supress only `SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingTraversableTypeHintSpecification` spec, but not all `SlevomatCodingStandard.TypeHints.ParameterTypeHint`

So actually I don't want to be forced to determine traversable type.

Same for:
```
ParameterTypeHintSniff
ReturnTypeHintSniff
PropertyTypeHintSniff
```

Any ideas?

**Comment by kukulich** [comment]
Just disable the specific error, see PHPCS documentation.

**Comment by san4io** [comment]
> PHPCS

![image](https://user-images.githubusercontent.com/12079341/126315406-b3c45a82-b580-45a4-a5a5-3a7c6b495fa2.png)
Result:
![image](https://user-images.githubusercontent.com/12079341/126315453-bef87607-11fb-4029-8a38-fc2c8b72368c.png)
