### ISSUE TITLE
Inherit traversable type from interface to prevent `MissingTraversableTypeHintSpecification`

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#1256]
Having an interface

```php
interface A {
    /** @return array<string, string> */
    public function fcn() : array
}
```

I'd like to omit any doc for traversable type as it is inherited from the interface:

```php
class B implements A {
    public function fcn() : array {
    }
}
```
Although, now I have to write

```php
class B implements A {
    /** @inheritDoc */
    public function fcn() : array {
    }
}
```

otherwise I get the error

> phpcs: SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingTraversableTypeHintSpecification: Method B::fcn() does not have @return annotation for its traversable return value.

Would it make sense to inherit the type?

**Comment by kukulich** [comment]
@simPod PHPCS works in one file scope.

**Comment by simPod** [comment]
Hmmm, so there's no way to find the method is an implementation of interface method, right?

**Comment by kukulich** [comment]
> Hmmm, so there's no way to find the method is an implementation of interface method, right?

Yes :(

**Comment by simPod** [comment]
Got it, thanks for swift input 🙃
