### ISSUE TITLE
SlevomatCodingStandard.PHP.TypeCast (Internal.Exception)

### ISSUE THREAD

**Issue by Miras4207** [slevomat/coding-standard#1270]
Sniff **SlevomatCodingStandard.PHP.TypeCast** throws following error:

`An error occurred during processing; checking has been aborted. The error message was: Undefined array key 1 in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/TypeCastSniff.php on line 61`

Versions:
slevomat/coding-standard: 7.0.14
PHP 8.0.6

**Comment by kukulich** [comment]
@Miras4207 please use verbose option of PHPCS and find the file and code that throws this error.

**Comment by Miras4207** [comment]
> @Miras4207 please use verbose option of PHPCS and find the file and code that throws this error.

The problematic code in our case was: `b"\xEF\xBB\xBF"`
There was no issue with this alternative: `(binary) "\xEF\xBB\xBF"`

I didn't notice there was a binary cast at first, otherwise I would have removed it.

Even though I see why it is not necessary to fix this case, I think it would be better if the `b` prefix was handled in a same was as `(binary)`.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/6bf37ba1de502abed17e24dd2e20da8868c20059
