### ISSUE TITLE
SlevomatCodingStandard.Namespaces.UseSpacing moves comment wrongly

### ISSUE THREAD

**Issue by olivernybroe** [slevomat/coding-standard#1274]
When having a class with a docblock just after the use (no spaces), it moves the comment as it belongs to the uses not the class.

So the following happens
```diff
use Exception;
/**
 * My sweet class
 */
+
class MyClass
```

However the expected result is 
```diff
use Exception;
+
/**
 * My sweet class
 */
class MyClass
```

**Comment by kukulich** [comment]
@olivernybroe Please post the original code before PHPCS fixed it.

**Comment by olivernybroe** [comment]
```php
use Exception;
/**
 * My sweet class
 */
class MyClass
{
}
```

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/c6e72663f175a01bfc0a946a49365bf3362b205d

**Comment by olivernybroe** [comment]
Amazing, thanks a lot ❤️
