### ISSUE TITLE
RequiredConstructorPropertyPromotion can produce logic changes

### ISSUE THREAD

**Issue by VladaHejda** [slevomat/coding-standard#1275]
`RequiredConstructorPropertyPromotion` can produce logic changes.

It is necessary to find out whether variable isn't altered before assigning to property. If it is, it shouldn't require / apply promotion OR it must alter the property, not the variable.

Example of logic change:

```
class Foo extends ObjectPrototype
{

	private int $number;

	public function __construct(int $number)
	{
		$number++;
		$this->number = $number;
	}

}
```

--->

```
class Foo extends ObjectPrototype
{

	public function __construct(private int $number)
	{
		$number++;
	}

}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/baf453cb7e29a59c0f5d4ecd428a3e683ca3da72
