### ISSUE TITLE
UnusedUse & phpstan Local type aliases

### ISSUE THREAD

**Issue by martinssipenko** [slevomat/coding-standard#1278]
I use [phpstan Local type aliases](https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases) in my project, but `SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` considers `use Psr\Log\LogLevel;` statement as not used (Type` Psr\Log\LogLevel` is not used in this file.).

I do have `searchAnnotations` enabled.

Is there anything we could do to add support for this?

```
<?php

declare(strict_types=1);

use Psr\Log\LogLevel;

/**
 * @phpstan-type Level LogLevel::EMERGENCY|LogLevel::ALERT|LogLevel::CRITICAL|LogLevel::ERROR|LogLevel::WARNING|LogLevel::NOTICE|LogLevel::INFO|LogLevel::DEBUG
 */
class Foo
{
  // ...
}
```

**Comment by kukulich** [comment]
It's already working, see https://github.com/slevomat/coding-standard/commit/88a787457bed12a89f5f63ffac6829d32847fc32

**Comment by martinssipenko** [comment]
@kukulich I see, it has been introduced in 7.0.0. Thanks for the prompt response!
