### ISSUE TITLE
InlineDocCommentDeclaration.NoAssignment cannot handle NullCoalesceEqualOperator

### ISSUE THREAD

**Issue by gregor-tb** [slevomat/coding-standard#1282]
this still works:
```
    function test(object $b, $a = null): \stdClass
    {
        /** @var \stdClass $a */
        $a = $a ?? $b;

        return $a;
    }
```

this fails on php8.0:

phpcs: SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.NoAssignment: No assignment to $a variable before or after the documentation comment.

```
    function test(object $b, $a = null): \stdClass
    {
        /** @var \stdClass $a */
        $a ??= $b;

        return $a;
    }
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/1022655a591e45ef372ee61e482ebcf4b95e7e1d
