### ISSUE TITLE
"never" support

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#1283]

**Comment by jansor** [comment]
Hi is this already implemented, as now when running PHPCS with rule 
[x] SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameInAnnotation.NonFullyQualifiedClassName
it will autofix the namespace of a method type never in php8.1 and thus the phpdoc block is wrong in return type for never

**Comment by kukulich** [comment]
Done.
