### ISSUE TITLE
Option to only count logical lines of code in SlevomatCodingStandard.Functions.FunctionLength ?

### ISSUE THREAD

**Issue by bmitch** [slevomat/coding-standard#1285]
Was curious if you folks would be open to adding an option to only count logical lines of code in the SlevomatCodingStandard.Functions.FunctionLength` rule?

If so, I'd be up for taking a crack at a pull request. Thanks.

**Comment by kukulich** [comment]
Yes, I’m ok with the option if you prepare PR :)

**Comment by bmitch** [comment]
Will see what I can do!
