### ISSUE TITLE
More defensive coding

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#1299]
Some classes throw fatal errors due to unchecked keys.
Here always an isset() check or alike should be made to make them more robust and skip instead of killing the whole fixing process.

> Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener in /.../vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php on line 59 in /.../vendor/squizlabs/php_codesniffer/src/Runner.php:607

It is also rather hard to debug then what exactly caused this rather than e.g. a clear exception or alike.

In my case it seems it is caused by an old file that contains too classes
```php
class Imap {
}

/**
 * ...
 */
class ImapMessageInfoLib {
}
```

Either way, in the code of
```php
	public static function getName(File $phpcsFile, int $classPointer): string
	{
		$tokens = $phpcsFile->getTokens();

		if ($tokens[$classPointer]['code'] === T_ANON_CLASS) {
			return 'class@anonymous';
		}

		// Adding this guard clause required
		if (!isset($tokens[$classPointer]['scope_opener'])) {
			return null; // Return null or empty string?
		}

		return $tokens[TokenHelper::findNext($phpcsFile, T_STRING, $classPointer + 1, $tokens[$classPointer]['scope_opener'])]['content'];
	}
```
it should bail early in this case.

**Comment by kukulich** [comment]
Can you please dump `$tokens[$classPointer]` ?

**Comment by dereuromark** [comment]
Sure, it is just the whitespace above, between the classes I imagine:
```
array(8) {
  ["code"]=>
  int(385)
  ["type"]=>
  string(12) "T_WHITESPACE"
  ["content"]=>
  string(1) " "
  ["line"]=>
  int(629)
  ["column"]=>
  int(31)
  ["length"]=>
  int(1)
  ["level"]=>
  int(5)
  ["conditions"]=>
  array(5) {
    [65]=>
    int(364)
    [5145]=>
    int(342)
    [5159]=>
    int(322)
    [5183]=>
    int(322)
    [5192]=>
    int(322)
  }
}
```

**Comment by kukulich** [comment]
So the method `getName()` is called with invalid parameter. The bug is somewhere before the call.

**Comment by dereuromark** [comment]
That is possible, does not mean, though, that the defensive coding down the line should be omitted.
A fatal error should be avoided no matter what kind of "strange" code is given, in order for the tool to at least be able to cover the rest of the classes/files.

Maybe we can abort in these cases gracefully by checking the index always, and then on top also make sure that higher logic takes into account such edge cases.

**Comment by kukulich** [comment]
I'm sorry I don't want to add many useless (for me) checks to the code.
