### ISSUE TITLE
[question] How to prevent '@param annotation for parameter "$myparam" missing' when a corresponding typehint exists?

### ISSUE THREAD

**Issue by bperel** [slevomat/coding-standard#1300]
I apologize if this question has already been answered as I think that I saw the solution in the past. I get the warning `phpcs: @param annotation for parameter "$a" missing` when declaring a function like this:
```php
<?php

class A
{

    /** This is my function */
    public function myFunction(string $a)
    {
    }
}
```

- If I remove the comment before the function, I don't get the warning, but I would like to keep this comment.
- If I add the parameter annotation like it's asked, I get `Method \A::myFunction() has useless @param annotation for parameter $a.`, which is indeed what I would like to avoid.

How can I keep my comment and prevent the warning from being triggered?

**Comment by kukulich** [comment]
I think this error does not come from Slevomat CS.

**Comment by bperel** [comment]
> I think the error `@param annotation for parameter "$a" missing` does not come from Slevomat CS.

You're right, `@param annotation for parameter "$a" missing` is [Squiz.Commenting.FunctionComment.MissingParamTag](https://github.com/slevomat/coding-standard/blob/master/build/phpcs.xml#L143), whereas `has useless @param annotation for parameter` comes from Slevomat. Is there a way to have both sniffs running at the same time without triggering warnings?

**Comment by kukulich** [comment]
@bperel Both sniffs cannot work together, as you see. So you have to choose one of them.
