### ISSUE TITLE
Incorrent order of annotations in group.

### ISSUE THREAD

**Issue by kamil-tekiela** [slevomat/coding-standard#1307]
I got this issue:

> Incorrent order of annotations in group.

What does "incorrent" mean? Is it a typo? Should it be "incorrect"?

https://github.com/slevomat/coding-standard/blob/3c38ab6b2a3ed9f78edfadda11f2fc981d5664fb/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php#L578

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/095675d307d23230d0dd01cc8d3b6125d5ebe5fb
