### ISSUE TITLE
ClassConstantVisibilitySniff adds `public` to `public final const`

### ISSUE THREAD

**Issue by canvural** [slevomat/coding-standard#1308]
Hi,

I'm not sure about the PHP 8.1 compatibility of this library. But today I encountered an issue with ClassConstantVisibilitySniff.

It changes `public final const FOO = 'bar` to `public final public const FOO = 'bar'` I expected no change since visibility is already there.

**Comment by kukulich** [comment]
This library is not compatible with any PHP 8.1 syntax because PHPCS itself is not compatible.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/fa7ea63dc313461166cfd41f6ae7d7004fd2b1c6
