### ISSUE TITLE
Closure use trailing comma sniffs

### ISSUE THREAD

**Issue by ondrejmirtes** [slevomat/coding-standard#1312]
Similar to `SlevomatCodingStandard.Functions.DisallowTrailingCommaInDeclaration` and `SlevomatCodingStandard.Functions.RequireTrailingCommaInDeclaration`, there could be a pair of sniffs for closure uses based on this RFC: https://wiki.php.net/rfc/trailing_comma_in_closure_use_list

Thank you.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/0c9f7b8afc36c21d762b76b1e587037f1079dc9a and https://github.com/slevomat/coding-standard/commit/1e7f14704a1ec1264f8b116ad4cf6cfcf6449ee6
