### ISSUE TITLE
Is there a sniff to format array key => value pairs?

### ISSUE THREAD

**Issue by akalongman** [slevomat/coding-standard#1317]
Is there a sniff to format array key => value pairs? Like this:
![Peek 2021-12-20 16-16](https://user-images.githubusercontent.com/423050/146766140-f6986696-d540-42e5-9d0d-e6d08cbc5da3.gif)

**Comment by kukulich** [comment]
This sniff is part of PHPCS itself.

**Comment by akalongman** [comment]
@kukulich did not found. Could you give the sniff name or link?

**Comment by kukulich** [comment]
It may be `ArrayIndentSniff` or `MultipleStatementAlignmentSniff`

**Comment by akalongman** [comment]
Still can not find. I've opened an issue in the PHPCS repo https://github.com/squizlabs/PHP_CodeSniffer/issues/3514

Thank you.
