### ISSUE TITLE
ParameterTypeHintSniff doesn't check closures type hints

### ISSUE THREAD

**Issue by abelharisov** [slevomat/coding-standard#1322]
Hi!
I am using slevomat/coding-standard:7.0.18 with squizlabs/php_codesniffer:3.6.2
I have sniff ParameterTypeHintSniff enabled and I expected that closure parameter type hints are also will be checked. But this rule ignores closures:
```
        $closure = static function ($test): void {
            echo $test;
        };
```
This code will not raise any errors

**Comment by kukulich** [comment]
Yes, that's expected behaviour. Not all types can be write as native type hints and it's diffucult to recognize if the type is missing or cannot be used.

**Comment by abelharisov** [comment]
I there any workaround? Any other rule to enforce using of type hins in closures?
