### ISSUE TITLE
Request: option to ignore octal numbers in RequireNumericLiteralSeparatorSniff

### ISSUE THREAD

**Issue by weirdan** [slevomat/coding-standard#1324]
Currently with `minDigitsBeforeDecimalPoint=3` this sniff enforces separator presence even for octal numbers, e.g. `chmod($filename, 0666)` should be spelled `chmod($filename, 0_666)`. However, it's not how people are used to spell permissions, even if they want decimal numbers spelt as `3_456`.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/3d9522dd7394b08ce3632a26ac7a23a6c2bd1c44
