### ISSUE TITLE
SlevomatCodingStandard.Functions.DisallowTrailingCommaInCall/Declaration but for single line

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#1326]
This often happens when squashing fcn declaration to a single line. Trailing comma stays there.

```php
fn(
    $a,
    $b,
)
```
👇🏾 
```php
fn($a, $b,)
```

Is there a sniff to force no trailling comma in single line call or declaration?

```diff
- fn($a, $b,)
+ fn($a, $b)
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/bb7bcdd8e1e25a66822c388da25c75c5f16c5dc0 and https://github.com/slevomat/coding-standard/commit/1b70ab56feab02cba4315da4bd5de0569c11198f
