### ISSUE TITLE
`DocCommentSpacingSniff` hangs when unusual doc block given

### ISSUE THREAD

**Issue by canvural** [slevomat/coding-standard#1327]
Hi,

After applying some changes to my code base with Rector, I ran the code style script and found this issue.

Rector changes the following docblock
```php
/** @phpstan-return array<string, string> */
```

to 
```php
/** @phpstan-return array<string, string>
* @return array<string, string> */
```

And this causes `DocCommentSpacingSniff` to hang infinitely. (Maybe Rector shouldn't do this but I still think the sniff shouldn't hang)

I also reproduced it in this repo by adding 

```php
/** @phpstan-return array<string, string>
* @return array<string, string> */
public function phpstanReturnAndReturnAnnotations()
{
	return [];
}
```

to [this](https://github.com/slevomat/coding-standard/blob/master/tests/Sniffs/Commenting/data/docCommentSpacingAnnotationsGroupsErrors.php) file. I didn't wanna PR it cause of the infinite hanging. But if you want I can send the PR.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/e5499859eaff8f30629e5fbefe5f92d3cedf81ba
