### ISSUE TITLE
Callable without a return type hint causes an exception to be thrown internally

### ISSUE THREAD

**Issue by internalsystemerror** [slevomat/coding-standard#1330]
Given the following docblock (from https://github.com/laminas/laminas-servicemanager/blob/3.10.x/src/ConfigInterface.php):

```php
/*
 * @psalm-type FactoriesConfigurationType = array<
 *      string,
 *      (class-string<Factory\FactoryInterface>|Factory\FactoryInterface)
 *      |callable(ContainerInterface,string,array<mixed>|null)
 * >
 */
```

An exception is thrown using `SlevomatCodingStandard.TypeHints.ReturnTypeHint`

and gives the following output:

```
ise@ise-surface:~/projects/laminas/laminas-servicemanager$ vendor/bin/phpcs -s
...........E............................................ 56 / 56 (100%)



FILE: src/ConfigInterface.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------------------------------------------------------------------------------------------
  1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: Invalid @psalm-type annotation.
    |       | (Internal.Exception)
 56 | ERROR | Doc comment for parameter "$serviceManager" missing (Squiz.Commenting.FunctionComment.MissingParamTag)
----------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 299ms; Memory: 14MB

```

This is caused because the callable doesn't contain a return type hint. Adding one, the error goes away. This took some time to debug and figure out, and if this should be reported as an error, a better error message would seem to be needed.

**Comment by Xerkus** [comment]
Issue traced to https://github.com/slevomat/coding-standard/blob/e5499859eaff8f30629e5fbefe5f92d3cedf81ba/SlevomatCodingStandard/Helpers/AnnotationHelper.php#L355 failing to parse annotation

**Comment by kukulich** [comment]
I can fix the internal error - will probably ignore the invalid `@psalm-type`...

**Comment by kukulich** [comment]
Invalid annotations will be ignored: https://github.com/slevomat/coding-standard/commit/8588446c4dbfb96939ee32edebf4e8e4d775efa3
