### ISSUE TITLE
UnusedUsesSniff incorrectly removes group import statement

### ISSUE THREAD

**Issue by Ilyes512** [slevomat/coding-standard#1338]
`SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff` incorrectly removes used import when you use grouped imports.

Configuration:

```php
// This is used in combination with ECS - https://github.com/slevomat/coding-standard which is
// basically a wrapper around PHP_CodeSniffer and PHP-CS-Fixer
$services->set(UnusedUsesSniff::class)
    ->property('searchAnnotations', true);
```

This is an example where I was able to replicate the problem:

```php
<?php

namespace MyAcme;

class Settings
{
    public const USERNAME = 'myname';
}

namespace MySpace;

use MyAcme\{Settings};

class Foobar
{
    public function myMethod(): string
    {
        return Settings::USERNAME;
    }
}
```

When I run it I get the following report:

```
1) issues/GroupImport_issue.php

    ---------- begin diff ----------
@@ -9,7 +9,6 @@

 namespace MySpace;

-use MyAcme\{Settings};

 class Foobar
 {
    ----------- end diff -----------


Applied checkers:

 * SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff.UnusedUse
```

I have tested it using a ruleset that only includes the UnusedUsesSniff.

**Comment by kukulich** [comment]
We don't support grouped `use`.

**Comment by Ilyes512** [comment]
FYI I don't want to use grouped `use` imports and I do use it togather with your sniff `SlevomatCodingStandard\Sniffs\Namespaces\DisallowGroupUseSniff`. 

If you dont support it anyways, wouldn;t it make sense to detect the useage and stop the `UnusedUsesSniff` from doing anything in that specific file and instead just report that it uses unsupported grouped `use` imports?

What happens now is that `DisallowGroupUseSniff` reports it (without being able to fix it because it lacks an autofixer, but thats fine) and  `UnusedUsesSniff ` just removes the complete import. So when you run it again, I don't get the warning anymore. 

Normally I would see the warning and fix it, but sometimes I want to apply the autofixers first and then go ahead and fix the warnings without autofixers. Another case is applying the fixers on a already existing project which results in ALLOT of changes... and yes I try to review the changes, but something like this is really unexpected (I just don't expect it to just remove the import line).

**Comment by kukulich** [comment]
Changed in https://github.com/slevomat/coding-standard/commit/c5cf9b5c1a44b8abba1279a199dcac206d1266c3
