### ISSUE TITLE
ParameterTypeHint and PropertyTypeHint don't support implicitly inherited docs

### ISSUE THREAD

**Issue by TravisCarden** [slevomat/coding-standard#1341]
`SlevomatCodingStandard.TypeHints.ParameterTypeHint`, `SlevomatCodingStandard.TypeHints.PropertyTypeHint`, and possibly other sniffs apparently don't look at docs inherited from parent classes or interfaces without an explicit `@inheritdoc` annotation. Especially in light of `SlevomatCodingStandard.Commenting.UselessInheritDocComment`, this seems undesirable.

**Comment by kukulich** [comment]
Yes.

**Comment by TravisCarden** [comment]
Lol. Would you care to elaborate, @kukulich? Is this a "won't fix" or "works as designed" or... ?

**Comment by kukulich** [comment]
PHPCS works in one-file scope.

**Comment by TravisCarden** [comment]
Oh, I see. I thought it was actually checking the parent class when it found an `@inheritdoc` annotation, but it must just be ignoring it then. Thanks for clarifying.
