### ISSUE TITLE
Method/function named "empty" giving internal error in FunctionHelper

### ISSUE THREAD

**Issue by janedbal** [slevomat/coding-standard#1347]
Given following php file

```
<?php function empty() {}
```

I'm getting internal error:

```
An error occurred during processing; checking has been aborted. The error message was: Undefined array key "" in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/FunctionHelper.php on line 92 (Internal.Exception)
```

Not sure which sniff is causing it, we are using plenty of them. I can give you a list if this wont be replicable for you. Used version: 7.0.19

**Comment by kukulich** [comment]
It looks as duplicate to https://github.com/slevomat/coding-standard/issues/1344

**Comment by janedbal** [comment]
Confirmed, I missed that. Sorry, closing.
