### ISSUE TITLE
`slevomat/coding-standard:7.0.20` not compatible with `phpstan/phpdoc-parser:1.4.0`

### ISSUE THREAD

**Issue by Ocramius** [slevomat/coding-standard#1348]
Ref https://github.com/psr7-sessions/storageless/runs/5731835587?check_suite_focus=true#step:3:349

Getting:

```
Error: An error occurred during processing; checking has been aborted. The error message was: Undefined property: PHPStan\PhpDocParser\Ast\Type\ConditionalTypeNode::$name in /github/workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php on line 263
```

https://github.com/slevomat/coding-standard/blob/6a7927694cfbf376cbba88c44bfb62aa21b6ec16/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php#L255-L264

Seems like the structure of `TypeNode` changed? :thinking:

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/be7898df20714c0118b17562a626050207bb1940

New release coming soon.
