### ISSUE TITLE
Treat classes/enums, interfaces and traits differently

### ISSUE THREAD

**Issue by oojacoboo** [slevomat/coding-standard#1351]
Interfaces can be extremely simple, classes not so much and traits differ.  The need to adhere to the same code styles for each of these, while uniform, isn't always ideal.  For instance, an interface could be very compressed, whereas a class desiring more line spacing between members.  Traits would likely follow class styles, but I see no reason to not offer the flexibility.

**Comment by kukulich** [comment]
Interface is "class" so it should be treated in the same way.
