### ISSUE TITLE
FullyQualifiedGlobalFunctions does not work

### ISSUE THREAD

**Issue by kkmuffme** [slevomat/coding-standard#1353]
version 7.1.0

The following three rules never give an error and are also not auto-fixed, despiting being auto-fixable.

```
<rule ref="SlevomatCodingStandard.PHP.OptimizedFunctionsWithoutUnpacking"/>
<rule ref="SlevomatCodingStandard.Namespaces.FullyQualifiedGlobalFunctions"/>
<rule ref="SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly"/>
```

Code example (for FullyQualifiedGlobalFunctions - this should however also trigger ReferenceUsedNamesOnly when using default config without any settings)

```php
<?php
if ( is_array( $foo ) ) {
    echo "bar";
}
```

Expected auto-fix to:

```php
<?php
if ( \is_array( $foo ) ) {
    echo "bar";
}
```

**Comment by kukulich** [comment]
Works for me 🤷‍♂️ There's probably something wrong in your configuration.

**Comment by kkmuffme** [comment]
My file:

```php
<?php
if ( is_array( $foo ) ) {
    echo "bar";
}

// just to test that auto-fixing works
$foo = true ? true : false;
```

My config: (useless ternary is just there to confirm that auto-fixing works)

```xml
<?xml version="1.0"?>
<ruleset name="devste">
	<rule ref="SlevomatCodingStandard.ControlStructures.UselessTernaryOperator"/>
	<rule ref="SlevomatCodingStandard.Namespaces.FullyQualifiedGlobalFunctions"/>
</ruleset>
```

The command I run:
```
php -dxdebug.mode=off /opt/composer/vendor/bin/phpcbf --standard=/absolute/path/phpcs-ruleset.xml /another/absolute/path/my.php
```


Result:
```php
<?php
if ( is_array( $foo ) ) {
    echo "bar";
}

// just to test that auto-fixing works
$foo = true;
```

The ternary is correctly auto-fixed, but the is_array is not global namespaced.

**Comment by kukulich** [comment]
@kkmuffme You have to add namespace to your file.

**Comment by kkmuffme** [comment]
Oh, ok.
But when using parameter `includeSpecialFunctions` it should work even when no namespace is specified? (so it will load the zend optimized functions in all cases, not just when a namespaces is specified)

**Comment by kukulich** [comment]
It’s useless to add \ when there’s no namespace.

**Comment by kkmuffme** [comment]
No, it's not. See https://tideways.com/profiler/blog/compiler-optimized-php-functions

**Comment by kukulich** [comment]
@kkmuffme the optimization works only in namespaced code

**Comment by kkmuffme** [comment]
You sure? When doing a simple while loop with and without \ in non-namespaced code I get a 1% performance gain by prefixing with backslash.
