### ISSUE TITLE
Bug: Undefined index in UselessIfConditionWithReturnSniff.php

### ISSUE THREAD

**Issue by kkmuffme** [slevomat/coding-standard#1354]
https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/ControlStructures/UselessIfConditionWithReturnSniff.php#L113

I'm getting a notice from this:
>An error occurred during processing; checking has been aborted. The error message was: Undefined index:  in /absolute_path/vendor/slevomat/coding-standard/SlevomatCodingStandard/ Sniffs/ControlStructures/UselessIfConditionWithReturnSniff.php on line 113

Needs to be changed to:

```php
if (!isset($tokens[$returnPointer]['code']) || $tokens[$returnPointer]['code'] !== T_RETURN) {
```

However, I think it makes sense to investigate why this issue happens in the first place.

Minium reproducable code:

```php
<?php
if ( !isset( $hello ) ) {
	return false;
}
```

with config:

```
<?xml version="1.0"?>
<ruleset name="devste">
	<rule ref="SlevomatCodingStandard.ControlStructures.UselessIfConditionWithReturn"/>
</ruleset>
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/124863045038d1dccf3b437cd39aa752a69658c2
