### ISSUE TITLE
Error after running phpcbf command 

### ISSUE THREAD

**Issue by kamreo** [slevomat/coding-standard#1363]
Hi guys! 

After I ran phpcbf I got uncaught error: TokenIterator not found in AnnotationHelper.php.

Full error message
`PHP Fatal error:  Uncaught Error: Class 'PHPStan\PhpDocParser\Parser\TokenIterator' not found in /project_dir/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php:521
Stack trace:
#0 /project_dir/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(338): SlevomatCodingStandard\Helpers\AnnotationHelper::parseAnnotationContent()
#1 /project_dir/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(45): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 /project_dir/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(34): SlevomatCodingStandard\Helpers\SniffLocalCache::setIfNotCached()
#3 /project_dir/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(359): SlevomatCodingStandard\Helpers\SniffLocalCache::getAndS in  /project_dir/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 521`

What could cause this issue?

**Comment by kukulich** [comment]
There's probably something with your autoload.
