### ISSUE TITLE
Function named "object" is always reported as unused

### ISSUE THREAD

**Issue by shadowhand** [slevomat/coding-standard#1365]
In some file, perhaps `functions.php`:

```php
namespace Acme;

function object(): object
{
    return new \stdClass();
}
```

In another file, perhaps `ResourceSchema.php`:

```php
namespace Acme\Resources;

use function Acme\object; // <-- will be reported as unused

final class ResourceSchema
{
    public function attributes(object $model): array
    {
        return [
            'id' => $model->id,
            'metadata' => $model->metdata ? $model->metdata : object(),
        ];
    }
}
```

The exact sniff reported is `SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse`.

The reason for having the function `object()` to account for an empty array being JSON encoded as `[]` instead of `{}`, such as when the `$model->metadata` would normally be an associative array.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/c1b4a8c9c8932032de79ced929c4069de0ba29d6

**Comment by shadowhand** [comment]
Thank you!
