### ISSUE TITLE
Undefined index: scope_closer

### ISSUE THREAD

**Issue by enumag** [slevomat/coding-standard#1370]
Same issue as https://github.com/slevomat/coding-standard/issues/902.

I found you had a workaround for this here: https://github.com/slevomat/coding-standard/commit/4c88f6c3d81d189bf2f4dfb0946f145d816a2048

But it seems this has been removed since then? Why? :thinking: We're using slevomat/coding-standard v7.0.18. I checked the code in v7.0.20 but the workaround doesn't seem to be there either.

**Comment by kukulich** [comment]
I'm sorry but I don't want to have dead code here.

**Comment by enumag** [comment]
Which is the last version of slevomat/coding-standard that had the workaround then?

**Comment by enumag** [comment]
Nevermind my colleague solved it. Most likely some new PHPCS issue. It was caused by

```
    public function __construct(
        private EntityManager $entityManager,
        private Clock $clock,
    )
    {}
```

instead of


```
    public function __construct(
        private EntityManager $entityManager,
        private Clock $clock,
    ) {
    }
```
