### ISSUE TITLE
PHP Notice in ForbiddenPublicPropertySniff for variables with scope modifier "var"

### ISSUE THREAD

**Issue by sveneld** [slevomat/coding-standard#1376]
PHP Notice:  Undefined index:  in ..../vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ForbiddenPublicPropertySniff.php on line 68

Caused when checking this code
```
class Example
{
    var $example = ';
}
```
Also this type of scope modifier does not marked as error by this sniff, but it should because var is equal to public. I understand that it is very old code and should be deprecated, but it still exist...

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/5bba04904bd72995adce0ca7146e30cd8410c3af

**Comment by sveneld** [comment]
When new tag will be released?
