### ISSUE TITLE
Incompatible with `phpstan/phpdoc-parser` >= 1.6

### ISSUE THREAD

**Issue by martijnc** [slevomat/coding-standard#1379]
`phpstan/phpdoc-parser@1.6.0` introduced `PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode` in https://github.com/phpstan/phpdoc-parser/commit/9d452051cbb2676d232a61920b5a9f336207af65 which it returns instead of `PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode` for docblock `@param` definitions without a type.

Slevomat typehints `ParamTagValueNode` in `ParameterAnnotation::__construct()`, but as of `phpdoc-parser@1.6.0` this can also be `TypelessParamTagValueNode` resulting in the following error when PHPCS encounters a docblock with a typeless `@param`.

> Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in /Volumes/Projects/mortar/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /Volumes/Projects/mortar/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31

**Comment by esserj** [comment]
example annotation
`@param $someTypelessParam`

**Comment by akalongman** [comment]
As a workeround I added `"phpstan/phpdoc-parser": "1.5.*"` in a composer.json

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/55e5dc5611359bacc64b8cc64fca007c7150d523

**Comment by Ilyes512** [comment]
Awesome that it was fixed so quickly! Can we have a new tag/release @kukulich? Thanks!

**Comment by kukulich** [comment]
@Ilyes512 There's sponsor button on the top of this page.

**Comment by Ilyes512** [comment]
Whoa... that does sound a little passive aggressive, but I will definitly keep you in mind in future :). Your work definitly deserve compensation!

**Comment by kukulich** [comment]
It's easy. I work on this mostly in my free time. So if you ask for release, you can motivate me to do it :) Or just wait :)

**Comment by ViktorCollin** [comment]
First of all I want to thank you for your good work of this! 

Im curious if it would be possible to patch this even in the 7.2 branch and release a fix version for it?
