### ISSUE TITLE
Problem mixing use statements im native enum

### ISSUE THREAD

**Issue by lucraraujo** [slevomat/coding-standard#1386]
I have this enum:
```php
<?php

declare(strict_types=1);

namespace App\Enums;

use JsonSerializable;

enum SomeEnum: string implements Enum, JsonSerializable
{
    use EnumTrait;

    case Foo = 'FOO;
    case Bar = 'BAR;

    public function label(): string
    {
        return match ($this) {
            self::Foo=> 'foos
            self::Bar=> 'bars,
        };
    }
}

```

As you can see, I import JsonSerializable to implement and I have some methods in a Trait.
The problem is that the sniffer "SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses.IncorrectlyOrderedUses" finds that the "use" statements are out of order.
To add salt to the issue, it tries to fix the problem by deleting the enum declaration line (line 9).

**Comment by kukulich** [comment]
There’s no released support of enums currently.

**Comment by lucraraujo** [comment]
Native enum is now supported by PHP_CodeSniffer. Check the latest release.

**Comment by kukulich** [comment]
I know, the enums support in PHPCS was made by me, but there’s no released support of enums in this repository.
