### ISSUE TITLE
Issue when 7.0.20 is used with squizlabs/PHP_CodeSniffer 3.7

### ISSUE THREAD

**Issue by pistej** [slevomat/coding-standard#1387]
An error occurred during processing; checking has been aborted. The error message was: Undefined array key "" in  ... slevomat/coding-standard/SlevomatCodingStandard/Helpers/FunctionHelper.php on line 92 (Internal.Exception)

`Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined array key "" in /root/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/FunctionHelper.php on line 98 in /root/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php:604
Stack trace:
#0 /root/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/FunctionHelper.php(98): PHP_CodeSniffer\Runner->handleErrors(2, 'Undefined array...', '/root/.composer...', 98)
#1 /root/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php(334): SlevomatCodingStandard\Helpers\FunctionHelper::getName(Object(PHP_CodeSniffer\Files\LocalFile), 371)
#2 /root/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php(293): SlevomatCodingStandard\Sniffs\Classes\ClassStructureSniff->getGroupForToken(Object(PHP_CodeSniffer\Files\LocalFile), 371)
#3 /root/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php(213): SlevomatCodingStandard\Sniffs\Classes\ClassStructureSniff->findNextGroup(Object(PHP_CodeSniffer\Files\LocalFile), 64, Array)
#4 /root/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Classes\ClassStructureSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 27)
#5 /root/.composer/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#6 /root/.composer/vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#7 /root/.composer/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(52): PHP_CodeSniffer\Fixer->fixFile()
#8 /root/.composer/vendor/squizlabs/php_codesniffer/src/Reporter.php(285): PHP_CodeSniffer\Reports\Cbf->generateFileReport(Array, Object(PHP_CodeSniffer\Files\LocalFile), false, 310)
#9 /root/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(654): PHP_CodeSniffer\Reporter->cacheFileReport(Object(PHP_CodeSniffer\Files\LocalFile), Object(PHP_CodeSniffer\Config))
#10 /root/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#11 /root/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(200): PHP_CodeSniffer\Runner->run()
#12 /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcbf(18): PHP_CodeSniffer\Runner->runPHPCBF()
#13 /root/.composer/vendor/bin/phpcbf(120): include('/root/.composer...')
#14 {main}
  thrown in /root/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php on line 604
`

**Comment by kukulich** [comment]
Please use last version.
