### ISSUE TITLE
Feature : detect class properties not declared

### ISSUE THREAD

**Issue by momala454** [slevomat/coding-standard#1392]
I'm not sure if it has already been mentioned, but I didn't found it.

Is it possible to detect this typo by detecting properties not declared ?

```php

class hello
{
    string $world;

    public function __construct(string $world)
    {
        $this->woldr = $world; // typo
    }
}

```

**Comment by kukulich** [comment]
PHPStan or Psalm are better for this.

**Comment by momala454** [comment]
"dynamic properties" are deprecated as of php8.2 : https://wiki.php.net/rfc/deprecate_dynamic_properties
So I think detecting those dynamic properties will need to be done for the release of PHP 8.2
