### ISSUE TITLE
MissingTraversableTypeHintSpecification for promoted properties

### ISSUE THREAD

**Issue by DanielBadura** [slevomat/coding-standard#1398]
Hello 👋 

i just encounterd a missing TypeHint spec for this file:
```php
<?php

declare(strict_types=1);

namespace Patchlevel\EventSourcing\Metadata\Event;

final class EventMetadata
{
    public function __construct(
        public readonly string $name,
        /** @var array<string, EventPropertyMetadata> */
        public readonly array $properties = []
    ) {
    }
}
```

The concrete error is:
```
 9 | ERROR | Method \Patchlevel\EventSourcing\Metadata\Event\EventMetadata::__construct() does not have @param annotation for its traversable parameter $properties.
   |       | (SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingTraversableTypeHintSpecification)
```

I think this should be valid. What do you think?

**Comment by bkdotcom** [comment]
I believe Slevomat is looking for a more specific type hint 
"array" isn't very descriptive  
something like `array<string, int|string>`
where 
string = the keys
int|string = the values

**Comment by DanielBadura** [comment]
The type is provided in the example 🤔

**Comment by bkdotcom** [comment]
d'oh.   but is that an accepted way to document a @param ?

vs

    /**
     * @param array<string, EventPropertyMetadata> $properties
     */
    public function __construct(
        public readonly string $name,
        public readonly array $properties = []
    ) {
    }

**Comment by DanielBadura** [comment]
AFAIK it is for promoted properties.

**Comment by kukulich** [comment]
I was waiting who will report it first :) Implemented in https://github.com/slevomat/coding-standard/commit/0cec515440c92735ce3cc35cfb0891d89080a72b
