### ISSUE TITLE
How to find in which file is problem?

### ISSUE THREAD

**Issue by motorcb** [slevomat/coding-standard#1405]
PHP Fatal error:  Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in C:\www\nette-coding-standard\vendor\slevomat\coding-standard\SlevomatCodingStandard\Helpers\AnnotationHelper.php on line 357 and defined in C:\www\nette-coding-standard\vendor\slevomat\coding-standard\SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation.php:31

https://forum.nette.org/cs/35311-nette-code-checker-jak-zjistit-kde-je-problem

**Comment by kukulich** [comment]
Use latest version.
