### ISSUE TITLE
README.md has become bloated

### ISSUE THREAD

**Issue by bkdotcom** [slevomat/coding-standard#1408]
navigation currently consists only of

1. [Sniffs included in this standard](https://github.com/slevomat/coding-standard#sniffs-included-in-this-standard)
  - [Functional - improving the safety and behaviour of code](https://github.com/slevomat/coding-standard#functional---improving-the-safety-and-behaviour-of-code)
  - [Cleaning - detecting dead code](https://github.com/slevomat/coding-standard#cleaning---detecting-dead-code)
  - [Formatting - rules for consistent code looks](https://github.com/slevomat/coding-standard#formatting---rules-for-consistent-code-looks)

than "scrolls for miles"

Thoughts on breaking the sniffs into separate readme files?

Perhaps by "sniff category"?

* Arrays
* Classes
* Commenting
* Complexity
* ControlStructures
* Exceptions
* Files
* Functions
* Namespaces
* Numbers
* Operators
* PHP
* TypeHints
* Variables
* Whitespaces

In favor of / in addition to "functional", "cleaning" & "formatting" ?

**Comment by bkdotcom** [comment]
Speaking of documentation:
An "annotated" xml file that contains every available sniff with every option explicitly set would be helpful

**Comment by kukulich** [comment]
I’m ok to split the readme to more files (perhaps in “doc” directory) - based on the sniff category. 

We can have only sniff names in the readme - as links to the new files.

**Comment by vojtech-dobes** [comment]
As a very happy but picky user of this coding standard, I am super glad for having all the detailed docs in single file. Makes it very easy to find what I am looking for.

**Comment by kukulich** [comment]
@vojtech-dobes 

> We can have only sniff names in the readme - as links to the new files.

Is this not sufficient?

**Comment by vojtech-dobes** [comment]
It's fine :)

**Comment by o5** [comment]
> I’m ok to split the readme to more files (perhaps in “doc” directory) - based on the sniff category.

It would be nice to also think about my old issue https://github.com/slevomat/coding-standard/issues/62 :) There is a dead link and I cannot edit now, this is the right one [UnnecessaryStringConcatStandard](https://github.com/squizlabs/PHP_CodeSniffer/blob/53e0f5/src/Standards/Generic/Docs/Strings/UnnecessaryStringConcatStandard.xml).

What about something what will grab fixture files like [backedEnumTypeSpacingErrors](https://github.com/slevomat/coding-standard/blob/02f273/tests/Sniffs/Classes/data/backedEnumTypeSpacingErrors.php) and [backedEnumTypeSpacingErrors.fixed.php](https://github.com/slevomat/coding-standard/blob/02f273/tests/Sniffs/Classes/data/backedEnumTypeSpacingErrors.fixed.php) and create something similar like

```xml
<!-- SlevomatCodingStandard/Docs/Classes/BackedEnumTypeSpacingSniff.xml  -->
<documentation title="Backed Enum Type Spacing">
    <standard>
    <![CDATA[
    TBD
    ]]>
    </standard>
    <code_comparison>
        <code title="Valid">
        <![CDATA[
enum BackedInt: int
{

}

enum BackedString: string
{

}
        ]]>
        </code>
        <code title="Invalid>
        <![CDATA[
enum BackedInt :   int
{

}

enum BackedString   :string
{

}
        ]]>
        </code>
    </code_comparison>
</documentation>
```
