### ISSUE TITLE
Final class sniff request

### ISSUE THREAD

**Issue by lookyman** [slevomat/coding-standard#142]
Would there be interest in a sniff that reports non-final concrete classes? If yes, I could try to prepare a pull request. I have a simple one [here](https://github.com/lookyman/coding-standard/blob/1e5f433cf7754708cb6f795359d94b8b3c8bb2c2/LookymanCodingStandard/Sniffs/Classes/FinalClassSniff.php), but would maybe like to make it a little bit more "clever", possibly by implementing ideas from https://ocramius.github.io/blog/when-to-declare-classes-final/, and with options to ignore certain groups of classes based on name, type, or other attributes.

**Comment by ondrejmirtes** [comment]
That is a pretty opinionated approach. For one, after making a class final, you can't mock it in PHPUnit. And I don't see a point in creating an interface with a single implementation, even just for the naming issues.

But creating such a sniff should be easy (register for `T_CLASS` token and look if there's `T_FINAL`, `T_ABSTRACT` or `T_NEW` in case of anonymous classes in front of it), but I don't think it should be promoted here.

**Comment by TomasVotruba** [comment]
@lookyman I've read the same post and use [FinalInterfaceSniff](https://github.com/Symplify/CodingStandard#finalinterfacesniff-class) for years.

Also it's [advanced version](https://github.com/Symplify/CodingStandard/blob/master/src/Sniffs/Classes/EqualInterfaceImplementationSniff.php) that checks that class has public methods, that are covered by interface methods. No extra.

Feel free [to create issue](https://github.com/Symplify/Symplify/issues) and add your ideas.
