### ISSUE TITLE
is there a sniff for forcing use statements instead of backslash references

### ISSUE THREAD

**Issue by arderyp** [slevomat/coding-standard#1430]
I did a quick search but couldn't find anything, please forgive me if I missed it.

What I am talking about is forcing

```php
use DateTime;

$dateTime = new DateTime(...);
```

instead of 

```
$dateTime = new \DateTime(...);
```

likewise, fixing things like `\intval` to `intval`

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesreferenceusednamesonly-
