### ISSUE TITLE
@var above return statement

### ISSUE THREAD

**Issue by mabar** [slevomat/coding-standard#1463]
This is supported by phpstan and phpstorm, but coding standard reports `SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.InvalidFormat`

```php
function test(): false
{
	$a = true;
	
	/** @var false */
	return $a;
}
```

https://phpstan.org/r/bcd2fb18-bd6d-420e-a2f8-cc2c3a5d704b
https://blog.jetbrains.com/phpstorm/2022/06/phpstorm-2022-2-eap-5/#anonymous_var_in_return_statements_wi

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentinginlinedoccommentdeclaration-

**Comment by mabar** [comment]
Thanks, absolutely missed that one 🙈
