### ISSUE TITLE
SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameInAnnotation.NonFullyQualifiedClassName does not support int<min, max> syntax

### ISSUE THREAD

**Issue by lptn** [slevomat/coding-standard#1464]
It wrongly converts [int range syntax](https://phpstan.org/writing-php-code/phpdoc-types#integer-ranges)
```php
/** @return int<0, max> */
/** @return int<min, 0> */
```
into
```php
/** @return int<0,  \Current\Namespace\max> */
/** @return int<\Current\Namespace\min, 0> */
```

```
name     : slevomat/coding-standard
versions : * 8.6.2

```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/cef466a5483282aa7505638728812ec009e5d906

**Comment by lptn** [comment]
@kukulich 
BTW, Psalm team just introduced a new unofficial PHPDoc type: `strict-array` (aka sealed arrays). Should I create a new issue to ask to support it?

Docs: https://github.com/vimeo/psalm/blob/master/docs/annotating_code/type_syntax/array_types.md#sealed-object-like-arrays

**Comment by kukulich** [comment]
@lptn PR is better :)
