### ISSUE TITLE
phpcbf # Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Creation of dynamic property 

### ISSUE THREAD

**Issue by LucasHantz** [slevomat/coding-standard#1477]
Running the new version of PHP 8.2.0 and freshly baked 8.7.0 version from yesterday and I'm still getting fatal errors when running phpcbf

Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBeforeFirstUse is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBeforeFirstUseWhenFirstInClass is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBetweenUses is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountAfterLastUse is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountAfterLastUseWhenLastInClass is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\ControlStructures\DisallowYodaComparisonSniff::$alwaysVariableOnRight is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\ControlStructures\DisallowYodaComparisonSniff::$DisallowYodaComparisonSniff is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBeforeFirstUse is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBeforeFirstUseWhenFirstInClass is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBetweenUses is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountAfterLastUse is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountAfterLastUseWhenLastInClass is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\ControlStructures\DisallowYodaComparisonSniff::$alwaysVariableOnRight is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\ControlStructures\DisallowYodaComparisonSniff::$DisallowYodaComparisonSniff is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Creation of dynamic property SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::$linesCountBeforeFirstUse is deprecated in vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326 in vendor/squizlabs/php_codesniffer/src/Runner.php:604

**Comment by kukulich** [comment]
It looks you have bugs in your configuration.

**Comment by LucasHantz** [comment]
Care to explain @kukulich before just closing the ticket please?

**Comment by LucasHantz** [comment]
<rule ref="SlevomatCodingStandard.Classes.PropertySpacing">
        <properties>
            <property name="linesCountBeforeFirstUse" value="1"/>
            <property name="linesCountBeforeFirstUseWhenFirstInClass" value="1"/>
            <property name="linesCountBetweenUses" value="0"/>
            <property name="linesCountAfterLastUse" value="1"/>
            <property name="linesCountAfterLastUseWhenLastInClass" value="1"/>
        </properties>
    </rule>

**Comment by LucasHantz** [comment]
This is the one that generates the Fatal error, don't see what is wrong there

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/blob/master/doc/classes.md#slevomatcodingstandardclassespropertyspacing-

**Comment by LucasHantz** [comment]
OK thank you. The new PHP version highlighted what my eyes couldn't see before. Sorry for the trouble.
