### ISSUE TITLE
Sniff to check enum case spacing

### ISSUE THREAD

**Issue by stlrnz** [slevomat/coding-standard#1479]
I'd like to ask if there is an existing Sniff to check for spaces between `case`s in native `enum` declarations?
Something like `SlevomatCodingStandard.Classes.PropertySpacing` would be nice.

I want to prevent declations like this.
```php
<?php

enum SimpleEnum
{
    case C1;

    case C2;
    case C3;
}
```

And instead force this.
```php
<?php

enum SimpleEnum
{
    case C1;
    case C2;
    case C3;
}
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/46984355979bc8c167525da9fb7828cd695ca599
