### ISSUE TITLE
ModernClassNameReference breaks get_class() with non-$this parameter

### ISSUE THREAD

**Issue by christopheg** [slevomat/coding-standard#1483]
```
<?php
class Test {
}

$var = new Test();
echo get_class($var);
```
triggers
`Class name referenced via call of function get_class().`

What is the preferred way to get the classname of a initiated object?
`$var::class`
is only available as of PHP 8

**Comment by kukulich** [comment]
If you still support PHP < 8, you can just disable the sniff.
