### ISSUE TITLE
Recommendation on if without curly braces?

### ISSUE THREAD

**Issue by MikeiLL** [slevomat/coding-standard#1488]
Thanks for the great work.

In this [closed issue](https://github.com/slevomat/coding-standard/issues/819) you mention that the Exception is intended.

Sorry for the spam, but I could use some direction as to _what_ I would do to get around it, or exactly what is happening when I include these standards with my `phpcbf` configs.

**Comment by kukulich** [comment]
I'm sorry I don't understand what do you want.

**Comment by bkdotcom** [comment]
Either

a)  add brackets to your control structures (recommended / bare minimum coding standard)

or 

b) don't use the following sniffs (which throw the exception if missing brackets)

* ControlStructures.ParentCallSpacingSniff 
* ControlStructures.BlockControlStructureSpacingSniff
* ControlStructures JumpStatementsSpacingSniff

**Comment by MikeiLL** [comment]
> Either
> 
> a) add brackets to your control structures (recommended / bare minimum coding standard)
> 
> or
> 

Thanks. I think maybe the Exception pops up when using either `else if` as opposed to `elseif`. I think they may also pop up with `else:` syntax. I remember it was a little bit unclear prevented phpcbf from running succesfully.

**Comment by bkdotcom** [comment]
@kukulich   indeed a bug

```
if (false) {	
} else if (false) {
}
```
will throw '"else" without curly braces is not supported.' Exception

the `T_ELSE`check needs to check if the next effective token is a `T_IF`

**Comment by kukulich** [comment]
@bkdotcom The exception is intended in this case.

**Comment by bkdotcom** [comment]
Perhaps the exception message should be "use of `else if` is not supported"   ?

**Comment by MikeiLL** [comment]
> Perhaps the exception message should be "use of `else if` is not supported" ?

Maybe even, "Use of `else if` is not supported. Use `elseif` instead (if an else is necessary)."
