### ISSUE TITLE
PHP 8.2 deprecation warning

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [slevomat/coding-standard#1489]
When I try to run Slevomat Coding standards with PHP 8.2, it gives the following deprecation warning:
```shell
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff::$newlinesCountBetweenOpenTagAndDeclare is deprecated in .../vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1326
```
To be clear: I upgraded to PHP 8.2 and ran composer update and composer install.

My composer.json line looks as follows:
```json
"squizlabs/php_codesniffer": "^3.7"
```

Did I do something wrong here?

**Comment by kukulich** [comment]
The option does not exist anymore: https://github.com/slevomat/coding-standard/blob/master/doc/type-hints.md#slevomatcodingstandardtypehintsdeclarestricttypes-

**Comment by TeaDrinkingProgrammer** [comment]
Thanks for the heads-up, should have read the documentation first, my bad. For anyone trying to fix the situation, substitute the property with linesCountBeforeDeclare.
