### ISSUE TITLE
Compatibility to codesniffer 3.*

### ISSUE THREAD

**Issue by alexz707** [slevomat/coding-standard#149]
Hi!

do you plan to upgrade the composer dependencies so the version 3 of php codesniffer will be supported?

regards
Alex

**Comment by kukulich** [comment]
@alexz707 You can try branch [phpcs3](https://github.com/slevomat/coding-standard/tree/phpcs3). PHPCS 3 is not released yet and is not compatible with PHPCS 2. So when PHPCS3 is released, I will have to release new version of our sniffs.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/pull/151

**Comment by alexz707** [comment]
Seems to be working at least for me! 👍 
hope you will release a stable version soon ;) 
keep up the good work!

**Comment by kukulich** [comment]
@alexz707 There's a bug in 3.0.0 so I need to wait for at least 3.0.1.

**Comment by TomasVotruba** [comment]
This can be closed, as CodeSniffer 3.0.1 was released and 3.0 for this package was released.

**Comment by kukulich** [comment]
Version 3.0 with PHPCodeSniffer 3.0 support has been released.
