### ISSUE TITLE
Feature request:  TrailingArrayCommaSniff should also work with T_ARRAY (in addition to T_OPEN_SHORT_ARRAY) ?

### ISSUE THREAD

**Issue by bkdotcom** [slevomat/coding-standard#1492]
> This sniff enforces trailing commas in multi-line arrays and requires short array syntax `[]`

Not sure why it's currently coded to only perform the sniff on T_OPEN_SHORT_ARRAY

I was able to get this sniff to also work with T_ARRAY with minor tweaking...

may I create a pull request?
Should it be configurable, which types of arrays will be sniffed?

**Comment by kukulich** [comment]
> Not sure why it's currently coded to only perform the sniff on T_OPEN_SHORT_ARRAY

Because it looks nobody needs it :)

> may I create a pull request?

Yes.

> Should it be configurable, which types of arrays will be sniffed?

No, it can just support both types.

**Comment by bkdotcom** [comment]
resolved with #1495
