### ISSUE TITLE
Sniff request:  Arrays.SortedByKey

### ISSUE THREAD

**Issue by bkdotcom** [slevomat/coding-standard#1499]
Sorted arrays greatly help with maintainability / reducing merge conflicts

    $keyedArray = array(
        'foo' => 'hello world',
        'bar' => 'some value',
    );

should be 

    $keyedArray = array(
        'bar' => 'some value',
        'foo' => 'hello world',
    );

Sniff would not apply to non-keyed arrays

    $thisIsFine = array(
        'some value',
        'hello world',
    );

Other sort related sniffs

* [SlevomatCodingStandard.Attributes.AttributesOrder](https://github.com/slevomat/coding-standard/blob/master/doc/attributes.md#slevomatcodingstandardattributesattributesorder-)
* [SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses](https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesalphabeticallysorteduses-)
* [SlevomatCodingStandard.Classes.ClassStructure](https://github.com/slevomat/coding-standard/blob/master/doc/classes.md#slevomatcodingstandardclassesclassstructure-)

Thoughts?

**Comment by kukulich** [comment]
I don't see any reason why not :)

**Comment by bkdotcom** [comment]
@kukulich 

I'm making good progress on this sniff  (and creating a ArrayHelper class in the process)..   

It's quickly become apparent that this sniff may be a bit "heavy handed" to apply universally to all keyed multi-line arrays

For example, ArrayHelper creates this array

	[
		'key' => '',
		'pointerStart' => int,
		'pointerArrow' => int,
		'pointerComma' => int,
		'pointerEnd' => int,
	]

which just makes more sense than sorting because some rule says it needs to be sorted

I feel code could get uglied up with too many
`// @phpcs:disable SlevomatCodingStandard.Arrays.Sorted.IncorrectlyOrderedArray` 

However, I think this would still be a very useful sniff
What are your thoughts on one or more of the following:

* a `minCount` option..   Set the minimum number of values the array must have to apply the sniff
* a `requireAnnotation` option... to require  some sort of `// phpcs:sorted` annotation/ comment.   
Are there any other sniffs that require explicitly enabling via annotation?

**Comment by bkdotcom** [comment]
meh..  let's start this out without any options.
Pull request is ready
