### ISSUE TITLE
Fix allow method overriding for the method getSniffClassName

### ISSUE THREAD

**Issue by Gido2935** [slevomat/coding-standard#1502]
Me and the company i work for have made an internal coding standard that uses slevomat/coding-standard. We were trying to override getSniffClassName. We found out that we weren't able to do that because it was a private method. In order for people to have the ability to override getSniffClassName i made the following changes.

For this reason i made this pull request https://github.com/slevomat/coding-standard/pull/1500

I would appreciate any feedback if there are any issues that prevents this pr from being merged

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/pull/1500
