### ISSUE TITLE
AlphabeticallySortedUses removes filedoc when "use" before and after it

### ISSUE THREAD

**Issue by kkmuffme** [slevomat/coding-standard#1504]
SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses

```php
<?php

use Foo\Bar;

/**
 * bla
 */
use Abc\Xyz;
```
 
 Will result in:
```php
<?php

use Abc\Xyz;
use Foo\Bar;
```

completely removing the comment.

Additionally it would be nice if there was an option/rule to set if the "use" statements should be before or after the filedoc

**Comment by kukulich** [comment]
I think it's not filedoc in this code, it's doccomment for `use Abc\Xyz;` so for code like this:

```php
<?php

use Abc\Xyz;
use Www;
/**
 * bla
 */
use Foo\Bar;
```

the output should be:

```php
<?php

use Abc\Xyz;
/**
 * bla
 */
use Foo\Bar;
use Www;
```

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/d5a5ebb5ec9272e463029da2b83a79089ccacde9
