### ISSUE TITLE
`@phpcsSuppress` comment should work

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#1505]
**Describe the bug**
We wanted to add a suppress together with a meaningful comment on why this is needed:

**Code sample**
```php
    /**
     * Return an instance with the specified uri
     *
     * @param \Psr\Http\Message\UriInterface $uri The new request uri
     * @param bool $preserveHost Whether the host should be retained.
     * @return static
     * @phpcsSuppress SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingNativeTypeHint For $preserveHost type.
     */
    public function withUri(UriInterface $uri, $preserveHost = false): static
```
But it still outputs

> `Error: Method \Cake\Http\ServerRequest::withUri() does not have native type hint for its parameter $preserveHost but it should be possible to add it based on @param annotation "bool".`

Expected would be that only the first part is seen as the type, and as always there is room for optional free text comment:
```php
@phpcsSuppress X.Y.Z
@phpcsSuppress X.Y.Z Some optional text.
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/252d2f245b4fd1219d4d19ac9595099929536a0c
