### ISSUE TITLE
Sniff Request:   No whitespace (or BOM)  before opening tag

### ISSUE THREAD

**Issue by bkdotcom** [slevomat/coding-standard#1508]
This can often sneak through...  and cause headers to be sent early / whtespace output

perhaps could be more strict and check for ANY content before opening tag

**Comment by kukulich** [comment]
See https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/Files/ByteOrderMarkSniff.php
