### ISSUE TITLE
Enforce "string" in lowercase in type declarations

### ISSUE THREAD

**Issue by linawolf** [slevomat/coding-standard#1516]
It would be really cool if slevomat could catch when "String" is written instead of "string" in type declarations. And maybe make a defined case for other types like "array" and "float" as well.

**Comment by kukulich** [comment]
There's `Generic.PHP.LowerCaseType` sniff in PHPCS itself.

**Comment by linawolf** [comment]
@kukulich So we investigated once more, it seems like it is not PHP types we have the problem with but doc-block comments. For example:

```
    /** @var String[] */
    private array $myStrings = [];
```
