### ISSUE TITLE
Laravel coding standards

### ISSUE THREAD

**Issue by cavo789** [slevomat/coding-standard#1518]
Hello

I was searching for a tool to scan my Laravel projects and check if I was following or not standard / best practices like using the correct naming convention for my classes.

I thought Larastan was, perhaps, a good candidate but probably not. I've posted there a question : https://github.com/nunomaduro/larastan/issues/1541

The idea is to verify if, f.i., in the ´app/Models´ folder I've correctly named my classes.  The correct use is singular and not plural (so `Student` and not `Students`).  I've explained in detail in the issue at Larastan.

For Laravel, naming conventions are https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions.

Someone (@szepeviktor) has suggested your tool and I've try it but I'm afraid that it didn't desserve that purpose (check against Laravel coding standard).  Am I wrong ?  I've created a ruleset file with all your rules and none has detected the violation.

Can you give me any advices? Is there any, specialized, rules for Laravel I can use?

Thanks a billion!

**Comment by szepeviktor** [comment]
Of course Slevomat has no rule for plural/singular Laravel models names.
But they may develop one in 2 minutes ...

Actually Laravel has tools for formatting (StlyeCI, Pint), not for naming etc. (thus static analysis)

**Comment by cavo789** [comment]
Hi all

For info, discovered yesterday : https://github.com/smortexa/laravel-arkitect

That tool is checking for naming convention .
