### ISSUE TITLE
Update markdown

### ISSUE THREAD

**Issue by skyferix** [slevomat/coding-standard#1523]
After running phpcs got this message when copied rule from markdown:

"SlevomatCodingStandard.Classes.RequireSelfReference" does not exist

**Comment by aleswita** [comment]
@skyferix upgrade `squizlabs/php_codesniffer` from version `3.7.1` to `3.7.2` discarted this file: `vendor/squizlabs/php_codesniffer/CodeSniffer.conf` containing followed settings (no idea why)
```php
<?php
 $phpCodeSnifferConfig = array (
  'installed_paths' => '../../../,../../contributte,../../slevomat/coding-standard',
);
```
so, revert this change, or add this
```xml
<config name="installed_paths" value="../../slevomat/coding-standard"/>
```
to your `ruleset.xml`

**Comment by kukulich** [comment]
`RequireSelfReference` is not part of any release now so please check if you use `dev-master` version.
