### ISSUE TITLE
Provide a security policy for this library

### ISSUE THREAD

**Issue by TravisCarden** [slevomat/coding-standard#1525]
Hi! I'm currently using the Slevomat Coding Standard on a library created specifically for inclusion in Drupal core (https://github.com/php-tuf/composer-stager), where we have [a policy of evaluating the security policies of packages](https://www.drupal.org/about/core/policies/core-dependency-policies/dependency-info#criteria) before adding them as dependencies. I don't see any such policy here (e.g., at https://github.com/slevomat/coding-standard/security). Do you have one? If so, would you be kind enough to publish it? If not, would you consider creating one? Thank you!

**Comment by kukulich** [comment]
Added in https://github.com/slevomat/coding-standard/commit/7eaa45d373f615f748acfb5616503c40c927e3c7

**Comment by TravisCarden** [comment]
Thank you!
