### ISSUE TITLE
RequireSelfReference only for Static references

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#1544]
Hey,

Say we have this:

```
class Animal {
	private int $id;
	private Animal $parent;

	public function __construct(int $id) {
		$this->id = $id;
	}

	public function setParent(int $id) : void {
		$this->parent = new Animal($id);
	}
}
```

If we have `RequireSelfReference` enabled, it's requiring me to change these two lines:

`private Animal $parent;` => `private self $parent;`
`$this->parent = new Animal($id);` => `$this->parent = new self($id);`

However, is it possible to make `RequireSelfReference` only require `self` when we're referring at some static property?

Example, for this cases only:

```
class Settings {
	public static int $cache_id;

	public function setCacheId(int $cache_id) {
		Settings::$cache_id = $cache_id;
	}
}
```

Meaning:

`Settings::$cache_id = $cache_id;` => `self::$cache_id = $cache_id;`

Thank you!

**Comment by kukulich** [comment]
I think it's better when the reference is always same, so always `self` is required.
