### ISSUE TITLE
AlphabeticallySortedUses drops secondary parts of use statements

### ISSUE THREAD

**Issue by jonathan1055** [slevomat/coding-standard#1547]
The **SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses** sorts `use` statement order. It works fine if each statement is a single separate statement. However I have found a problem when the use statements are defined with multiple parts. PHP allows for multiple use definitions within one statement, and they can also be split over more than one line, such as
```
use B, BpartTwo;
use D, DpartTwo as Dalias, DpartThree;
use C;
use A as AliasA,
    ApartTwoOnNewLine;
```
When the fixer is run on this file, only the first class within each `use` statement is output, and the secondary (and further) parts are dropped and lost from the output. The result using the above example is:
```
use A as AliasA;
use B;
use C;
use D;
```
The secondary parts are all lost completely, and this is a bug.

**Comment by jonathan1055** [comment]
This problem is due to collecting up and storing the use statement definition pieces via `getFileUseStatements()` then rebuilding the statement at the point of fixing/replacement. Multi-part use statements are not recoreded fully, only the first part of any statement is stored, so when it comes to replacement all subsequent parts are not included.

It is out of scope of this sniff to split multi-part use statements into separate single statements. So the proper way to fix this is to sort the statements by the class of the first part, but then replace statements in their entirety directly as they appear in the source file. The result of fixing the above file should be
```
use A as AliasA,
    ApartTwoOnNewLine;
use B, BpartTwo;
use C;
use D, DpartTwo as Dalias, DpartThree;
```

**Comment by kukulich** [comment]
Yes, we don’t support multiple “use” statements on one line.

**Comment by jonathan1055** [comment]
_"Yes, we don’t support multiple “use” statements on one line."_
OK "not supporting" is one thing, but causing parts of source code lines to be deleted, is an actual bug. So are you saying that any project which has allows multiple use statements cannot use this sniff? There should be a bigger warning about that.

I have just forked the project and was starting to look at a solution. But if you are saying you will not consider fixing it, then I wont go any further. 

If Slevomat does not "support" multiple use statements, then it would be bettter in the fixer, once a multiple use is detected (which is very easy to do) then the fixer should halt and do nothing, and give a message, rather than delete bits of source lines quietly which then create errors.

**Comment by klausi** [comment]
Fully agreed with @jonathan1055 !

@kukulich are you interested in a fix here for Slevomat? Otherwise we probably have to fork the sniff into Drupal Coder and fix it there.

**Comment by kukulich** [comment]
The best way is to use `PSR2.Namespaces.UseDeclaration` that prohibits more multiple declaration in one `use` statement.

> If Slevomat does not "support" multiple use statements, then it would be bettter in the fixer, once a multiple use is detected (which is very easy to do) then the fixer should halt and do nothing, and give a message, rather than delete bits of source lines quietly which then create errors.

Yes, I'm ok to merge PR that will use this solution - it should not report fixable error but just error when multiple use is detected.

**Comment by jonathan1055** [comment]
Thanks @kukulich I will work on how to stop the fixer if a multiple use is detected. 

Interetsingly, the project I am working _does_ also enforce `PSR2.Namespaces.UseDeclaration` but the problem I found was that the Slevomat sniff (and hence fixer) was being run _before_ it. So the secondary parts were getting lost before the fixer in `PSR2.Namespaces.UseDeclaration.MultipleDeclarations` could get a chance to split them into single statements.

**Comment by jonathan1055** [comment]
I have foked the repo and have a first draft of a solution. Can you re-open this issue please? Then I will make a PR and see what happens. I am unfamiliar with the slevomat coding style requirements, so there will be plenty of things that need changing I expect. Also you probably want test coverage for the change? I've not run any phpunit locally on this yet.

**Comment by jonathan1055** [comment]
@kukulich Can you re-open this issue please, to make it easier for me (and others) to follow the fix. Thanks

**Comment by jonathan1055** [comment]
PR #1551 is ready for final review. Includes test coverage as modifications as requested.
