### ISSUE TITLE
SlevomatCodingStandard.Exceptions.DeadCatch hangs for weird catch definition

### ISSUE THREAD

**Issue by VasekPurchart** [slevomat/coding-standard#155]
I didn't know this was possible to write, but it actually works - omitting the whitespace between type definition and parameter name:

* https://3v4l.org/upRAH
* https://3v4l.org/5bITD

Minimal reproducible code:

```php
<?php

try {

} catch (\Exception$e) {

}
```

**Comment by Majkl578** [comment]
Same applies for parameters: https://3v4l.org/IFiun

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/2b197d0e36e943d422aeeea07cf43d3d555bf030

**Comment by kukulich** [comment]
@Majkl578 I've just added some more tests, even for properties https://github.com/slevomat/coding-standard/commit/033caca2399292d5d00a7c25c0326f8f1b5f878a.
