### ISSUE TITLE
Check for valid PHPDoc tags in a case sensitive way

### ISSUE THREAD

**Issue by phansys** [slevomat/coding-standard#1556]
Can we have an option or a new rule to check for consistency in PHPDoc tags regarding its casing?

See doctrine/dbal#6015.

**Comment by kukulich** [comment]
As I understand https://github.com/doctrine/dbal/pull/6015 right it's not about an option. There's a demand to have a sniff that will require all phpdoc tags to be lowercase.

**Comment by phansys** [comment]
Yes. As I don't know how the rules are configured, I mentioned an option in case there is something like that available to force the case sensitivity while the parsing process.

**Comment by greg0ire** [comment]
By the way @phansys , I didn't ask you, what made you pick `inheritdoc` over `inheritDoc`?

**Comment by phansys** [comment]
>By the way @phansys , I didn't ask you, what made you pick inheritdoc over inheritDoc?

I noticed the difference while copying and pasting between different classes. I'm not sure if this is an inconsistency or if it is intentional, because even in the PHPDoc documentation, the tag is written in different ways:
* `inheritdoc`: https://docs.phpdoc.org/guide/references/phpdoc/inline-tags/inheritdoc.html
* `inheritDoc`:https://docs.phpdoc.org/guide/guides/inheritance.html#the-inheritdoc-tag

**Comment by phansys** [comment]
Well... we can find more occurrences :laughing: https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html

**Comment by greg0ire** [comment]
Oh but that's from Smarty, didn't notice that until I stumbled upon this thread that you probably stumbled upon yourself before: https://github.com/phpDocumentor/phpDocumentor/issues/84 (which mentions Doctrine, lol)

I think the official tag is whatever phpdocumentor itself uses. And internally, they seem to be using `inheritDoc`: https://github.com/search?q=repo%3AphpDocumentor%2FphpDocumentor%20inheritdoc&type=code

I really think Doctrine should be using `inheritDoc`. Maybe the sniff should propose both with an option, and default to `inheritDoc`?

**Comment by phansys** [comment]
>I really think Doctrine should be using inheritDoc. Maybe the sniff should propose both with an option, and default to inheritDoc?

Yeah, that's exactly what I am proposing:

>Can we have an option or a new rule to check for consistency in PHPDoc tags regarding its casing?

**Comment by greg0ire** [comment]
I know, but I'm not as sure as you are that the option is needed. Maybe `inheritdoc` is really incorrect and shouldn't be an option. I'm on the fence. WDYT @kukulich ?

**Comment by phansys** [comment]
>I know, but I'm not as sure as you are that the option is needed. Maybe inheritdoc is really incorrect and shouldn't be an option. I'm on the fence. WDYT @kukulich ?

Oh, sorry for that. I'm also fine with one or the other. My goal is to provide consistency for the codebase regardless the chosen variant.

**Comment by greg0ire** [comment]
No worries, I should have expressed myself more clearly :slightly_smiling_face:

**Comment by kukulich** [comment]
PHPDoc is inherited by default so the best way is https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentinguselessinheritdoccomment- :)

The problem is that PHPCS cannot read comments from parents so the `@inheritDoc` can be used to "skip" some checks.

However it's easy to write sniff that will check annotations casing - I'm just not sure how it should be configured or what should do with `@ORM\*` etc.

**Comment by greg0ire** [comment]
> PHPDoc is inherited by default so the best way is https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentinguselessinheritdoccomment- :)

Are you sure? When removing `inheritDoc`, I get this:

```
FILE: src/Connections/PrimaryReadReplicaConnection.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 249 | ERROR | Method \Doctrine\DBAL\Connections\PrimaryReadReplicaConnection::executeStatement() does not have @param annotation for its traversable parameter $params.
     |       | (SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingTraversableTypeHintSpecification)
 249 | ERROR | Method \Doctrine\DBAL\Connections\PrimaryReadReplicaConnection::executeStatement() does not have @param annotation for its traversable parameter $types.
     |       | (SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingTraversableTypeHintSpecification)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

> The problem is that PHPCS cannot read comments from parents so the @inheritDoc can be used to "skip" some checks.

Is the issue above what you are hinting at here?

> However it's easy to write sniff that will check annotations casing - I'm just not sure how it should be configured or what should do with @ORM\* etc.

Maybe it should be configured with a list of words that need to have a very specific case? The default value could be `['inheritDoc', 'dataProvider'…]`. I don't think anything should be done w.r.t `@ORM\*` though. `ORM` is just a random alias.

**Comment by kukulich** [comment]
> Is the issue above what you are hinting at here?

Yes, Slevomat sniff use `@inheritDoc` to skip this checks because of the PHPCS limitation.

> Maybe it should be configured with a list of words that need to have a very specific case? The default value could be ['inheritDoc', 'dataProvider'…].

I was thinking about the same. And anything that is not configured will be ignored.

**Comment by kukulich** [comment]
Please try https://github.com/slevomat/coding-standard/pull/1557
