### ISSUE TITLE
SlevomatCodingStandard.Functions.StaticClosure may break code using closure binding

### ISSUE THREAD

**Issue by mabar** [slevomat/coding-standard#1562]
It's probably not worth to attempt making a fix, because it's impossible to find all `bindTo()`, `bind()` and `call()` calls, but I think it should be at least documented, that this sniff can potentially break code

See https://3v4l.org/f3LNC

Also other sniffs should warn about potential code breaking behavior as it may not be always obvious. I am aware of these:

- `SlevomatCodingStandard.TypeHints.DeclareStrictTypes.DeclareStrictTypesMissing` - when code is not ready for strict types
- `SlevomatCodingStandard.TypeHints.PropertyTypeHint.MissingNativeTypeHint` - when phpdoc is incorrect or overriding untyped property from third party
- `SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingNativeTypeHint` - when phpdoc is incorrect or overriding method with untyped parameter from third party
- `SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingNativeTypeHint` - when phpdoc is incorrect or overriding method with untyped return from third party
- `SlevomatCodingStandard.PHP.RequireExplicitAssertion` - when phpdoc is incorrect
- `SlevomatCodingStandard.Functions.StrictCall` - when code relies on non-strict behavior
- `SlevomatCodingStandard.Operators.DisallowEqualOperators` - when code relies on non-strict operators

**Comment by kukulich** [comment]
Thank you. However I think all sniffs could break code - the fixer is not perfect. And people don't read documentation so I think it's useless to add such warning.
