### ISSUE TITLE
ReferenceUsedNamesOnly breaks aliased namespace imports

### ISSUE THREAD

**Issue by derrabus** [slevomat/coding-standard#1573]
I believe the fix for #1570 broke aliased namespace imports. I'm using the coding standard on a project that uses Mockery in unit tests and imports it as `use Mockery as m;` like in the following example:

```php
<?php

use Mockery as m;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;

class MyTestCase extends TestCase
{
    private LoggerInterface&m\MockInterface $loggerMock;

    protected function setUp(): void
    {
        $this->loggerMock = m::mock(LoggerInterface::class);
    }
}
```

After the upgrade to Slevomat Coding Standard 8.12.0, this is "fixed" to…

```php
<?php

use m\MockInterface;
use Mockery as m;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;

class MyTestCase extends TestCase
{
    private LoggerInterface&MockInterface $loggerMock;

    protected function setUp(): void
    {
        $this->loggerMock = m::mock(LoggerInterface::class);
    }
}
```

Note the new import `use m\MockInterface;`. This of course won't work because `m` is an alias and `use` statement must be absolute, they must not reference each other.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/f69e2524e8770efb9b3e5ac4a0ebc0d54eb446d7

**Comment by derrabus** [comment]
Thank you very much. I can confirm that the bug is solved for me!
