### ISSUE TITLE
ModernClassNameReference fixes get_class($this) with php 7.1

### ISSUE THREAD

**Issue by greg0ire** [slevomat/coding-standard#1580]
`doctrine/orm` supports php 7.1. We have configured phpcs to specify it, and have some occurrences of `get_class($var)` in our codebase. Yet when I try to use `get_class($this)` in an abstract class, it gets fixed to `static::class`.

Should maybe the check in the second condition be copied in the first?

https://github.com/slevomat/coding-standard/blob/3c40fc8bfaa43e2e64bb3b61b86c7e1bd176a5e0/SlevomatCodingStandard/Sniffs/Classes/ModernClassNameReferenceSniff.php#L132-L134

Here is the PR I'm working on: https://github.com/doctrine/orm/pull/10754

**Comment by kukulich** [comment]
I've probably missed something... https://3v4l.org/I0GBH#v7.1.0

**Comment by greg0ire** [comment]
No, it's me who missed something :facepalm: when trying on 3v4l, I added a `$`, like this `static::$class`, and concluded this wasn't supported (I was already convinced it wasn't, and the confirmation bias did the rest). Sorry for wasting your time. :bow:

**Comment by kukulich** [comment]
@greg0ire No problem :) If I can “waste” your time a little in return… Can you please try dev-master of Slevomat CS in Doctrine? Because of this https://twitter.com/ondrejmirtes/status/1664500014406615041?s=46&t=25L5QqGu82FsBqPk-Zqdwg

**Comment by greg0ire** [comment]
Not sure what it's going to do exactly but I will give it a try 👍

**Comment by greg0ire** [comment]
Just tried it, and there seem to be a lots of false positives: it's now saying imports are unused.

Here is an example:

```
FILE: tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1514Test.php
----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------------------------------------------------------------------------------
 10 | ERROR | [x] Type Doctrine\ORM\Mapping\Entity is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
 11 | ERROR | [x] Type Doctrine\ORM\Mapping\GeneratedValue is not used in this file.
    |       |     (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
 12 | ERROR | [x] Type Doctrine\ORM\Mapping\Id is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
----------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------------------------------------
```

Here the file: https://github.com/doctrine/orm/blob/2.15.x/tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1514Test.php

**Comment by kukulich** [comment]
@greg0ire Thanks, will check

**Comment by kukulich** [comment]
@greg0ire Thank you very much, it's fixed now.

**Comment by greg0ire** [comment]
OK< now there's another issue: it's removing comments such as this one: https://github.com/doctrine/orm/blob/76b8a215c237cb3d3ff540e005bb0c1276d066f6/tests/Doctrine/Tests/ORM/Functional/Ticket/GH6362Test.php#L40-L44
