### ISSUE TITLE
Native `callable` type hint is wrongfully enforced in constructor property promotion

### ISSUE THREAD

**Issue by herndlm** [slevomat/coding-standard#1583]
`SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingNativeTypeHint` seems to be having problems with the `callable` type in constructor property promotion handling it just like any other method. But there are types that cannot be used there, see https://3v4l.org/FHkVn 

According to https://wiki.php.net/rfc/typed_properties_v2 all types except `void` and `callable` are supported.

UPDATE: Is this something `TypeHintHelper::isValidTypeHint()` or another helper method there could check maybe? But first that sniff needs to be aware if it is dealing with constructor property promotion or not I guess.. I can look into contributing this maybe, feel free to give me any hints / guidelines :)

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/4166003e9ca097a67951ab434f321c90eb621c3e
