### ISSUE TITLE
SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingAnyTypeHint does not like linebreaks since 8.13.0

### ISSUE THREAD

**Issue by greg0ire** [slevomat/coding-standard#1586]
```php
   /**
     * @return AST\BetweenExpression|
     *         AST\CollectionMemberExpression|
     *         AST\ComparisonExpression|
     *         AST\EmptyCollectionComparisonExpression|
     *         AST\ExistsExpression|
     *         AST\InExpression|
     *         AST\InstanceOfExpression|
     *         AST\LikeExpression|
     *         AST\NullComparisonExpression
     */
```

causes the rule in the title to kick in. The whole code can be seen at https://github.com/doctrine/orm/blob/4c3bd208018c26498e5f682aaad45fa00ea307d5/lib/Doctrine/ORM/Query/Parser.php#L2569-L2577

**Comment by kukulich** [comment]
Thanks, @ondrejmirtes will try to fix it in https://github.com/phpstan/phpdoc-parser

**Comment by ondrejmirtes** [comment]
Psalm maintainers recommend to parenthesize the multiline union type: https://github.com/vimeo/psalm/discussions/9969#discussioncomment-6298087 Which would make it work with phpstan/phpdoc-parser and Slevomat CS too.
