### ISSUE TITLE
phpcs internal error with too much stars

### ISSUE THREAD

**Issue by williamdes** [slevomat/coding-standard#1587]
`Upgrading slevomat/coding-standard (8.12.1 => 8.13.0)`

```
FILE: routes/xxxx/xxxx.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Unexpected token
   |       | "/****", expected '/**' at offset 0 on line 1
   |       | (Internal.Exception)
----------------------------------------------------------------------
```

The offending code: `/**** template for mail (easy debug) *****/`

The corrected code: `/* *** template for mail (easy debug) **** */` to fix it

**Comment by williamdes** [comment]
I also suspect this to be some infinite loop as I had to bump to 1G the memory limit to see this internal error

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/ea34bea4e279c0aebcef26e9302dbc78c1e85931
