### ISSUE TITLE
SlevomatCodingStandard.Commenting.DocCommentSpacing: part of phpdoc is removed entirely

### ISSUE THREAD

**Issue by LordSimal** [slevomat/coding-standard#1588]
See https://github.com/cakephp/cakephp/pull/17169/commits/8e67380d5a086d1772676854cbd1f225ab5233cd#diff-e1d901983944d842aee7bd6aeede96e17e30877f15abb3817187e6baf4fab8c7

Used version: 8.13.0

Pretty sure this is related to https://github.com/slevomat/coding-standard/issues/1579

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/a13c15e20f2d307a1ca8dec5313ec462a4466470

**Comment by LordSimal** [comment]
Thanks for taking care of this so quickly 🙇🏻
