### ISSUE TITLE
UselessFunctionDocComment removes descriptive annotations

### ISSUE THREAD

**Issue by danepowell** [slevomat/coding-standard#1589]
Since 8.13.0, the UselessFunctionDocComment has started to throw on / remove `@return` annotations with descriptions, such as here: https://github.com/acquia/cli/pull/1547/files#diff-2b7771d88c66755dc00ee8758066c2b7ea6bc1bdb7f00c8c6dfbcbc96ac6cd55L598

If a return annotation has a text description, I don't think it should be considered useless.

I saw a couple of similar issues that were fixed in 8.13.1, but upgrading to 8.13.1 doesn't fix this.

**Comment by ondrejmirtes** [comment]
A text on the next line cannot really be considered a description of the tag on the previous line.

phpdoc-parser has some logic for this - if there's a description starting on the same line as the tag, it considers the text on the current line and the next line as description of the tag.

But if the text after the tag starts on the next line, it's a standalone text node.

What slevomat/coding-standard would have to do is to consider any text nodes between tags as description of the previous tag. But I'm not sure how useful and common it is.

**Comment by ondrejmirtes** [comment]
An example. Right now you're formatting your code like this:

```php

  /**
   * @param string $sshUrl
   *   The SSH URL to the server.
   * @return string
   *   The sitegroup. E.g., eemgrasmick.
   */
```

To get rid of the problem you'd have to start the description on the same line:

```php

  /**
   * @param string $sshUrl The SSH 
   * URL to the server.
   * @return string The
   * sitegroup. E.g., eemgrasmick.
   */
```

**Comment by danepowell** [comment]
Thanks, I think I understand the confusion now. Our projects follow the [Drupal commenting standards](https://www.drupal.org/docs/develop/standards/php/api-documentation-and-comment-standards#return), which dictate descriptions should start on a newline. I never even considered that descriptions could/should start on the same line as the annotation, but it turns out that is what the [phpdoc spec itself recommends](https://docs.phpdoc.org/guide/guides/docblocks.html). Seems like Drupal and phpDoc need to work this out amongst themselves.

I'm happy converting my annotations to start on the same line, since I think the phpDoc spec should take precedence. But I expect other Drupal users will run into this issue as well.

**Comment by ondrejmirtes** [comment]
I'll make this a setting in phpdoc-parser which Slevomat CS will be able to take advantage of.

**Comment by acbramley** [comment]
Yeah this is going to be very disruptive for the Drupal community.

**Comment by mstrelan** [comment]
If it helps, according to the Drupal coding standards, the description part must be indented with two spaces on the line(s) immediately following the annotation.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/pull/1599
