### ISSUE TITLE
Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\AnnotationHelper::getStartPointer(): Return value must be of type int, null returned 

### ISSUE THREAD

**Issue by Citizen4our** [slevomat/coding-standard#1595]
Hello
module vesrion: 8.13.1

If you have code like this in any method (comment block):

/** @see \Magento\CatalogGraphQl\DataProvider\Product\SearchCriteriaBuilder::build line 127
         * and @see \Magento\Framework\Search\Search::search line 72
         */

You can see error:
_Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\AnnotationHelper::getStartPointer(): Return value must be of type int, null returned_ 

so, if remove word 'and' before '@see'  (no matter which one, @params, etc.) - error not happened.
Also, if add cast to int in line `vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php:326` - error not happened. But I'm not sure if it right way.

**Comment by kukulich** [comment]
I think it's right to remove the `and`.

**Comment by Citizen4our** [comment]
Okay, remove is necessary. But it shouldn't crash with a fatal error as now.
