### ISSUE TITLE
Error: Undefined constant "T_OPEN_PARENTHESIS"

### ISSUE THREAD

**Issue by mikebronner** [slevomat/coding-standard#1596]
Hi guys, not sure where the error for this is, not sure if its on my end with how I am implementing things.

I get this error when trying to instantiate the CognitiveSniff class:

```php
class CognitiveTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp();

        self::$sniff = new CognitiveSniff;
    }

    // ...
}
```

```shell
Error: Undefined constant "T_OPEN_PARENTHESIS"

/var/www/html/tests/Unit/Complexity/CognitiveTest.php:19
```
where line 19 refers to `self::$sniff = new CognitiveSniff;`

How should I be instantiating the sniff class to avoid this error? Thanks for your help.

PS: I'm writing tests for my custom ruleset to meet our coding standards.

**Comment by ondrejmirtes** [comment]
This isn't how you test PHP_CodeSniffer sniffs.

See the test suite here in this repo how it's done.

This is important: https://github.com/slevomat/coding-standard/blob/723c330f7b66fb6672c3bcf01cdb5d9cd8d9112a/SlevomatCodingStandard/Sniffs/TestCase.php#L32-L72

And this is how you typically test a file: https://github.com/slevomat/coding-standard/blob/723c330f7b66fb6672c3bcf01cdb5d9cd8d9112a/tests/Sniffs/Arrays/ArrayAccessSniffTest.php#L10-L14

**Comment by mikebronner** [comment]
@ondrejmirtes yea, that's what I'm doing, but i'm writing my own testcase with some additional features that extends the slevomat testcase. I am asking more for understanding how to new up this sniff class, and wasn't sure if there is some secret sauce i need to add. Thanks :)
