### ISSUE TITLE
PHPStorm inspections does not work with TypeNameMatchesFileNameSniff

### ISSUE THREAD

**Issue by mhujer** [slevomat/coding-standard#16]
When you use *path checking* rules (e.g. `TypeNameMatchesFileNameSniff`), PHPStorm CodeSniffer inspection will report *false-positives* because temporary file with incorrect path is used for validation.

**See the PHPStorm issue**: https://youtrack.jetbrains.com/issue/WI-30583

(I know this is not an issue of the sniffs or the coding standard itself, but I think it may be useful to have it noted here. Since the PHPStorm is [widely used](http://www.sitepoint.com/best-php-ide-2014-survey-results/) IDE I am probably not the last one to discover this problem.)

**Comment by ondrejmirtes** [comment]
Thank you. I noticed this too last week when my colleague showed it to me. I also think it's an issue of the IDE and I'm not sure how to fix it from our point of view.

You could probably fix it by creating a special ruleset.xml and pointing PhpStorm to it. Your CI environment would still run this sniff, but IDE would use a different ruleset.xml that included the project's ruleset.xml and additionally ignored this sniff.

**Comment by mhujer** [comment]
@ondrejmirtes creating an extra `ruleset.xml` which excludes the problematic sniff is a good workaround, thanks fo the idea!

**Comment by janlanger** [comment]
Looks like this was fixed by PhpStorm team (or will be in next version)

**Comment by mhujer** [comment]
It works fine in PhpStorm 2016.1.1 EAP! https://twitter.com/phpstorm/status/717665814372081664

**Comment by ondrejmirtes** [comment]
Cool :+1:
