### ISSUE TITLE
UselessConstantTypeHintTest throws error.

### ISSUE THREAD

**Issue by mikebronner** [slevomat/coding-standard#1605]
given the following code:
```php
<?php

declare(strict_types = 1);

namespace ValmarCodingStandard\Tests\Fixtures\TypeHints;

class UselessConstantTypeHintWithErrors
{
    /**
     * @var string
     */
    const TEST = 'test';

	/**
	 * AA constant
     *
	 * @var string
	 */
	const AA = 'aa';
}
```

PHPCS throws the following error:
```
phpcs: Uncaught TypeError: SlevomatCodingStandard\Helpers\SniffSettingsHelper::normalizeArray(): Argument #1 ($settings) must be of type array, string given, called in /var/www/html/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/ForbiddenCommentsSniff.php on line 50 and defined in /var/www/html/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffSettingsHelper.php:40
```

This code, however, seems to run fine:
```php
<?php

declare(strict_types = 1);

namespace ValmarCodingStandard\Tests\Fixtures\TypeHints;

class UselessConstantTypeHintWithErrors
{
    /**
     * @var string
     */
    const TEST = 'test';

	/**
     *
	 * @var string
	 */
	const AA = 'aa';
}
```

not sure why this is, because that was taken directly from your test file: https://github.com/slevomat/coding-standard/blob/master/tests/Sniffs/TypeHints/data/uselessConstantTypeHintErrors.php

Running on PHP 8.2, Ubuntu 22.04

**Comment by kukulich** [comment]
I’m sorry I don’t understand what you are doing.

**Comment by mikebronner** [comment]
I'm going over the different sniffs, creating a ruleset, and testing that the sniffs work as configured for my ruleset.
If you try to sniff you first codeblock it breaks PHPCS, if you have 
```
	<rule ref="SlevomatCodingStandard.TypeHints.UselessConstantTypeHint" />
```
in your ruleset.xml file

**Comment by kukulich** [comment]
The TypeError mentioned above is from different sniff that is configured wrong - probably.

**Comment by mikebronner** [comment]
ok, thanks, i will research that some more

**Comment by mikebronner** [comment]
ok, thanks, i will research that some more
