### ISSUE TITLE
False Multiline array must have trailing comma

### ISSUE THREAD

**Issue by vedmant** [slevomat/coding-standard#161]
With next piece of code it shows false error "Multiline array must have trailing comma"

        return [
            //
        ];

It's just empty array with empty comment, a lot of this stubs are generated in Laravel framework and it's not violating standard.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/c9a08f49aa06b01638a024d91385acc6261d6aa3
