### ISSUE TITLE
ReferenceViaFullyQualifiedName changes FQN to reserved keyword

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#1613]
`SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly.ReferenceViaFullyQualifiedName` tries to change `\Psl\Type\null()` to `null()` which is not valid php code because of abusing reserved keyword.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/c4526463cfa0d6dfba32e944826a839f90b331fa

**Comment by simPod** [comment]
@kukulich I'm sorry but I may have reported the false positive.

I tried to reproduce the case and found out php parses it with no issues https://3v4l.org/Eas0p

The only issue seems to be that `SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` thinks the import `use function Psl\Type\null;` is unused when we use `null()` in the code.
