### ISSUE TITLE
`SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` marks `Psl\Type\null` as unused

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#1631]
`SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` thinks the import `use function Psl\Type\null;` is unused when we use `null()` in the code.

(https://github.com/slevomat/coding-standard/issues/1613#issuecomment-1733307645)

**Comment by kukulich** [comment]
Fixed thanks to PHPCS upgrade: https://github.com/slevomat/coding-standard/commit/923e12170e92a1d3a4994a321163e0c20aa1a7d3
