### ISSUE TITLE
New Sniff Idea: Remove useless cast in return

### ISSUE THREAD

**Issue by finn-matti** [slevomat/coding-standard#1634]
Example:

```
public function returnBool(): bool
{
   return (bool)1;
}
```

This and similar explicit casts could be removed from code as the return type hint already casts appropriately.

**Comment by BafS** [comment]
This only work if you don't use strict typing. It's not a great practice.

```
<?php declare(strict_types=1);

function returnBool(): bool
{
   return 1;
}

returnBool();
```

Here you will have a `TypeError`.

See https://3v4l.org/4tNdF

**Comment by finn-matti** [comment]
Uff. Yes! You're absolutely right! Using strict types should be preferred. Thanks for making me aware of the problems with this approach.
