### ISSUE TITLE
differencies in configuration properties

### ISSUE THREAD

**Issue by BigCharlie** [slevomat/coding-standard#164]
When playing with SlevomatCodingStandard.Files.TypeNameMatchesFileName sniff, I found that there is a difference in the way different properties are treated. Given configuration

```xml
<rule ref="SlevomatCodingStandard.Files.TypeNameMatchesFileName">
    <properties>
        <property name="rootNamespaces" type="array" value="
            src=>X,
            tests/src=>X\Tests,
        " />
        <property name="skipDirs" type="array" value="Exceptions," />
        <property name="extensions" type="array" value="php,phpt," />
    </properties>
</rule>
```

results in two rootNamespaces, one skipDirs, but three extensions (last one empty).

rootNamespaces, skipDirs are trimmed too, but there's no way how to use multi-line configuration (as for rootNamespaces) with extensions.

I'm not sure if that is a bug or expected behavior. I just found the multi-line array configuration more readable (git diff mainly).

**Comment by kukulich** [comment]
Thank you for your report.

Should be fixed in https://github.com/slevomat/coding-standard/commit/ee66903be747490f14d0b88f75ac46667aef082c
