### ISSUE TITLE
`squizlabs/PHP_CodeSniffer` is abandoned

### ISSUE THREAD

**Issue by LordSimal** [slevomat/coding-standard#1640]
See https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

Will this package switch to https://github.com/PHPCSStandards/PHP_CodeSniffer as it is a direct fork?

**Comment by kukulich** [comment]
Yes.

**Comment by jrfnl** [comment]
@bkdotcom As per the announcement:

> Note: I would recommend waiting to make the switch until the 3.8.0 release has been tagged. Watch releases on the [new repo](https://github.com/PHPCSStandards/PHP_CodeSniffer) to automatically get notified of this. The changelog will contain the relevant information for making the switch.

Until a release has been tagged from the new repo with the `replace` directive in the `composer.json`, things won't work as expected as the files in the `vendor/bin` won't be replaced.
