### ISSUE TITLE
Error with php_codesniffer 3.8.0 on rule DisallowYodaComparison

### ISSUE THREAD

**Issue by alepieser** [slevomat/coding-standard#1654]
Hello,

With the last version of php_codesniffer (3.8.0) we noticed this error:

`ERROR: Ruleset invalid. Property "alwaysVariableOnRight" does not exist on sniff SlevomatCodingStandard.ControlStructures.DisallowYodaComparison`

Thanks for your help

**Comment by kukulich** [comment]
You have mistake in your ruleset. This sniff does not have option `alwaysVariableOnRight`.
