### ISSUE TITLE
Argument requires ParamTagValueNode, TypelessParamTagValueNode given 

### ISSUE THREAD

**Issue by JayroBoy** [slevomat/coding-standard#1656]
I have recently been placed responsible over a PHP application that was configured by someone else and uses PHPCS as part of its QA process. Since the last update I have been getting the following error when running phpcs:

```
Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): 
Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode,
PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given
```

I have looked through the call stack and there seems to be only third-party(relative to the application) code present in it. Googling the error yields no recent results, similar to github search. Is it possible that this is a bug/issue or is the most likely cause faulty configuration?

**Comment by kukulich** [comment]
It looks you don't use latest version of this library.
