### ISSUE TITLE
TypeHintDeclarationSniff: support for @inheritdoc

### ISSUE THREAD

**Issue by asprega** [slevomat/coding-standard#166]
Since this sniff does not support `@inheritdoc` for looking up `@param` and `@return` annotations in superclasses, when I extend framework classes I am forced to copy/paste annotations from there to my classes, or the sniff will report errors. Good examples might be Symfony forms or Doctrine types. Is there any intention to support this annotation, or does it pose significant issues/overhead?

**Comment by kukulich** [comment]
@asprega PHPCS doesn't know anything about parent classes. Each class is checked separately. I can only ignore methods with @inheritdoc. Would you be ok with this solution?

**Comment by asprega** [comment]
Thanks for the quick reply!
Yes, that would work great for me.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/727678c634864ff609157c6e6586e5c746fd3520.

**Comment by Fuco1** [comment]
I was just about to submit this same issue.  I think simply ignoring the method is an OK solution as the parent file would eventually be checked separately and the types will be specified there.

Thanks for fixing this!
