### ISSUE TITLE
Can't document the return of a function with `@var`

### ISSUE THREAD

**Issue by devnix** [slevomat/coding-standard#1660]
Currently is not possible to document the return of a function inline without creating a temporal variable. This syntax is covered by PHPStan, Psalm, etc

```php
function test(mixed $foo): array|false
{
    /** @var int */ // Invalid inline documentation comment format "@var int", expected "@var type $variableName Optional description". (SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.InvalidFormat)
    return $foo;
}
```

Here is a practical example in the wild: [src/Driver/SQLite3/Result.php](https://github.com/doctrine/dbal/pull/6287/files#diff-e6b9d256dc38d8bd92ff6af0799b48fd9490b8710b11436e9a3415e30138ce9eR30)

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentinginlinedoccommentdeclaration-

**Comment by devnix** [comment]
![*Facepalm*](https://i.gifer.com/origin/27/271c22724f6e2360effa30297d8cc45f_w200.gif)

Thank you @kukulich
