### ISSUE TITLE
Useless parentheses in new class

### ISSUE THREAD

**Issue by farhadsakhaei** [slevomat/coding-standard#1662]
Hi,
I got this error:
Useless parentheses in "new".PHPCS(SlevomatCodingStandard.ControlStructures.NewWithoutParentheses.UselessParentheses)

**The code is:**
`self::$instance = new $class_name();`

**Comment by kukulich** [comment]
Yes, the sniff reports this :)

**Comment by farhadsakhaei** [comment]
@kukulich 
Thank you for creating this great standard,
If I remove the paranteces, I get another error:
Parentheses must be used when instantiating a new class PHPCS (PSR12.Classes.ClassInstantiation.MissingParentheses)

**Comment by kukulich** [comment]
You have to fix your PHPCS configuration. You have enabled sniffs that report incompatible errors.

**Comment by farhadsakhaei** [comment]
@kukulich 
OK, I add PSR12.Classes.ClassInstantiation.MissingParentheses
in the exclude rules,
Thank you

**Comment by farhadsakhaei** [comment]
Sorry, 
I got another error:
Usage of "new" without parentheses is disallowed.PHPCS(SlevomatCodingStandard.ControlStructures.NewWithParentheses.MissingParentheses)

Should I exception the SlevomatCodingStandard.ControlStructures.NewWithoutParentheses.UselessParentheses for this line?
Or this should be improve?
