### ISSUE TITLE
 Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by oojacoboo** [slevomat/coding-standard#173]
when enabling this ruleset, I get the following error:

`Unexpected token P in JSON at position 0`

I had this issue previously and it was related to and <arg /> tag being specified.

**Comment by kukulich** [comment]
We don't use JSON in our sniffs. However PHPCS use JSON for caching. Do you use option `--cache`? If so, can you try run PHPCS without this option?

**Comment by oojacoboo** [comment]
I was able to resolve the issue.  I actually don't fully recall what it was now.  It may have been that there was an <arg /> tag set for cache and I removed it.
