### ISSUE TITLE
declare(declare(strict_types = 1); on new line?

### ISSUE THREAD

**Issue by gsdevme** [slevomat/coding-standard#179]
Hi,

I notice the sniff for `declare(strict_types = 1);` enforces it be on the same line as `<?php` .. however the draft PSR standard has it on the new line.

Is it worth aligning the rule to the draft? or is there some way to use the PSR notation? 

https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#example

**Comment by kukulich** [comment]
You can use options of the sniff, see https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintsdeclarestricttypes-

**Comment by gsdevme** [comment]
Oh thanks, likely worth changing the default though imo.
