### ISSUE TITLE
YodaComparisonSniff breaks code or ignores if logical operator is present

### ISSUE THREAD

**Issue by vanam** [slevomat/coding-standard#180]
Hi, I am using your code sniffers through [Nette Coding Standard](https://github.com/nette/coding-standard) and `YodaComparisonSniff`:
a) breaks code if logical operators are present:
```php
    public function g($param) {
        if (A::TYPE_A === $param or A::TYPE_B === $param) {
            echo "a";
        }
    }
```
changes to:
```php
    public function g($param) {
        if ($paramA::TYPE_A === $param or A::TYPE_B) {
            echo "a";
        }
    }
```
b) Ignores Yoda expression
```php
    public function h($param) {
        if ($param === A::TYPE_A or A::TYPE_B === $param) {
            echo "a";
        }
    }
```
changes to (does not change):
```php
    public function h($param) {
        if ($param === A::TYPE_A or A::TYPE_B === $param) {
            echo "a";
        }
    }
```

Tests describing this issue can be found at [my fork](https://github.com/vanam/coding-standard/commit/c9df4f290dfd31b489279ff3fe953817de401d65) (should I make a pull request?).

Sample source codes to test on: [example.zip](https://github.com/slevomat/coding-standard/files/1246775/example.zip)

**Comment by ondrejmirtes** [comment]
It's definitely possible there's a bug, but I think you don't want to use `and` and `or` operators in your code, surprisingly, they behave differently than `&&` and `||`. See: http://php.net/manual/en/language.operators.logical.php

But of course we're gonna fix this, should be easy :)

**Comment by vanam** [comment]
Two words: Legacy Codebase :)

btw is there a fixer to change `or` to `||` and `and` to `&&`?

**Comment by ondrejmirtes** [comment]
I suspect not, exactly because it's no just safe to replace one with another, you'd have to add parentheses and the result wouldn't be so nice :)

**Comment by kukulich** [comment]
Thank you for your report. Fixed in https://github.com/slevomat/coding-standard/commit/cb6986fa61665de0a4c89708db8caa9733f7ed27
