### ISSUE TITLE
Chained private method calls marked as unused

### ISSUE THREAD

**Issue by venyii** [slevomat/coding-standard#185]
When using `SlevomatCodingStandard.Classes.UnusedPrivateElements` together with chained method calls, the sniffer complains about unused private methods:

**test2.php**
```php
<?php

class Test {
  public function __construct() {
    $this
      ->testMethod1()
      ->testMethod2()
      ->testMethod3()
    ;
  }

  private function testMethod1() {
    return $this;
  }
  private function testMethod2() {
    return $this;
  }
  private function testMethod3() {
    return $this;
  }
}
```

**ruleset.xml**
```xml
<?xml version="1.0"?>
<ruleset name="Test">
  <rule ref="vendor/slevomat/coding-standard/SlevomatCodingStandard/ruleset.xml" />
</ruleset>
```

**composer.json**
```yml
{
    "require": {
        "squizlabs/php_codesniffer": "^3.0",
        "slevomat/coding-standard": "^3.3"
    }
}
```
Using versions:
```
slevomat/coding-standard  3.3.0
squizlabs/php_codesniffer 3.0.2
```

**Command**
`./vendor/bin/phpcs --standard=ruleset.xml --sniffs=SlevomatCodingStandard.Classes.UnusedPrivateElements test2.php`

This produces currently:
```
-----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------
 15 | ERROR | Class Test contains unused private method testMethod2().
 18 | ERROR | Class Test contains unused private method testMethod3().
-----------------------------------------------------------------------
```
which I'd expect to return no issues.

WDYT?

**Comment by Majkl578** [comment]
Does it work if you add `self` return type to the private methods?
_(Although legitimate bug report, I'd suggest to avoid this approach and use separate method calls on $this instead -- it will be more readable.)

**Comment by kukulich** [comment]
Thank you for you report.

Fixed in https://github.com/slevomat/coding-standard/commit/30084f858212a6e7f77d60a3605d4621758665f2
