### ISSUE TITLE
Expected N spaces after parameter type; M found - disable this hint

### ISSUE THREAD

**Issue by progsmile** [slevomat/coding-standard#186]
Hi there, thanks you for such useful package! Have issue with this spacing after parameter type in comments, - I just need to disable this check. Here are more info with screenshots.

I've added KKKK, to find particular rule, and this is caused by `PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\FunctionCommentSniff`
![alt](https://image.prntscr.com/image/ErzzMTdmQ7aiL-F5rDbuvA.png)
![alt](https://image.prntscr.com/image/G3A34tffRjmOetBtvJOChw.png)
![image](https://user-images.githubusercontent.com/6272773/29913527-1b63013e-8e3e-11e7-8b23-2272dfd3117d.png)

Thanks.

**Comment by kukulich** [comment]
It should be ok if you exclude `Squiz.Commenting.FunctionComment.SpacingAfterParamType`.

**Comment by progsmile** [comment]
Thanks @kukulich, it works!)
