### ISSUE TITLE
Remove important annotations

### ISSUE THREAD

**Issue by snapshotpl** [slevomat/coding-standard#187]
I like `SlevomatCodingStandard.TypeHints.TypeHintDeclaration.UselessDocComment` rule, however it removes two important annotation for me: @codeCoverageIgnore and @throws
Is there any setting to keep it?

**Comment by Majkl578** [comment]
You can specify useful annotations in configuration, see README: https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintstypehintdeclaration-

**Comment by snapshotpl** [comment]
@Majkl578 :+1:
