### ISSUE TITLE
[NFR] TypeHints.TypeHintDeclarationSniff inheritdoc insensitive case checks

### ISSUE THREAD

**Issue by andrew-demb** [slevomat/coding-standard#188]
Hello.

In our project, we're using doc inheritance via `@inheritDoc` annotation, but `TypeHintDeclarationSniff::hasInheritdocAnnotation()` check only for lowercase variant of annotation.

How about change used the PHP function to locating str `strpos -> stripos`?
https://github.com/slevomat/coding-standard/blob/3.3.0/SlevomatCodingStandard/Sniffs/TypeHints/TypeHintDeclarationSniff.php#L995

**Comment by kukulich** [comment]
@andrew-demb Could you please provide a pull request with the change and with test?

**Comment by kukulich** [comment]
@andrew-demb Thank you. It will be in the next release.
