### ISSUE TITLE
FullyQualifiedGlobalConstantsSniff autofix error.

### ISSUE THREAD

**Issue by titanrat** [slevomat/coding-standard#190]
FullyQualifiedGlobalConstantsSniff doesn't work correct with some lines.
Example line:
`const TYPE_ONE = 1, TYPE_TWO = 2, TYPE_THREE = 3;`

After this sniff and it's autofix line looks like
`const TYPE_ONE = 1, \TYPE_TWO = 2, \TYPE_THREE = 3;`

This fix brokes code.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/1204c8020af9cd8e10230e052810b2722349fc75
