### ISSUE TITLE
Setup a 2.x branch

### ISSUE THREAD

**Issue by Fuco1** [slevomat/coding-standard#192]
Hey.  I would like to backport some new patches for the 2.4 release (we still depend on codesniffer 2) but as there is no branch I don't have anywhere to target the pull request.  Would you be willing to maintain a branch for the 2.x series?

**Comment by Fuco1** [comment]
Actually, seems like the thing I want already is included.  :blush: But a branch might still be useful.

**Comment by kukulich** [comment]
@Fuco1 I will prepare last bugfix release of version 2.x later this week. However it will really be last release and I don't want to maintain version 2.x anymore.

**Comment by Fuco1** [comment]
Okey, thanks and thanks also for letting us know.  I will try to migrate to CS 3 as well but it's a bit unclear as of when.

**Comment by kukulich** [comment]
@Fuco1 Could you please test branch `version2` before I release it?

**Comment by Fuco1** [comment]
Our entire codebase still passes so at least it works the same as before :) I have tested the new feature I was interested in and that also works.  I'll keep running the git version for a while and report back if I get some problems.
