### ISSUE TITLE
Feature Request for Sniffs

### ISSUE THREAD

**Issue by temp** [slevomat/coding-standard#194]
Any chance to get a sniff that enforces importing everything in code?

We have the rule that everything you use in your code (not necessarily in DocBlocks) has to be imported. I tried developing a sniff for this, but it's hard when you never dealt with this before ;-)

Another useful sniff would be a check for usage of unscoped standard and SPL exceptions. 
We follow this guideline (http://usrportage.de/archives/940-Polite-Exceptions-Fixing-the-stepchild-of-API-design.html) for exceptions, and try to avoid direct usage of standard exceptions.

**Comment by ondrejmirtes** [comment]
Hi, requirement to import everything is already in the repository. Checkout `SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly` in the README.

You might have to exclude other sniffs that contradict this like `SlevomatCodingStandard.Namespaces.UseOnlyWhitelistedNamespaces` and sniffs that have `FullyQualified` in their name, but otherwise, this works well.

**Comment by ondrejmirtes** [comment]
Also, some other sniffs might be interesting to you, be sure to read the whole README.

**Comment by temp** [comment]
Oh - misinterpreted this one. Nice! The only place where we use full qualified names are @covers in phpunit tests. So I would configure fullyQualifiedKeywords with "@covers"?

**Comment by ondrejmirtes** [comment]
The sniff with `fullyQualifiedKeywords` works with language keywords like `extends` or `new`, not with annotations.

**Comment by ondrejmirtes** [comment]
I recommend you to copy our `SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameInAnnotation` sniff and modify it for your purposes.

**Comment by kukulich** [comment]
`ReferenceUsedNamesOnly` ignore all annotations so `@covers` with FQN should be ok.

**Comment by temp** [comment]
Ok, thanks. Looks like this in not necessary, a "@covers \My\Class" produces no warning.

**Comment by temp** [comment]
Thanks!
Any chance for the global Exception sniff?

**Comment by ondrejmirtes** [comment]
@temp What exactly are the requirements?

Also, be sure to check out PHPStan, another one of our projects, for more code quality (and bug-preventing) checks:

* Introduction article: https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3
* GitHub: https://github.com/phpstan/phpstan

**Comment by temp** [comment]
I know phpstan, and we already use it. Love it!
The requirements for the exception thing is fairly easy: never throw a global exception.
We always scope our exceptions (\Whatever\RuntimeException extends \RuntimeException), like described in the article I provided. 
In a nutshell:
Using the global exceptions makes it nearly impossible to catch specific errors, that's why we enforce it.
We go even further, every package on our side has a Marker Interface (\Whatever\ExceptionInterface extends Throwable), and the above mentioned RuntimeException implements the Marker Interface (\Whatever\RuntimeException implements \Whatever\ExceptionInterface). Based on that we have the concrete Exception: \Whatever\FileNotFoundException extends \Whatever\Runtimexception.
With this constuct you can catch everything coming from \Whatever:
catch (\Whatever\ExceptionInterface)
Or catch all RuntimeException from \Whatever:
catch (\Whatever\RuntimeException)
Or, of course, catch the concrete Exception:
catch (\Whatever\FileNotFoundException).

**Comment by TomasVotruba** [comment]
@temp You can find also some inspiration in this automated fixer: https://github.com/Symplify/CodingStandard#types-should-not-be-referenced-via-a-fullypartially-qualified-name-but-via-a-use-statement-wrench

**Comment by kukulich** [comment]
No plans to implement it currently.
