### ISSUE TITLE
anyway to let class use its interface function declaration?

### ISSUE THREAD

**Issue by videni** [slevomat/coding-standard#201]
```
interface OrderInterface
{
    public function getCheckoutCompletedAt(): \DateTime;
}

class Order extends OrderInterface
{
    public function getCheckoutCompletedAt()
     {

     }
}
```

I have lots of code like this,  anyway to fix this automaticially please?

**Comment by ondrejmirtes** [comment]
I don't think so, PHP_CodeSniffer does not have access to the class reflection.

**Comment by videni** [comment]
@ondrejmirtes ,I am new to phpcs,  thanks for telling me.

**Comment by ondrejmirtes** [comment]
@videni Check out this article if you want to know what different tools are capable of in PHP: https://medium.com/@ondrejmirtes/three-pillars-of-static-analysis-in-php-f3f5d7bfd61b

**Comment by Majkl578** [comment]
The code you referenced will generate fatal error because subclass is not allowed to omit previously speicfied return type. https://3v4l.org/ia8c1

**Comment by videni** [comment]
@ondrejmirtes , thanks , that article is very helpful
