### ISSUE TITLE
FullyQualifiedGlobalFunctions - support for excludes

### ISSUE THREAD

**Issue by KacerCZ** [slevomat/coding-standard#210]
Is is possible to extend sniff `SlevomatCodingStandard.Namespaces.FullyQualifiedGlobalFunctions` to support list of function names which are not reported?

I'm using gettext extension for translations and using fully qualified name for function `_` creates ugly symbol soup. For example `$message = \sprintf( \_( 'Message code %d.' ), $code );`.

PHP-CS-Fixer supports this setting for 'native_function_invocation' as 'exclude' parameter.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/f6667fac2306fed1fad6d0aee4f7f32ecc863ddc.

**Comment by KacerCZ** [comment]
Tested, works as expected.
Thank you.
