### ISSUE TITLE
What is difference AssignmentInConditionSniff to native one?

### ISSUE THREAD

**Issue by TomasVotruba** [slevomat/coding-standard#218]
How does local `AssignmentInConditionSniff` differs [to native AssignmentInConditionSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php)? Apart one adding error and other adding warning.

I get same output on simple assignment: 

![image](https://user-images.githubusercontent.com/924196/33662345-c3a04b1a-da8b-11e7-8552-7b25aa69e858.png)

**Comment by kukulich** [comment]
Native sniff exists since PHPCS 3.1.0. We support currently PHPCS >= 3.0.1.

There are some differences in the implementation as well however I did not have time to find out if it's possible to remove our sniff in future releases.

**Comment by TomasVotruba** [comment]
Thanks, I didn't know it was so fresh.
