### ISSUE TITLE
Unused use warning for class in @return

### ISSUE THREAD

**Issue by meridius** [slevomat/coding-standard#22]
I get fillowing even when my use is specified in `@return` doc comment.
> Type ReturnedClass is not used in this file (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)

Consider this:
```php
use Some\Space\ReturnedClassFactory;
use Some\Space\ReturnedClass;

class MyClass {

	/**
	 * Text
	 * @param string $type
	 * @return ReturnedClass
	 */
	private function getWriter($type) {
		...
		return ReturnedClassFactory::createWriter($type);
	}

}
```

**Comment by ondrejmirtes** [comment]
Please refer to the documentation of the sniff in the README. There's a setting to search in the annotations too.

Ondřej Mirtes




On Sat, Apr 2, 2016 at 3:12 PM -0700, "Martin Lukeš" <notifications@github.com> wrote:












I get fillowing even when my use is specified in @return doc comment.




Type ReturnedClass is not used in this file (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)




Consider this:

use Some\Space\ReturnedClassFactory;
use Some\Space\ReturnedClass;

class MyClass {

    /**
     * Text
     * @param string $type
     * @return ReturnedClass
     */
    private function getWriter($type) {
        ...
        return ReturnedClassFactory::createWriter($type);
    }

}

**Comment by meridius** [comment]
I know that @ondrejmirtes , but I'm not able to set my `ruleset.xml` to use that setting. Here is my ruleset (trimmed), I'd be very grateful, if you could look into that.

```xml
<?xml version="1.0"?>
<ruleset name="Meridius Coding Standard">

    <rule ref="./vendor/slevomat/coding-standard/SlevomatCodingStandard/ruleset.xml">
        <exclude name="SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameAfterKeyword" /> <!-- I want every (extends/implements) to be defined in use section -->
        <exclude name="SlevomatCodingStandard.Namespaces.FullyQualifiedExceptions.NonFullyQualifiedException" /> <!-- I want even exceptions to be defined in use section -->
        <exclude name="SlevomatCodingStandard.Namespaces.UseOnlyWhitelistedNamespaces.NonFullyQualified" /> <!-- this just prevents using the "use" section -->
        <exclude name="SlevomatCodingStandard.Files.TypeNameMatchesFileName" /> <!-- this expects the myname/projectname/src/MyName/ProjectName/MyClass.php structure, which may be right, but is damn-too-long -->
    </rule>

    <rule ref="SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse">
        <properties>
            <property name="searchAnnotations" type="boolean" value="true" />
        </properties>
    </rule>

</ruleset>
```

Thank you in advance

**Comment by janlanger** [comment]
@meridius Take a look in here for correct syntax https://github.com/slevomat/csob-gateway/blob/master/build/ruleset.xml#L18 The ref="" should be `SlevomatCodingStandard.Namespaces.UnusedUses`

**Comment by meridius** [comment]
Thank you @janlanger
