### ISSUE TITLE
phpcbf failed to fix superfluous TypeHintDeclaration.UselessParameterAnnotation for variadic parameter

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#220]
The code looked like this:
```php
/**
 * @param object ...$elements
 */
public function foo(int $bar, object ...$elements) : void
{
}
```
After running phpcbf, method signature was changed but docblock was not removed, phpcbf ended with error `FAILED TO FIX`.

**Comment by kukulich** [comment]
@Majkl578 Could you please test version 4.1.0 ?

**Comment by Majkl578** [comment]
Will let you know later, can't really test now due https://github.com/slevomat/coding-standard/commit/7df050c2c2ac0a2316f9bfb936fd95b4462710e0#commitcomment-26381405

**Comment by Majkl578** [comment]
Works with 4.1.0, thanks!
