### ISSUE TITLE
Documentation for IncorrectWhitespaceBetweenOpenTagAndDeclare

### ISSUE THREAD

**Issue by redthor** [slevomat/coding-standard#243]
Hi there,
I started getting this 

` 3 | ERROR | [x] There must be a single space between the PHP open tag and declare statement. (SlevomatCodingStandard.TypeHints.DeclareStrictTypes.IncorrectWhitespaceBetweenOpenTagAndDeclare)`

I couldn't find any documentation about it. Do you know why this check exists?
Thanks!

**Comment by Majkl578** [comment]
It's documented in README: https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintsdeclarestricttypes-

**Comment by redthor** [comment]
Sorry, I don't see `IncorrectWhitespaceBetweenOpenTagAndDeclare` in there...

**Comment by Majkl578** [comment]
Error code is something different than option name. Maybe it's a bit confusing. What causes your error is option called `newlinesCountBetweenOpenTagAndDeclare`, also see [source](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/TypeHints/DeclareStrictTypesSniff.php#L131) for a proof.

**Comment by redthor** [comment]
Ok, I think I get it. Somewhere the `newlinesCountBetweenOpenTagAndDeclare` is set to zero? If it is set to zero it then requires that we have a space after `<?php`, so that it becomes `<?php_`.

That makes sense, otherwise the opening tag would be `<?phpdeclare(strict_types`

Interestingly, I can add a space after the opening tag, e.g. `<?php_` *and* add two newline characters before the `declare...` and it does stop the `IncorrectWhitespaceBetweenOpenTagAndDeclare` failure. However I do not get an error about the two newlines when zero was expected.

**Comment by kukulich** [comment]
> Interestingly, I can add a space after the opening tag, e.g. <?php_ and add two newline characters before the declare... and it does stop the IncorrectWhitespaceBetweenOpenTagAndDeclare failure. However I do not get an error about the two newlines when zero was expected.

It's a bug, I'll fix it.

**Comment by kukulich** [comment]
Should be fixed in https://github.com/slevomat/coding-standard/commit/8f5437d5c9124b06526a854ceb0b648bf37ac6ec
