### ISSUE TITLE
FullyQualifiedExceptions systemExceptions option

### ISSUE THREAD

**Issue by Soullivaneuh** [slevomat/coding-standard#246]
Feature idea for `SlevomatCodingStandard.Namespaces.FullyQualifiedExceptions`: Adding a `systemExceptions` option.

This will enforce the sniffer to match only PHP root exception name matching (`RuntimeException`, `LogicException` etc...) instead of `*Exception`.

It would make things easier rather than having to list all our custom exceptions on a list.

WDYT? :-)

**Comment by kukulich** [comment]
It would be better to prepare special sniff `FullyQualifiedGlobalExceptions`. Would you prepare a PR?

**Comment by Soullivaneuh** [comment]
What do you mean by a `FullyQualifiedGlobalExceptions` ? The goal for me it not too use FQCN for global exception but convert to FQCN all exception which look like the global exception.

Sample: 

- `Foo\Bar\RuntimeException` -> Match
- `Foo\Bar\LogicException` -> Match
- `Foo\Bar\FishingRuntimeException` -> Does not match
- `Foo\Bar\NotRelatedException` -> Does not match

Do we agree? :-)

I don't see why not an option. :thinking:

**Comment by Majkl578** [comment]
I personally don't see logic behind such convention so -1 from me...

**Comment by kukulich** [comment]
Agreed.

**Comment by Soullivaneuh** [comment]
The logic is to make FQCN usage for exception with same names as the system ones.

It make no senses to use FQCN for all classes just because they finish with `Exception`.

Would you accept a PR for it? It's still just an option after all.

**Comment by Majkl578** [comment]
Why do you use custom exceptions with the same unqualified name as built-ins? Better have meaningful exception names like NameNotUniqueException that extends \RuntimeException and implements you package's ExceptionInterface.

**Comment by kukulich** [comment]
I agree with Majkl578 so I’m sorry I would not accept such a PR.

**Comment by Soullivaneuh** [comment]
> Why do you use custom exceptions with the same unqualified name as built-ins?

I don't. But some libraries does and I can handle that.
