### ISSUE TITLE
Check return typehint on anonymous functions

### ISSUE THREAD

**Issue by Soullivaneuh** [slevomat/coding-standard#249]
Sample:

```php
$node->validate()
    ->ifTrue(static function (array $services) { return 0 === \count($services); })
    ->thenInvalid('You must enable at least one service.')
;
```

Can be converted to this:

```php
$node->validate()
    ->ifTrue(static function (array $services): bool { return 0 === \count($services); })
    ->thenInvalid('You must enable at least one service.')
;
```

The sniffer currently does not handle that case.

**Comment by kukulich** [comment]
It's not easy to detect that your function returns boolean. That's why we support only `void` for anonymous functions.

**Comment by Soullivaneuh** [comment]
Well, I did a bad explanation.

I didn't mean for a fixer, but the sniffer tells nothing about that.

IMO, the code-sniffer should add an error about a missing type-hint, should it not?

**Comment by Majkl578** [comment]
No, it can be mixed or anything and it can't be documented (closures have no phpDoc block), only safely detectable is void. This has been explained in past in another issue (can't provide a link now from phone).

**Comment by Majkl578** [comment]
@Soullivaneuh See explanation in #230.

**Comment by Soullivaneuh** [comment]
@Majkl578 I totally agree for the impossibility to add a `@return` annotation, but we may introduce an option just for missing typehint warning? On most of the cases, an anonymous function does not returns tons of value type, it may be interesting to have this option.
