### ISSUE TITLE
Parse annotations with phpstan/phpdoc-parser

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#251]
https://github.com/phpstan/phpdoc-parser

**Comment by Majkl578** [comment]
:top: Will this also add support for Foo<> notation?

**Comment by kukulich** [comment]
Yes

**Comment by CZechBoY** [comment]
Can we somehow ignore errors from `Foo<> notation `? But know whole sniff `SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.InvalidFormat`.

**Comment by Majkl578** [comment]
Next PhpStorm EAP will support intersection types on parser level (but still treat them as unions), so this is more actual than ever. :)
https://youtrack.jetbrains.com/issue/WI-39419#focus=streamItem-27-3061342-0-0

**Comment by Majkl578** [comment]
https://blog.jetbrains.com/phpstorm/2018/09/phpstorm-2018-3-eap-183-2635-12/

**Comment by simPod** [comment]
PHPStan support is out https://github.com/phpstan/phpstan/commit/73cc2118c873c082aa8fbe7b037188ec4d04e7a1

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/824a235ae9889eb274b353346ae653adace4b3f4 and https://github.com/slevomat/coding-standard/commit/91b8c2a816979b3480aeeda61a579450d7bfc974
