### ISSUE TITLE
The required order of use statement types should be configurable

### ISSUE THREAD

**Issue by nicwortel** [slevomat/coding-standard#261]
The SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses sniff enforces the order in which the use statement types (class, function, constant) are listed. However, the required order (class, constant, function) is hard coded in [`UseStatement.php`](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Helpers/UseStatement.php#L116-L120), and differs from the order that is required by the now in review [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements) (class, function, constant).

If the order of use statement types would be configurable, people could configure the sniff to follow PSR-12.

The example from PSR-12:

```php
<?php

/**
 * This file contains an example of coding styles.
 */

declare(strict_types=1);

namespace Vendor\Package;

use Vendor\Package\{ClassA as A, ClassB, ClassC as C};
use Vendor\Package\Namespace\ClassD as D;
use Vendor\Package\AnotherNamespace\ClassE as E;

use function Vendor\Package\{functionA, functionB, functionC};
use function Another\Vendor\functionD;

use const Vendor\Package\{CONSTANT_A, CONSTANT_B, CONSTANT_C};
use const Another\Vendor\CONSTANT_D;

/**
 * FooBar is an example class.
 */
class FooBar
{
    // ... additional PHP code ...
}
```

**Comment by kukulich** [comment]
@nicwortel I think PSR-12 is wrong because it doesn't reflect how editors (eg. PHPStorm) currently work.

**Comment by alcaeus** [comment]
@kukulich wouldn't that be a reason to make it configurable? I expect IDEs to follow suit once PSR-12 has gone through the vote. It might be worth holding off on building it until the discussion is through though.

The way I see it, if the sniff is expected to support PSR-12, it would also have to allow for the newline between the use statement groups.

**Comment by kukulich** [comment]
https://github.com/php-fig/fig-standards/pull/1007 :)

>  it would also have to allow for the newline between the use statement groups.

It would be better to provide new sniff for `use` formatting.

**Comment by alcaeus** [comment]
Yes, a new sniff would make sense. Don't want one sniff to do too much 👍

**Comment by nicwortel** [comment]
I also filed an issue for PhpStorm to make the order configurable: https://youtrack.jetbrains.com/issue/WI-40357

Also see https://youtrack.jetbrains.com/issue/WI-40590 for the newlines between the import types.

**Comment by kukulich** [comment]
Ok, https://github.com/php-fig/fig-standards/pull/1007 was declined so I'll do new configuration option. Just have to figure out how the configuration should look like.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/144cbdf12991520721c3becfcabd759af6d982ca

**Comment by nicwortel** [comment]
Thank you!

**Comment by kukulich** [comment]
The sniff for `use` spacing just landed in master: https://github.com/slevomat/coding-standard/commit/e5e3a25327abf80afad3bf8b34218dfcbd079140
