### ISSUE TITLE
EarlyExit doesn't properly handle binary AND in condition

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#268]
```php
if ($invoke & self::INVOKE_MANAGER) {
    $this->eventManager->dispatchEvent($eventName, $event);
}
```
after fixing becomes:
```php
if (!$invoke & self::INVOKE_MANAGER) {
    return;
}

$this->eventManager->dispatchEvent($eventName, $event);
```

The negated condition should be put into braces, otherwise it breaks precedence: https://3v4l.org/Gs1GX

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/7e2a06c261ec4815c124ee019deabca6d86e5fc9
