### ISSUE TITLE
Unused use warning for class in type comment

### ISSUE THREAD

**Issue by meridius** [slevomat/coding-standard#27]
As far as I know, there is no support for parsing type comments by _SlevomatCodingStandard.Namespaces.UnusedUses_.

Consider this, which will be found as error _SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse_
```php
use Bar\Something;
use Foo\MyType;

...

/* @var $variable MyType */
$variable = Something::create();
```

Could support for that be added please?

**Comment by ondrejmirtes** [comment]
Do you have searchAnnotations set to true as advised in #22? Can you send failing test or PR?

**Comment by meridius** [comment]
Sure I have searchAnnotations enabled. ;)
Here is the failing test.
