### ISSUE TITLE
Sniff to force strict comparisons when strict types are enabled

### ISSUE THREAD

**Issue by alcaeus** [slevomat/coding-standard#270]
`declare(strict_types = 1)` does not affect functions like `in_array` that have a `$strict` parameter. There should be a sniff to require explicitly passing either `true` or `false` when strict typing is enabled. Requiring passing `false` allows for cases where strict type checks are explicitly not wanted without disabling the sniffs.

List of methods I found that have a `$strict` parameter:
* `base64_decode`
* `in_array`
* `array_search`
* `array_keys`

**Comment by alcaeus** [comment]
`SlevomatCodingStandard.Types.RequireStrictFunctionCalls`?

**Comment by kukulich** [comment]
Do you agree that this sniff should not be fixable?

Or I can add option `$fixable` with big warning and then add `true` always.

**Comment by alcaeus** [comment]
I think it's best to leave it not fixable and let the developer deal with the fallout. Always assuming `true` can have unintended consequences and we don't want to guess what the developer was thinking.

**Comment by kukulich** [comment]
It looks that the check is already in PHPStan (https://github.com/phpstan/phpstan-strict-rules) so I think it's no need to duplicate it in PHPCS...

However I've just improved the PHPStan rule based on your suggestions:
- https://github.com/phpstan/phpstan-strict-rules/pull/10/commits/1027243a0bb1df3cfd1d37f84ada3627560f2f77
- https://github.com/phpstan/phpstan-strict-rules/pull/10/commits/9dcbc65cc348a11254c5f00bba1a8baa973efd13

**Comment by alcaeus** [comment]
Oh, I didn't know those - will have to check them out. Thanks for the improvements!
