### ISSUE TITLE
EarlyExit fixer - incorrectly (not-)negated code #2 (with isset)

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#275]
This code from [Doctrine's SimpleObjectHydrator](https://github.com/doctrine/doctrine2/blob/e0ee4b1ad7acb0efbe89553eb3176d36b29713ec/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php#L125):
```php
if (! isset($data[$fieldName]) || ! $valueIsNull) {
    $data[$fieldName] = $value;
}
```
fixer converts it into:
```php
if (isset($data[$fieldName]) || ! $valueIsNull) {
     continue;
}

$data[$fieldName] = $value;
```

**Comment by kukulich** [comment]
I'm always happy when I wake up and see new reported bugs from you 😀 

Just kidding :) Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/abecb88680e18e35e19c03472fef39ddb0af6d66.
