### ISSUE TITLE
UnusedUses - Classes `use`'d by Documentation Now Marked Unused

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#285]
We updated from 4.1.0 to 4.4.5 today and suddenly all our types that are `use`-d for documentation by  strictly in documentation like `@return DiInterface` are marked unused by `SlevomatCodingStandard.Namespaces.UnusedUses`

I suspect #283 may have had something to do with the break.

The following is a broken example:

```
<?php

namespace Controller\cli\tools;

use Iron\Controller\AbstractController;
use Iron\Di\DiInterface;

class Report extends AbstractController {

	/** @var DiInterface */
	protected $di;
}
```

We have an automatic process to cbf fix `SlevomatCodingStandard.Namespaces.UnusedUses` specifically so this came as a bit of a shock as hundreds of files suddenly had their documentation broken ;)

**Comment by kukulich** [comment]
@donatj Can you please check `dev-master`?

**Comment by donatj** [comment]
I can in about an hour. Just driving home from work.

**Comment by donatj** [comment]
I totally spaced that it's Valentine's day and I had dinner plans with my
wife. I will work on this tomorrow.

**Comment by donatj** [comment]
Tried it again with `dev-master` - still an issue - even with that example file given above. 

Running it just against the file above I receive

```
FILE: /Users/jdonat/Sites/myon/test.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | ERROR | [x] Type Iron\Di\DiInterface is not used in this file.
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

**Comment by Majkl578** [comment]
Did you enable `searchAnnotations` option?
```xml
    <rule ref="SlevomatCodingStandard.Namespaces.UnusedUses">
        <properties>
            <property name="searchAnnotations" type="boolean" value="true"/>
        </properties>
</rule>
```

**Comment by donatj** [comment]
@Majkl578 Good question. We did not - Is that option new or were we just relying on a bug?

That eliminated **most** of the problem's. Let me take a look at the couple we still have and see if they're legit. If they are I'll try to boil them down into examples.

**Comment by Majkl578** [comment]
It's there since ever: https://github.com/slevomat/coding-standard/blame/master/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php#L21

**Comment by Majkl578** [comment]
Also please make sure you test with dev-master, 4.4.5 has some known bugs (waiting for 4.4.6 which should fix them).
https://github.com/slevomat/coding-standard/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+unuseduses

**Comment by donatj** [comment]
@Majkl578 Yep, I am on dev-master as @kukulich asked me to be.

The remaining issues all appear to be with things using `@var` within a method ala:

```php
<?php

namespace Controller\cli\tools;

use Iron\Controller\AbstractController;
use Iron\Di\DiInterface;

class Report extends AbstractController {

	function doThing( $thing ) {
		/**
		 * @var $soup DiInterface
		 */
		$soup = $thing;

		return $soup;
	}
}
```

The example above is silly of course, I just boiled it down - our use case are things we are pulling out of Di that are not typed, we tell our static analyzers the type with a syntax as above.

**Comment by kukulich** [comment]
I cannot decide if it’s a bug or feature :)

There’s another sniff that reports this as invalid because the right versiou should be “@var UserMapper $userMapper”

**Comment by donatj** [comment]
@kukulich http://docs.phpdoc.org/references/phpdoc/tags/var.html  PHPDocumentor has the type first in their documentation ;)

**Comment by Majkl578** [comment]
Imho the given code is invalid, it should be `@var DiInterface $soup`.

**Comment by donatj** [comment]
I'm not going to put up a fight over it. 

Just going to have to update a bunch of places in our code I guess ;)

**Comment by donatj** [comment]
For the record I did have `searchAnnotations` turned on - just not in the ruleset I made to debug the problem ;)

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/86262345729a05d8633a080e4862f5a5379de38d
