### ISSUE TITLE
Undefined index: scope_opener

### ISSUE THREAD

**Issue by mkroeders** [slevomat/coding-standard#286]
The `EarlyExitSniff` has an internal exception when the `scope_opener` is not set for line 47. My feeling says it will also fail for `scope_closer`

Although I have no clue where the exact error comes from I have the understanding that the following code of mine that is sniffed produces the error;

```php
protected function bindParameters(): Statement
    {
        if ($this->hasState(static::STATE_NEW_PARAMETERS)) {
            $this->state ^= static::STATE_NEW_PARAMETERS;

            foreach ($this->parameters as $name => $value) {
                $type = PDO::PARAM_STR;
                if (is_object($value) || is_array($value)) {
                    $value = json_encode($value);
                } else if (is_bool($value)) {
                    $type = PDO::PARAM_BOOL;
                } else if (is_int($value)) {
                    $type = PDO::PARAM_INT;
                } else if ($value === null) {
                    $type = PDO::PARAM_NULL;
                }

                $this->statement->bindValue($name, $value, $type);
            }
        }
        return $this;
    }
```

Hope it can be fixed

**Comment by kukulich** [comment]
@mkroeders What version do you use? Can you please check master?

**Comment by mkroeders** [comment]
Was running 4.4.6, changed to dev master but still get an error

`	An error occurred during processing; checking has been aborted. The error message was:
   |       | Undefined index: scope_closer in EarlyExitSniff.php
   |       | on line 477 (Internal.Exception)`

**Comment by kukulich** [comment]
@mkroeders No, the right fix is to write `elseif` correctly, that means without the space.

**Comment by mkroeders** [comment]
@kukulich using `elseif` indeed fixed the error. Perhaps make a sniff that `else if` is not valid

**Comment by Majkl578** [comment]
It's already part of PSR-2:
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR2/Sniffs/ControlStructures/ElseIfDeclarationSniff.php

But the sniff should not break on `else if` either imho.

**Comment by kukulich** [comment]
Yes, I’ll throw an exception.
