### ISSUE TITLE
UselessDocComment error if there is only @thows in docblock

### ISSUE THREAD

**Issue by fefas** [slevomat/coding-standard#299]
Hello,

I don't know if that is a bug or an expected behavior, but it seems strange to me and by looking the code I couldn't figure out if this Sniff would be configurable.

My problem is that the following method is generating an `UselessDocComment` error:
```php
/**
 * @throws VoucherNotRedeemableException
 */
public function method(string $param, SomeClass $someClass): int { /* ... */ }
```

If this error is not expected, maybe a new `if` is missing around line 566 of `TypeHintDeclarationSniff.php`.

**Comment by kukulich** [comment]
@fefas Did you read README?

**Comment by fefas** [comment]
@kukulich .. yes, I did. You mean [this part](https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintstypehintdeclaration-)? Sorry, if I've missed something..

**Comment by kukulich** [comment]
Yes, I did. There's a list with options of this sniff.

**Comment by fefas** [comment]
Mh! I see.. I can provide it in `usefulAnnotations` .. I've added the following config and it works fine 😄
```xml
<rule ref="SlevomatCodingStandard.TypeHints.TypeHintDeclaration">
    <properties>
        <property name="usefulAnnotations" type="array" value="@throws"/>
    </properties>
</rule>
```
Thanks a lot and sorry for haven't understood the docs well!

May I add this sample in README?

**Comment by kukulich** [comment]
Maybe later :)

**Comment by kanduvisla** [comment]
Sooo... I see now that `usefulAnnotations` is deprecated. How can I now let PHPCS pass if the docblock only contains `@throws`?

**Comment by mr-feek** [comment]
bump on this ^
