### ISSUE TITLE
False positive in SlevomatCodingStandard.Classes.UnusedPrivateElements.UnusedMethod

### ISSUE THREAD

**Issue by malarzm** [slevomat/coding-standard#305]
Seems like the sniff is not checking for method usage when passed as `callable`. In Doctrine ODM [`Expr::normalizeSortOrder`](https://github.com/doctrine/mongodb-odm/blob/c77d682033054a63a48c963131218d73a407ddea/lib/Doctrine/ODM/MongoDB/Query/Expr.php#L1418) is reported as unused even though it's used as [array_map's callback](https://github.com/doctrine/mongodb-odm/blob/c77d682033054a63a48c963131218d73a407ddea/lib/Doctrine/ODM/MongoDB/Query/Expr.php#L1292). 

I tried to take a look at the sniff in question but I don't think I'll be able to fix it myself :)

**Comment by kukulich** [comment]
See https://github.com/slevomat/coding-standard/issues/159

**Comment by malarzm** [comment]
Ah, thanks for the link and sorry for the noise!

**Comment by kukulich** [comment]
@malarzm No problem, I like issues that I can easy solve :D
