### ISSUE TITLE
EarlyExitSniff: Undefined index when body braces are missing in IF

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#312]
Hi,
I got this php error
```
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Undefined index: scope_closer in
   |       | ...\vendor\slevomat\coding-standard\SlevomatCodingStandard\Sniffs\ControlStructures\EarlyExitSniff.php
   |       | on line 199 (Internal.Exception)
```
when processing code like
```php
<?php

namespace Abc\def;

class Cls
{
    public function someMethod()
    {
        if (! $values->offsetExists('active'))
            $values->active = null;
    }
}
```

slevomat/coding-standard: 4.5
php: 7.1.11

**Comment by kukulich** [comment]
@CZechBoY Should this if be ignored or should it report better internal error?

**Comment by CZechBoY** [comment]
I would create new inspection/check for this, but will not throw any error.

Of course better than this is to write something like "Missing curly braces in IF statement."

**Comment by kukulich** [comment]
"Missing curly braces in IF statement" should be done in other sniff, not here.

**Comment by kukulich** [comment]
Notice fixed in master.

**Comment by f3l1x** [comment]
Well I've just recieved same error on this code.

```php
<?php declare(strict_types = 1);

class A
{

	public function b(): void
	{
		if (PHP_SAPI !== 'cli') return;
	}

}
```

```
An error occurred during processing; checking has been aborted. The error message was: Undefined index: scope_closer in
    |       |     .../vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php on line 195 (Internal.Exception)
```

How to fix it? I mean, I would like to write this type of condition. Should I disable this sniff?

**Comment by coudenysj** [comment]
You should not write code like that, is the answer here :). 

https://www.dwheeler.com/essays/apple-goto-fail.html

**Comment by kukulich** [comment]
@f3l1x You can prepare PR to support this :)
