### ISSUE TITLE
Error when using "else if"

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#313]
Hi,
I got this php error when my code uses "else if" instead of "elseif":
```
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Probably invalid "elseif" on
   |       | line 84. (Internal.Exception)
```
while line 84 is
```php
} else if ($value === 'abcdef') {
```

**Comment by kukulich** [comment]
@CZechBoY The error is correct, `elseif` is the right version.

**Comment by CZechBoY** [comment]
I know, but cannot this be somehow easily fixed/accepted by this library? And warn about it via some inspection/check?

**Comment by kukulich** [comment]
@CZechBoY It could probably be accepted if someone prepare a PR :)

**Comment by CZechBoY** [comment]
@kukulich Is it possible to run some pre-checks with phpcs?

**Comment by kukulich** [comment]
@CZechBoY You can run phpcs with different configuration first.
