### ISSUE TITLE
Unused private method, but it is used as callback

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#314]
Hi,
I have something like this code
```php
class Abc
{
    private function callbackMethod($a, $b)
    {
        return rand();
    }

    public function abcdef()
    {
        $data = [1, 2, 3, 4, 5];

        uasort($data, [$this, 'callbackMethod']);
    }
}
```

but method `callbackMethod` is false considered as unused.
slevomat/coding-standard: 4.5

**Comment by kukulich** [comment]
See https://github.com/slevomat/coding-standard/issues/159

**Comment by CZechBoY** [comment]
ok, this should be mentioned somewhere as known limitation... phpstorm detected that so the IDE problems are irrelevant now
