### ISSUE TITLE
UnusedUse: Method annotation with space between name and opening bracket

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#315]
Hi,
I have this code, which generates unused use:
```php
use Abc\UseDep;

/**
 * @method string myMethod (UseDep $par)
 */
class Abcdef
{
}
```

If I remove space between method name and opening bracket, it correctly reports nothing.
working example from above:
```php
use Abc\UseDep;

/**
 * @method string myMethod(UseDep $par)
 */
class Abcdef
{
}
```

**Comment by kukulich** [comment]
Thank you for your report, fixed in https://github.com/slevomat/coding-standard/commit/b826f0f31af0e7a093e36a429cf7aa28fd5d1054
