### ISSUE TITLE
Suggestion: NamespaceSpacing

### ISSUE THREAD

**Issue by novjan** [slevomat/coding-standard#320]
I have one tip for new Sniff and it is `NamespaceSpacing`.
It will be almost copy/paste of `SlevomatCodingStandard.Namespaces.UseSpacing`, but it will be for Namespace instead of Use.

What do you think?

**Comment by kukulich** [comment]
It looks that `PSR2.Namespaces.NamespaceDeclaration` doesn't check lines before the `namespace` declaration :(

So implemented in https://github.com/slevomat/coding-standard/commit/83e45f80067d9e97f7ebb6034f35d0359f1e1f55 :)
