### ISSUE TITLE
DocCommentSpacingSniff: support for annotations grouping

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#323]

**Comment by tominventisbe** [comment]
If this is about grouping "class" annotations such as Doctrine annotations, I second this, so e.g.:

```php
/**
 * @ORM\SomeDoctrineAnnotation1
 * @ORM\SomeDoctrineAnnotation2
 *
 * @var Test
 *
 * @return Test
 */
```

It may be interesting to note that this sniff cannot be currently enabled if you want this behavior as it is impossible to disable `linesCountBetweenDifferentAnnotationsTypes`, so either you will either have to have no lines between _all_ tags or the specified amount of lines between _all_ tags, including annotations; it is not possible to use it for just the other settings until this is fixed.

**Comment by kukulich** [comment]
@tominventisbe You could exclude the specific erroc code.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/8a81aeb05a8ac56aaa79bac03eb5984915cbb1be
