### ISSUE TITLE
Chained private methods false positive backport to 3.x

### ISSUE THREAD

**Issue by maryo** [slevomat/coding-standard#330]
Would it be please please possible to backport this fix into 3.x? I am updating coding standards for an older project on php 7.0.
I would do it myself as I did in my fork but it is probably not possible to make a PR for this (tag or a new branch name). I am using also a consistence/coding standard which last version supporting php 7.0 depends on 3.x.

**Comment by kukulich** [comment]
I’m sorry but I don’t want to support this old version anymore.

Just exclude the rule - it’s the most simple way.
