### ISSUE TITLE
Preg error when parsing types

### ISSUE THREAD

**Issue by paranoiq** [slevomat/coding-standard#333]
SlevomatCodingStandard\Helpers\TypeHelper::isTypeName() fails with `PREG error 2` when given name like `\Foo\Bar<T>`

**Comment by Majkl578** [comment]
This format is not supported.

**Comment by paranoiq** [comment]
thank you captain obvious. this issue is not about the result of the method, but about it crashing on unexpected input

**Comment by Majkl578** [comment]
No need for insulting responses.
Anyway imho not worth fixing since this is not supported anyway and will eventually be handled by #251. (Would like to prepare send PR?)

**Comment by kukulich** [comment]
@paranoiq Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/4eedbb1607ddbebca8eb177603a006e1ca7fa382
