### ISSUE TITLE
AlphabeticallySortedUses: make the PSR-12 order default

### ISSUE THREAD

**Issue by nicwortel** [slevomat/coding-standard#346]
As of PhpStorm 2018.1, [the order of class, function and constant `use` statements follows the order defined by PSR-12](https://youtrack.jetbrains.com/issue/WI-40357).

Therefor, the [default order in the sniff that was PhpStorm compatible](https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesalphabeticallysorteduses-) no longer makes sense (unless when using an older PhpStorm version).

I suggest removing the option and making the [PSR-12 order](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements) (classes, functions, constants) the default behavior.

Also see #261

**Comment by Majkl578** [comment]
> As of PhpStorm 2018.1, the order of class, function and constant use statements follows the order defined by PSR-12.

So far I have only seen random sort in PhpStorm.

This is a huge BC break.

**Comment by nicwortel** [comment]
I have to be a bit more specific: the auto-import function of PhpStorm indeed seems to be random. However, if you reformat your code (with "Optimize imports" enabled), PhpStorm will sort the `use` statements. The order used to be classes, constants, functions, but [has been changed in 2018.1 to classes, functions, constants](https://youtrack.jetbrains.com/issue/WI-40357) to be consistent with PSR-12.

The default behavior of the sniff follows the old behavior of PhpStorm (< 2018), which is why I suggest changing the default behavior to PSR-12 / the new PhpStorm behavior.

I agree that this is a BC break so I understand that this will probably be changed in a new major release.

**Comment by Majkl578** [comment]
FYI PSR-12 was moved back to discussion phase.

**Comment by simPod** [comment]
Related https://github.com/slevomat/coding-standard/pull/326

**Comment by mmoll** [comment]
What about making it configurable? :)
mayflower/mo4-coding-standard#44

**Comment by simPod** [comment]
AFAIK it is, see the docs https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesalphabeticallysorteduses-

it is just not default

**Comment by kukulich** [comment]
https://blog.jetbrains.com/phpstorm/2019/01/phpstorm-2019-1-early-access-program-is-open/

So I probably change the default in 5.0.0.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/9da52e730fcb3b6842d8e07906339a5f30dab32a
