### ISSUE TITLE
Idea: Check multi-line method call syntax

### ISSUE THREAD

**Issue by alcaeus** [slevomat/coding-standard#351]
This is relevant for code building on fluent interfaces, e.g. when using the query builders provided with Doctrine ORM or MongoDB ODM. The idea is to force the following syntax for multi-line function calls:
```
// Single-line syntax stays allowed
$this->getChild()->doSomething();

// Multi-line syntax
$this
    ->doSomething()
    ->beginBlock()
        ->doSomethingElse()
        ->beginBlock()
            ->doYetSomethingElse(
                $firstArg,
                $secondArg,
                [
                    'foo' => 'bar',
                    'baz' => 'foo',
                ]
            )
    ->doLastThing()
;
```

I was able to come up with the following rules
* Similar to multi-line function declarations, once there's a newline in a series of method calls, there MUST NOT be more than one call per line
* The first call MUST be on a new line, indented one step further than the previous line
* Each line MUST NOT increase indentation level more than once compared to the previous line
* Each line MAY decrease indentation level multiple times compared to the previous line, but MUST NOT be indented less than the first call
* If a single call is split up over multiple lines, its arguments MUST be presented on their own line
* The trailing semicolon must be on its own line indented the same as the original statement (in the example above, `$this`.

Is this something you would consider implementing? I could give it a shot, but don't really know where to start.

**Comment by kukulich** [comment]
I'll think about it. It's not easy but it's possible :)

Maybe there could also be an optional settings for method list that should always increase indentation level.

**Comment by alcaeus** [comment]
> Maybe there could also be an optional settings for method list that should always increase indentation level.

Sniff-level option is difficult, since builders may require moving back a few indentation levels. Take MongoDB ODM's aggregation builder for example:
```
$builder
    ->match()
        ->field('foo')
          ->gt(5)
          ->lt(2)
    ->group()
        ->field('_id')
          ->expression('...')
    ->execute()
;
```

**Comment by kukulich** [comment]
Should be already in PHPCS 3.5.0.
