### ISSUE TITLE
Split TypeHintDeclaration sniff

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#353]
This sniff is doing too much, also is extremely complex.
I'd like to propose splitting it into smaller sniffs, basically per use-case described in readme, namely:
* PropertyType - check that property always has `@var`
* FunctionParameterType - check that parameter has either native type or `@param`
* FunctionReturnType - check that function/method either native return type or `@return`
* CompleteFunctionDocComment - require documentation for all types, even redundant (yes, people still do that...); makes `enableEachParameterAndReturnInspection` redundant
* SuperfluousTypeDocumentation - check redundant `@param`/`@return` tags
* UselessDocComment - check that doc block does not contain useless annotations (not specific to `@param`/`@return`; makes `allAnnotationsAreUseful` obsolete
* ExplicitIterableType - require specifications for iterable types

**Comment by kukulich** [comment]
@Majkl578 This is just my intention for 5.0 so I’m very happy you make up all the sniffs names :)

There are some more sniffs that should be splitted to.

**Comment by sebastiaanluca** [comment]
Is there any update or feedback on this issue? Currently looking for a way to use `SlevomatCodingStandard.TypeHints.TypeHintDeclaration` and allow both full PHPDocs ánd type hints, regardless of duplicate definitions. `allAnnotationsAreUseful` seems to remove the PHPDocs when the variable definitions fully match the type hints.

**Comment by kukulich** [comment]
I've decided to implement only four sniff: https://github.com/slevomat/coding-standard/commit/7db89bee53a4f841cbd5d88efa473af6148cc027
