### ISSUE TITLE
MissingTraversableReturnTypeHintSpecification unclear how to fix

### ISSUE THREAD

**Issue by marcelloh** [slevomat/coding-standard#355]
I use a multidimansional array as a return value

I'm trying to fix this, but it is unclear to me, what the format is of the annotation

I even checked this to be sure:
var_dump("array",is_array($aResultPrefs));
var_dump('iter',is_iterable($aResultPrefs));
if($aResultPrefs instanceof \Traversable) {
    echo "is traversable";
}
and it's an array and is_iterable.

So my docBlock comment is:
* @return array[]|iterable fields with preferences for each field
But it still is wrong

I've looked in the data dir of the typehints tests, and I see annotations like:
* @return string[]|\Traversable
* @return array|iterable|\Traversable
* @return array[]
* @return \Traversable[]
* @return array[]|null

It is unclear how to fix this.
It would be nice if there was a kind of wiki-page, where people could find an example solution to fix errors like this.

Any help would be appreciated.

**Comment by kukulich** [comment]
@marcelloh You have to specify the type of the items. Eg. `@return string[]|array` or `@return mixed[]|iterable`

**Comment by marcelloh** [comment]
thanks :-) I though I had tried everything, but this combination was new hahaha...
