### ISSUE TITLE
PHPCS 3.3

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#360]
https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0

**Comment by Majkl578** [comment]
Hmm, lovely, ReturnTypeHintSpacing is completely broken. Incorrect spacing is not even detected by the sniff and is forcibly fixed to not have space before colon. :angry: 

semver ftw

**Comment by kukulich** [comment]
I'm happy I have tests because the upgrade will be very painful.

**Comment by Majkl578** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/issues/2049

Doctrine CS is broken too: https://travis-ci.org/doctrine/coding-standard/builds/389215937

**Comment by kukulich** [comment]
Hmm, standard situation with PHPCS release :(

**Comment by carusogabriel** [comment]
@kukulich Something we can help?

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/pull/361
