### ISSUE TITLE
Missing @inheritdoc support for properties

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#364]
Hi @kukulich. This is more a question than a bug report. Does `@var` annotations have the concept of `@inheritdoc`? e.g.:
```php
/**
 * {@inheritdoc}
 */
protected $signature = 'command:trigger';
```

Using `SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingPropertyTypeHint`, it reports some cases related to that.

**Comment by Majkl578** [comment]
https://docs.phpdoc.org/guides/inheritance.html#properties

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/f8e8d4de3d0bf00bf6234cde245f8307239cba77
