### ISSUE TITLE
RequireShortTernaryOperator improvements

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#372]
Small improvements that we can make to this Sniff :smile: 

`RequireShortTernaryOperator` does not work with properties:
```php
$bar = $this->foo ? $this->foo : '';
```

`RequireShortTernaryOperator` does not work with parentheses when them surround the first variable:
```php
$foo = ($bar) ? $bar : '';
```

Btw, using this second example, is there a Sniff to remove these unnecessaries parentheses? :innocent:

**Comment by kukulich** [comment]
Improved in https://github.com/slevomat/coding-standard/commit/f1748b9926e63ef789824409aeb971c0dc3b9c84
