### ISSUE TITLE
RequireCombinedAssignmentOperatorSniff

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#379]
Force the usage of `{operator}=`. E.g.:

```diff
-$sum = $sum + 3;
+$sum += 3;

-$string = $string . 'foo';
+$string .= 'foo'; 
```

**Comment by VasekPurchart** [comment]
Probably rather `.=` in the 2nd case? :)

**Comment by kukulich** [comment]
Shit... I would be much easier to add `+=` everywhere ;)

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/7d4bfbbde0e116b9b2eb730d5aa3cf26dc8b9c12
