### ISSUE TITLE
Sniff to forbid & replace __CLASS__, get_class(), get_parent_class() and get_called_class()

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#387]
* Replace `__CLASS__` with `self::class`
* Replace `get_class($this)` (with `$this` or no arguments) by `static::class`
* Replace `get_parent_class()` (without arguments) with `parent::class`
* Replace `get_called_class()` with `static::class`

`https://github.com/symfony/symfony/pull/27860`

**Comment by kukulich** [comment]
Nice idea!

Do you have suggestion for the sniff name?

**Comment by Majkl578** [comment]
I was thinking about `ModernClassNameReferencesSniff`, but dunno if you prefer one sniff or four. :)

**Comment by kukulich** [comment]
I think I will add one sniff with four codes.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/45aa8d0d9f58a595f8b027e1a3232b53bc6af646
