### ISSUE TITLE
FullyQualifiedClassNameInAnnotation modifies descriptions too.

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#394]
The fixer for `SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameInAnnotation` is a bit overzealous and unnecessarily modifies param descriptions too.

For e.g. it changes tag
```
@param Response $response Response
```
to
```
@param \Cake\Http\Response $response \Cake\Http\Response
```
expected was
```
@param \Cake\Http\Response $response Response
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/f9f15e8b2f31e800fba112272275cd90405a61df
