### ISSUE TITLE
Add option for TypeHints.TypeHintDeclaration's fixer to skip magic methods.

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#398]
It would be nice if there was an option to make the fixer skip adding type hints for magic methods like `__call()`, `__get()` etc. (basically any method starting with double underscores).

**Comment by kukulich** [comment]
Why? I don't see any reason.

**Comment by ADmad** [comment]
Well I don't see much value in adding typehints to magic methods. They are not meant to be called by user code and PHP will always call them with correct types. For e.g. what's the benefit for declaring `__call(string $name , array $arguments)` when PHP it always going to call it with string and array for 1st and 2nd argument respectively? Most people specify the types in docblocks mainly for consistency and making docblock related sniffers happy.

**Comment by kukulich** [comment]
I’m sorry but I still don’t see any benefit.
