### ISSUE TITLE
Idea: require closures to be static when not using $this

### ISSUE THREAD

**Issue by alcaeus** [slevomat/coding-standard#400]
Not sure if this should be a sniff or rather a part of phpstan-strict-rules, but consider the following example:
```
function (string $something) use ($otherThing): string {
    return $something . $otherThing;
}
```

Since the closure isn't using `$this`, it should be declared statically:
```
static function (string $something) use ($otherThing): string {
    return $something . $otherThing;
}
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/6a6ea0af49d9bef39029f60ab63cfd2616c1ea71
