### ISSUE TITLE
Improve RequireNullCoalesceOperator Sniff

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#401]
Hello there :wave: 

There's a case that I believe we can cover with the RequireNullCoalesceOperator sniff:
```diff
-return $foo !== null ? $foo : [];
+return $foo ?? [];
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/f8b5c704bae14e83ee17ebda65e095c5709284ed
