### ISSUE TITLE
Feature: NewWithoutParentheses

### ISSUE THREAD

**Issue by Levivb** [slevomat/coding-standard#410]
Hey,

Similar to how there's a sniff for [avoiding yoda-statements](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/ControlStructures/DisallowYodaComparisonSniff.php) and the opposite for [requiring yoda-statements](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/ControlStructures/RequireYodaComparisonSniff.php), it would be nice to have the reverse of [NewWithParentheses](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/ControlStructures/NewWithParenthesesSniff.php) possible called NewWithoutParentheses. Logically removing the empty `()` after `new`

Let me know what you think :)

**Comment by kukulich** [comment]
@Levivb Would you prepare PR?

**Comment by Levivb** [comment]
heh, I'll try. Have never created anything like a sniff. So I'd have to do some reading on how sniffers work. Due to a marriage of a family member at the end of this month of which I am one of the organizers for it might be beginning of next month. :)

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/83a5b0581ecde721942516f20226f4e9bd38166f

It was very easy for me and I want to do new release early :)

**Comment by Levivb** [comment]
I love you
