### ISSUE TITLE
Feature: UnusedClass

### ISSUE THREAD

**Issue by szepeviktor** [slevomat/coding-standard#411]
Hello!

Our codebase has classes which were used and planned to be used but not referenced currently.
Is it possible to detect them?

**Comment by ondrejmirtes** [comment]
It's not. Please check out https://medium.com/@ondrejmirtes/three-pillars-of-static-analysis-in-php-f3f5d7bfd61b why.

**Comment by szepeviktor** [comment]
Thanks.
When I tell Composer to `composer install --optimize-autoloader` I get a list of all classes in `vendor/composer/autoload_classmap.php`.
Is there a way to tell if a specific (I iterate over the above list) class is unused?

**Comment by kukulich** [comment]
It’s not possible with PHPCS.
