### ISSUE TITLE
Handling Laravel routes

### ISSUE THREAD

**Issue by szepeviktor** [slevomat/coding-standard#412]
```php
Route::get('/answers', [
    'as' => 'answer_list',
    'uses' => 'AnswerController@index',
]);
```

Could classes and methods be handled (unused, not existent, case mismatch etc.) in Laravel routes?

**Comment by mhujer** [comment]
@szepeviktor As the PHP_CodeSniffer cannot access other files I think this is a task for [PHPStan](https://github.com/phpstan/phpstan) (and its Laravel extension)

**Comment by szepeviktor** [comment]
Thank you.
