### ISSUE TITLE
`SlevomatCodingStandard.Classes.UnusedPrivateElements` fails to detect `[$this, 'name']` callbacks

### ISSUE THREAD

**Issue by Ocramius** [slevomat/coding-standard#413]
To reproduce, you can run the rule against something like following:

```php
final class Thing
{
    public function foo() : bool
    {
        return call_user_func([$this, 'bar']);
    };
    private function bar() : bool
    {
        return true;
    }
}
```

`bar` will be detected as unused symbol. Tricky, since it works for every scenario in which a `callable` is used.

**Comment by kukulich** [comment]
See https://github.com/slevomat/coding-standard/issues/159
