### ISSUE TITLE
Bug: UselessVariable causes syntax error with assignment in function argument

### ISSUE THREAD

**Issue by Levivb** [slevomat/coding-standard#419]
Hey,

Note: this might be a duplicate of #420 

Last weekend I noticed the following (simplified):
```php
function getUserByRecaller($recaller) {
    $this->viaRemember = !is_null($user = $response['user']);
    return $user;
}
```

Which, with the `UselessVariable` sniff is fixed to:
```php
function getUserByRecaller($recaller) {
    $this->viaRemember = !is_null(return $response['user']);
}
```

Note the return statement inside the `is_null` function call.

Now obviously, a variable assignment inside a function call shouldn't be done in the first place. So no wonder the sniff got the fix wrong :P

The resulting code does however error out in a rather dramatic fashion: syntax error<br>
For me, the linter in the pipeline catched the error, but not everyone might be so lucky.

I'm not sure what the potential bugfix here would be. One could argue the code sniffer should run a linter over each file it touches, although that should probably be something for phpcs itself. Perhaps skipping this sniff if the variable assignment is preceded by other code (see https://github.com/slevomat/coding-standard/issues/420 as well). Or a combination of skipping the `UselessVariable` and having an additional sniff, similar to `AssignmentInConditionSniff` which prohibits the assignment in function arguments (that might be complicated though).

Let me know what you think

Thanks in advance

**Comment by kukulich** [comment]
Thank you for your report.

Should be fixed with https://github.com/slevomat/coding-standard/commit/e470c10c66f4496c723d83fad2ccf7cf0729ee7f
