### ISSUE TITLE
UnnecessaryConditionWithReturnSniff

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#424]
```
if (cond()) {
  return true;
} else {
  return false;
}
```

```
if (cond()) {
  return true;
}

return false;
```

should be fixed to:

```
return cond();
```

```
cond() ? true : false
```

should be fixed to

```
cond()
```

**Comment by Levivb** [comment]
Note: this might cause problems with type hinting. 

For example:
```php
function getSpecials(array $array){
    return array_filter($array, static function($item){ return $item instanceof Special; });
}

function hasSpecialItems(array $array): bool
{
    return getSpecials($array) ? true : false;
}
```

Perhaps not the best of examples, but I hope it shows the need for a typehint check :P

And since phpcs can only check per file, whatever type the `cond()` function returns can often not be checked

**Comment by ondrejmirtes** [comment]
@Levivb I don't think you're right - in your case, both `getSpecials($array) ? true : false` and `getSpecials($array)` result type is boolean.

PHPCS is not the right tool for typehint checking, that's what tools like PHPStan are for. They can infer this better.

**Comment by Levivb** [comment]
Agree with the PHPStan comment.

But `getSpecials` actually returns an array. So `return getSpecials($array)` will also return an array and therefor error on the return typehint from `hasSpecialItems`

I've tinkered the following in `artisan tinker` (laravel):
```php
>>> function getSpecials(array $array): array {
...     return array_filter($array, static function($item){ return $item instanceof Special; });
... }
>>> function hasSpecialItems(array $array): bool
... {
... return getSpecials($array);
... }
>>> hasSpecialItems([])
TypeError: Return value of hasSpecialItems() must be of the type boolean, array returned
>>>
```

A possible solution would be to cast to boolean:
```php
>>> function getSpecials(array $array): array {
...     return array_filter($array, static function($item){ return $item instanceof Special; });
... }
>>>
>>> function hasSpecialItems(array $array): bool
... {
... return (bool)getSpecials($array);
... }
>>> hasSpecialItems([])
=> false
```

**Comment by ondrejmirtes** [comment]
Yeah, it's correct that the value in condition (both in `if` and in ternary) might be just truthy/falsey (like an empty array or an empty/non-empty string) so having this automatically fixed might be problematic. I'm so used to writing your situation like this:

```php
return count(getSpecials($array)) > 0 ? true : false;
```

That this didn't occur to me.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/d043592d4f611f788661152c59d1af8da11bce84
