### ISSUE TITLE
ModernClassNameReference breaks get_class() with non-$this parameter

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#429]
Currently transforms i.e. `get_class(new stdClass())` into `self::class`.

https://travis-ci.org/doctrine/coding-standard/jobs/422129786

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/4f955a34fa62a574b5c88fe6ce7f26780752e7f4

**Comment by CZechBoY** [comment]
@kukulich Same with get_parent_class.
