### ISSUE TITLE
Feature request - ParameterWithUnusedDefaultValue

### ISSUE THREAD

**Issue by ondrejmirtes** [slevomat/coding-standard#435]
```php
function foo(
    ?int $foo = null, // next param is not optional, remove = null
    ?int $bar
) {

}
```

And also (it's not related to nullability at all):

```php
function foo(
    int $foo = 1, // next param is not optional, remove = 1
    ?int $bar
) {

}
```

There might be a slight conflict with `NullableTypeForNullDefaultValue` because you can't safely remove the default value when it's used to mark parameter as nullable:

```php
function foo(
    int $foo = null, // next param is not optional but this makes $foo nullable
    ?int $bar
) {

}
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/0a7fc12bc353a1f6630a720d7bf9f3da0701f086
