### ISSUE TITLE
Optionally allow FQN for instanceof in ReferenceUsedNamesOnlySniff

### ISSUE THREAD

**Issue by finwe** [slevomat/coding-standard#44]
"Feature" request.

`instanceof` matching is potentially dangerous same ways as `throw`ing/`catch`ing exceptions, therefore FQN should be allowed (optionally with user setting, same as `$allowFullyQualifiedExceptions`).

**Comment by ondrejmirtes** [comment]
Have you tried putting `T_INSTANCEOF` in configurations of `SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameAfterKeyword` (`keywordsToCheck`) and `SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly` (`fullyQualifiedKeywords `)? I haven't tested it but it should just work. Refer to README for details.

**Comment by finwe** [comment]
Oh, this works. I already have `T_EXTENDS,T_IMPLEMENTS` there. Just forgot. And `Exception`s are a special token-less case I guess.

Thanks, closing this.
