### ISSUE TITLE
UselessInheritDocComment remove tag when useful

### ISSUE THREAD

**Issue by Soullivaneuh** [slevomat/coding-standard#441]
With this class sample:

```php
final class TextTypeExtension extends AbstractTypeExtension implements DataTransformerInterface
{
    // ...

    /**
     * {@inheritdoc}
     */
    public function transform($value)
    {
        return $value;
    }
}
```

It will remove the `inheritdoc` tag, and then tell me this:

```
 42 | ERROR | Method \AppBundle\Form\Extension\TextTypeExtension::transform() does not have parameter type hint nor @param annotation for its parameter $value. (SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingParameterTypeHint)
 42 | ERROR | Method \AppBundle\Form\Extension\TextTypeExtension::transform() does not have return type hint nor @return annotation for its return value. (SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingReturnTypeHint)
```

So I have to had this ($value can be anything here):

```
@param mixed $value
@return mixed
```

But those tags are already defined on the interface: https://github.com/symfony/symfony/blob/v4.1.4/src/Symfony/Component/Form/DataTransformerInterface.php#L44-L46

Maybe I'm wrong, but I don't think the inheritdoc tag is useless here. If yes, I'm curious to know on which cases this tag is not removed by the fixer. :-)

**Comment by kukulich** [comment]
Thank your for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/a6c2bac66f9114592163bbafb12e4bfe7303d7f3
