### ISSUE TITLE
ModernClassNameReference breaks get_parent_class() with non-$this parameter

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#444]
Currently transforms i.e. `get_parent_class(new stdClass())` into `parent::class`.

**Comment by Majkl578** [comment]
Confirmed this in Doctrine ORM:
```diff
-        $parent = get_parent_class($className);
+        $parent = parent::class;
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/0701666f3019a6f3df74492ae436206d914e1e17
