### ISSUE TITLE
UselessVariable: multiple attributions to the same variable

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#451]
An idea we might want to include into the `UselessVariableSniff`:

```php
$foo = $foo = 'foo'; // Reports multiple attributions

$foo = $bar = 'something'; // It's okay
```

**Comment by kukulich** [comment]
It does not make sense to add it to `UselessVariableSniff`. It would be better to prepare new sniff.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/b4b930df59fb2f6063462546449faa49785ebfab

**Comment by carusogabriel** [comment]
@kukulich Thanks, gonna try this out. From what I see, will it look for multiple assignments, not just twice? I know it's kind of impossible, but, as we are here :)

```php
$foo = $foo = 'foo'; // Wrong, one time

$bar = $bar = $bar = 'bar'/ // Wrong, two times
```

**Comment by kukulich** [comment]
@carusogabriel It's already reported, see https://github.com/slevomat/coding-standard/commit/21fdb9bcd6e8f141be2a6476b83fabb53370e4cc :)
