### ISSUE TITLE
Sniff to check that engine-optimized functions do not use argument unpacking

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#454]
There is [bunch of PHP functions](https://github.com/php/php-src/blob/850b53df0e3aa1a898db000244290fd0b7ecc8b6/Zend/zend_compile.c#L3916-L3975) that are optimized into specialized VM opcode. This [only works when argument unpacking is not used](https://github.com/php/php-src/blob/850b53df0e3aa1a898db000244290fd0b7ecc8b6/Zend/zend_compile.c#L3912-L3914).

Having a sniff which will point out when such function is used with variadics would be nice.

**Comment by kukulich** [comment]
@Majkl578 Could you please send one more PR and add the sniff to README? :)

**Comment by Majkl578** [comment]
You really need to add a CI check for that, I always forget to do it. :rofl: On it.
