### ISSUE TITLE
UnusedVariable: foreach without value

### ISSUE THREAD

**Issue by klapuch** [slevomat/coding-standard#458]
Hi,
Sometimes, it's desired to use `foreach` and its key without value. It's possible to use `array_keys`, but it's twice as slow. What do you think about ignoring variables as `$_`?

The following should pass:
```php
foreach ($values as $key => $_) {
  echo $key;
}
```
Thank you

**Comment by Levivb** [comment]
I tried that the first time around as well. It's not uncommon do use `_` as unused variable. In GO and Ruby anyway to my knowledge at least

**Comment by kukulich** [comment]
If more people ask for this feature, I'll add an option to ignore it.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/91a850b084d795625ea5690b213230394a23963e

However I'm not happy with the name of the option...
