### ISSUE TITLE
SlevomatCodingStandard.Namespaces.RequireOneNamespaceInFile rule does not exist

### ISSUE THREAD

**Issue by hhovakimyan** [slevomat/coding-standard#464]
I have installed `slevomat/coding-standard` package and tried to use SlevomatCodingStandard.Namespaces.RequireOneNamespaceInFile rule, but on code sniffer execution time it was reported to me, that this rule does not exist. But does this rule really exist or not? If it does not exist, please removed it from Github documentation page. It is wasting my and other developers' time.

**Comment by kukulich** [comment]
Yes, it exists. It’s used by this project itself.

There’s probably something wrong with your configuration.
