### ISSUE TITLE
InlineDocCommentDeclaration sniff has trouble with more complex docblock types

### ISSUE THREAD

**Issue by tominventisbe** [slevomat/coding-standard#467]
The `InlineDocCommentDeclaration` sniff seems to have trouble recognizing more complex docblock types, where it claims that the format is incorrect, for example:

```php
/** @var array<string, mixed> $plugins */
/** @var array<array<string, mixed>> $plugins */
```

I understand that this is not official phpDocumentor syntax, though I still think it may be supportable by searching for a dollar sign from the end of the string, though I may be wrong.

It may be worth noting that this is recognized properly:

```php
/** @var array<string> $plugins */
```

Thanks!

**Comment by kukulich** [comment]
It supposed to be solved with https://github.com/slevomat/coding-standard/issues/251
