### ISSUE TITLE
Sniff AlphabeticallySortedUses sorts alphabetically also functions

### ISSUE THREAD

**Issue by janedbal** [slevomat/coding-standard#47]
I know this it not so common, but this sniff behaves differently then optimizing use statements for example in PhpStorm. I don't know if this is intentional so I'm noticing it here.

Expected order by this sniff (strict alphabetical):
```php
use Doctrine\ORM\EntityManager;
use function GuzzleHttp\Psr7\str as format_http_message;
use GuzzleHttp\Exception\RequestException;
```

Optimized by PhpStorm (functions at the end):
```php
use Doctrine\ORM\EntityManager;
use GuzzleHttp\Exception\RequestException;
use function GuzzleHttp\Psr7\str as format_http_message;
```

**Comment by ondrejmirtes** [comment]
There is no support for use function a use const because I literally haven't heard about this syntax until now. We will fix it for sure in the future and try to stay compatible with PhpStorm. /cc @pepakriz

**Comment by pepakriz** [comment]
@ondrejmirtes  I agree

**Comment by ondrejmirtes** [comment]
Fixed with https://github.com/slevomat/coding-standard/commit/0a12b4a1fda0157d199a1e0e8f8c163902eba573
