### ISSUE TITLE
Rule to forbid `static::CONSTANT`

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#473]
Accessing constants with `static::` violates const invariant and should not be used.

https://3v4l.org/BUDNC

**Comment by kukulich** [comment]
@Majkl578 DisallowLateStaticBindingForContantsSniff?

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/729f62894430bc6d01c730a4088609a7ce63f6a6
