### ISSUE TITLE
RequireTernaryOperatorSniff

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#480]
I don't know if it's possible with CS Tools due to their complexity, but there're cases that we can use the `??` operator to simplify conditions:

```diff
-if (isset($bar)) {
-    $foo = $bar;
-} else {
-    $foo = 'default';
-}
+$foo = $bar ?? 'default';

-if (isset($bar)) {
-    return $bar;
-} else {
-    return 'default';
-}
+return $bar ?? 'default';
```

**Comment by kukulich** [comment]
It would be better to prepare RequireTernaryOperatorSniff

**Comment by carusogabriel** [comment]
@kukulich Sounds good. Require ternary operator over if/else struct :+1:

**Comment by ondrejmirtes** [comment]
`??` is called a coalesce operator, not ternary.

**Comment by ondrejmirtes** [comment]
Oh, sorry, I misunderstood (and also didn't want to close this).

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/189b946819fe3fd9454f1c25618a5903dac056e5
