### ISSUE TITLE
Typo in DisallowLateStaticBindingForContants

### ISSUE THREAD

**Issue by EvgenyOrekhov** [slevomat/coding-standard#488]
The first "s" is missing in the word "Constants". The files should be renamed.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/78d05a17a4b12746bfff32ffe5b289b02096bb48 and https://github.com/slevomat/coding-standard/commit/9b41ba31b745732d465f3f87d5194118aef4f1a1
