### ISSUE TITLE
Static closures not compatible with Closure::bind()

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#493]
BetterReflection uses closure binding to access object properties. Static closures cannot be bound to an object at all.
https://github.com/Roave/BetterReflection/blob/ffe74cae76a35d09cdc913fda5390a6317d170f6/src/Reflection/ReflectionProperty.php#L370-L372

This is probably impossible to fix in a generic way (would require static analysis), but preventing `Closure::bind(static function () ... {}, ...)` should be doable.

**Comment by kukulich** [comment]
Heh, I wrote this code in BR 😄

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/5d77d358c34723ab498a78d48c7ca589560c6aa5
