### ISSUE TITLE
DocCommentSpacing fixer removed whole methods non-standard docComment format encountered

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#494]
The following two docBlocks were merged into one and methods between them were removed:
https://github.com/doctrine/persistence/blob/9e18d0d4fcfb43004b1964399af17344d4dd7aad/tests/Doctrine/Tests/Common/Persistence/Mapping/SymfonyFileLocatorTest.php#L97-L147

Note that the second one has non-standard format:
```php
    /** @dataProvider customNamespaceLookupQueryProvider
```

Another strange thing is that after fixing the format manually and running PHPCS, wrong annotation order (`@dataProvider should be the last`) is not detected for [the first](https://github.com/doctrine/persistence/blob/9e18d0d4fcfb43004b1964399af17344d4dd7aad/tests/Doctrine/Tests/Common/Persistence/Mapping/SymfonyFileLocatorTest.php#L97-L105) method, [the second method](https://github.com/doctrine/persistence/blob/9e18d0d4fcfb43004b1964399af17344d4dd7aad/tests/Doctrine/Tests/Common/Persistence/Mapping/SymfonyFileLocatorTest.php#L97-L105) is detected and fixed.

**Comment by kukulich** [comment]
Fixed fixed in https://github.com/slevomat/coding-standard/commit/34304e38dc4dca4e201268745ba8f26239b25e5a

**Comment by kukulich** [comment]
Second error fixed in https://github.com/slevomat/coding-standard/commit/5e878708a16a75ed11a7d9aa02f50c257065d4fe
