### ISSUE TITLE
Yoda comparison is required & disallowed

### ISSUE THREAD

**Issue by szepeviktor** [slevomat/coding-standard#496]
```php
<?php declare(strict_types = 1);

$a = 1;

if ($a === 1) {
    echo 1;

    return 2;
} else {
    echo 'Please do not use else!';
}
```

`vendor/bin/phpcs --standard=vendor/slevomat/coding-standard/SlevomatCodingStandard/ a.php`

"Yoda comparison is required."

After changing to `1 === $a`: "Yoda comparisons are disallowed."
Please advise.

v4.8.1

**Comment by kukulich** [comment]
See readme.

**Comment by szepeviktor** [comment]
@kukulich Thank you.

I've searched the readme for "yoda" and found no mention that I must disable one of them or I find myself in this situation.
Could you help?

**Comment by ondrejmirtes** [comment]
See this section: https://github.com/slevomat/coding-standard#how-to-run-the-sniffs

Slevomat CS contains contradicting sniffs and its fine because it's not meant to be used as a whole.

**Comment by szepeviktor** [comment]
Thank you.
