### ISSUE TITLE
Sniff suggestion: HeredocShouldBeNowdoc

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#501]
[HEREDOCs](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) without variables should effectively be [NOWDOCs](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc), this may also eliminate some required escaping in some cases and also make code safer (less escaping -> less possible issues).

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/84f11171d376927aafd4b400fedd0203817d1934
