### ISSUE TITLE
UselessConditionWithReturnSniff autofixer may result in wrong return type

### ISSUE THREAD

**Issue by janedbal** [slevomat/coding-standard#503]
Following code:
```php
public function exists(): bool
{
        $order = $someQueryBuilder->getQuery()->getOneOrNullResult();
        return $order ? true : false;
}
```

will be "fixed" into:

```php
public function exists(): bool
{
        $order = $someQueryBuilder->getQuery()->getOneOrNullResult();
        return $order;
}
```

...which actually breaks the code. This sniff now relies on that the condition is boolean, which may not be true. It should fix only those, where it is boolean for sure (e.g. `$order !== null` comparison is used).

**Comment by kukulich** [comment]
It’s not possible with PHPCS.

**Comment by janedbal** [comment]
Yes it is. You just fix only those where there is a comparison or boolean operator in condition.

- `return $order ? true : false;` - not fixable
- `return $order->isValid() ? true : false;` - not fixable
- `return $order === null ? true : false;` - fixable
- `return $order->getPrice() > 0 ? true : false;` - fixable
- `return $order || $oldOrder ? true : false;` - fixable

**Comment by kukulich** [comment]
I want the second example to be fixable.

**Comment by janedbal** [comment]
Then it should be in readme that it may break code and it is implemented that way intentionally.

**Comment by TomasVotruba** [comment]
@janedbal What about this fixes? https://github.com/rectorphp/rector/pull/838/commits/b8c566d84b81068c7f25fbb57e7da654bab47fb5#diff-7844530a9a0bb539b3e0e66d55552c60

**Comment by TomasVotruba** [comment]
@janedbal Could you check this? https://github.com/rectorphp/rector/pull/838/commits/57c166e2d006e004d8ad235cb82ef230ed9ea6a2

@slevomat Why are you deleting this comment? It helps to solve the questoin.
