### ISSUE TITLE
UselessParentheses: bug when use include inside function

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#510]
Code to reproduce:

```diff
-Foo::bar(include($class), $dir);
+Foo::bar(include$class, $dir);
```

Ref: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ClassCacheCacheWarmer.php#L41

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/11c40c48186f6312258903f380197e959dddf078
