### ISSUE TITLE
UselessParantheses does not pick up arithmetic expressions

### ISSUE THREAD

**Issue by tominventisbe** [slevomat/coding-standard#514]
It appears the UselessParantheses sniff doesn't pick up arithmetic expressions. Not sure if this is intentional or an overight, since I don't see them in the tests either (so it may have been intentional).

```php
// Picked up.
$x = ($this->a);
```

```php
// Not picked up.
$x = (5 + 5);
```

```php
// Picked up, is happy when either inner or outer parantheses are removed.
$x = (5 + (3 + 5));
```

**Comment by kukulich** [comment]
It's not intentional but I won't fix it because I think this case is not so common.
