### ISSUE TITLE
Unused variable inside of foreach in case of modify value

### ISSUE THREAD

**Issue by o5** [slevomat/coding-standard#517]
Hello, I started to use sniff `SlevomatCodingStandard.Variables.UnusedVariable` but ends with this code:

```php
foreach ($array as &$value) {
   $value = 'changed';
}
```

```
FILE: /var/www/src/Foo/Bar.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 72 | ERROR | Unused variable $value
    |       | (SlevomatCodingStandard.Variables.UnusedVariable.UnusedVariable)
----------------------------------------------------------------------
```

Is it right behaviour? If yes what about the similar settings like `$ignoreUnusedValuesWhenOnlyKeysAreUsedInForeach`?

Thank you

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/3ffb5302191d3cce775a61adb527021dbcd1a555
