### ISSUE TITLE
Collections support

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#531]
Will collections be supported by this CS? `@var \ArrayObject<int, string> $var`

I know it's still in [draft mode](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#collections) but eg. PHPStorm will support it (currently in EAP, see [PHPDoc PSR-5 <generic> collection type hints](https://blog.jetbrains.com/phpstorm/2018/09/phpstorm-2018-3-eap-183-2635-12/))

For now `SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.InvalidFormat` is thrown for that syntax.

**Comment by kukulich** [comment]
Duplicate of #251

**Comment by simPod** [comment]
Late for the party 🎉 , thx
