### ISSUE TITLE
ClassNameReferencedViaFunctionCall in traits

### ISSUE THREAD

**Issue by paranoiq** [slevomat/coding-standard#538]
SlevomatCodingStandard.Classes.ModernClassNameReference.ClassNameReferencedViaFunctionCall

`$this::class` cannot be used in traits (`Fatal error: Dynamic class names are not allowed in compile-time ::class fetch`), so this rule should have exception for them

**Comment by kukulich** [comment]
@paranoiq Can you please post your code that reports the error? The fixer does not produce `$this::class`.

**Comment by paranoiq** [comment]
mea culpa. there are other ways arround this: https://3v4l.org/RlB62
