### ISSUE TITLE
A Number of Problems with UnusedVariableSniff

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#541]
I was very excited to see the addition of `UnusedVariableSniff` reviewing my way up the release notes after updating our version of the coding standard. Not all of our devs use IDE's, so it's a fairly common issue in our codebase.

After implementing it however I am sad to say we are getting a large number of false positives. 

I'm doing my best to roll the problems into examples without exposing real code.

---

### Case 1:

It appears if a string contains a backslash before a variable, it doesn't count as used. This is cropping up quite a bit for us as we have a fair deal of code generation with variables as namespace components.

```php
<?php

$foo = "ok";
$bar = "\\$foo";

echo $bar;
```

gives us

```
FILE: /Users/jdonat/Sites/myon/test.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | Unused variable $foo.
----------------------------------------------------------------------
```

----

### Case 2:

Another problem we're seeing in quite a few places is changing the value of a reference seems to be unhandled. See the following made up example.

```php
<?php

function &entryLocate() {
	$get = &$_GET['key'];
	return $get;
}

$x =& entryLocate();
$x = "change value of key";

print_r($_GET);
```

which outputs:

```
Array
(
    [key] => change value of key
)
```

gives us

```
FILE: /Users/jdonat/Sites/myon/test.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 9 | ERROR   | Unused variable $x.
----------------------------------------------------------------------
```

-----

### Case 3:

This isn't very pretty code but we've got a handful of this about. 

I'm not 100% sure you should even fix this, as it seems **kind of** like we're overwriting it immediately. I can see arguments on both sides.

Anyway thought you might want to be aware:

```php
<?php

$p = 0;
$data = ['a' => 1, 'b' => 2];
foreach($data as $id => $sisid){
	if(($p += 1) % 100 == 0){
		print ".";
	}
}
```

gives us

```
FILE: /Users/jdonat/Sites/myon/test.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | ERROR | Unused variable $p.
----------------------------------------------------------------------
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/52daf44e4efe94a50e279a0a160c287774f86066, https://github.com/slevomat/coding-standard/commit/a27623a4bba2ca40668cc30e91da09d2d42eecdd and https://github.com/slevomat/coding-standard/commit/8545c98802138e0069606d3689c416501d2fa5c3
