### ISSUE TITLE
UnusedUses - Parameter class in @method annotation marked as unused when multiple results are possible

### ISSUE THREAD

**Issue by holtkamp** [slevomat/coding-standard#542]
Not sure whether the title makes sense, difficult to describe this. See the example below.

```
- slevomat/coding-standard: 4.8.5
- PHP 7.1.23
```

--------
In the following scenario, `use Domain\ClassB;` is marked as being unused:

```php

use Domain\ClassA;
use Domain\ClassB;
use Illuminate\Support\Collection;

/**
 * @method ClassA[]|Collection findAll(ClassB $parameter)
 */
class SomeRepository {}
```

In this scenario `use Domain\ClassB;` is **not** marked as being unused:
```php

use Domain\ClassA;
use Domain\ClassB;

/**
 * @method ClassA[] findAll(ClassB $parameter)
 */
class SomeRepository {}
```

In this scenario `use Domain\ClassB;` is also **not** marked as being unused:
```php

use Domain\ClassB;
use Illuminate\Support\Collection;

/**
 * @method Collection findAll(ClassB $parameter)
 */
class SomeRepository {}
```

I can try to come up with a failing test case. But a PR would be quite difficult for me, little experience with the internals of this library...

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/bdeaa1abf3585ca588038e5dcb5a895c15defdf7
