### ISSUE TITLE
SlevomatCodingStandard.Classes.TraitUseSpacing removes everything between uses

### ISSUE THREAD

**Issue by stephanvierkant** [slevomat/coding-standard#544]
I enabled `SlevomatCodingStandard.Classes.TraitUseSpacing` and phpcs removed the `$id` from my code:

Before:
```
<?php

namespace Acme;

use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Timestampable\Traits\Timestampable;

class TestClass
{
    use Timestampable;
    
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    use BlameableEntity;
}

```

After:

```
// ...
class TestClass
{
    use Timestampable;
    use BlameableEntity;
}
```

I don't think defining attributes between traits is a good practice, but it would be nice if this fixer doesn't remove usefull code between traits.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/936c0b3e88a8f16c1f0c9eb831457c489445bf0b
