### ISSUE TITLE
make magicless conditions opt-in in UselessConditionWithReturn

### ISSUE THREAD

**Issue by VasekPurchart** [slevomat/coding-standard#557]
As described in #503, `UselessConditionWithReturn` sometimes can lead to broken code since it assumes that there are no magic type conversions in the conditions. Essentially is assumes that all expressions in the condition already result in boolean.

I think this is quire dangerous to have as a default behavior, but I understand the need to have this if your codebase is already magic free.

I think it would be best if this behavior would be turned on only as opt-in (default false) by a directive. My proposed name for it is `assumeAllConditionExpressionsAreAlreadyBoolean` - it is a bit long, but I think it should carry the message better when the explanation is included in it, rather than coming up with something shorter and having the documentation only in the readme.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/8d1b06286b80d03069cf704d138d6923648666ea
