### ISSUE TITLE
Autofixing for DisallowEqualOperators can break existing code

### ISSUE THREAD

**Issue by tominventisbe** [slevomat/coding-standard#559]
Autofixing for `DisallowEqualOperators` can sometimes break existing code, such as the following example:

```php
$someString = 'test';

// Autofixing will make this ===, which can never be true.
if (((bool) $someString) == '0') {
    // ...
}
```

To some degree I did still want the autofixing for this example as I wanted to move my code to use proper type hinting and all that anyway (and this example was crappy code to begin with), but as the other rules that possibly break code don't do autofixing - or some have it configurable, such as the constant visibility modifier -, it may be worthwhile to not autofix this and only report it or provide an option to specify it autofixing is desired or not.

Thanks!

**Comment by kukulich** [comment]
Just don't use the fixer if your code is not compatible :)
