### ISSUE TITLE
AssignmentInCondition and DisallowedYodaComparison break on lack of parenthesis

### ISSUE THREAD

**Issue by iltar** [slevomat/coding-standard#565]
![image](https://user-images.githubusercontent.com/1754678/49810672-ffcbc700-fd61-11e8-98da-b1b289995b4c.png)

```php
if (null === $env = $input->getOptions()['env']) {
    // ...
}
```
Gets turned into invalid php syntax:
```php
if ($env === null = $input->getOptions()['env']) {

}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/f9fab1421f74210c2fddbf6e26a1a6a35d5285e6

**Comment by iltar** [comment]
Thanks! This will save me a lot of manual fixing
