### ISSUE TITLE
UnusedVariableSniff Bug When Variable in Parens

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#579]
The following code marks `$runaway` as unused 

```
 5 | ERROR   | Unused variable $runaway.
```

```php
<?php

function foo() {
	$runaway = 6; // max depth is 5
	while( ($runaway-- > 0) ) {
		echo ".";
	}
}
```

While the parens seem silly in _this example_, they make sense in the much larger comparison I boiled the issue down from.

It does the same thing with both increment and decrement operators. 

Curiously however if we remove the second set of parens, it **does not** mark it as unused

```php
<?php

function foo() {
	$runaway = 6; // max depth is 5
	while( $runaway-- > 0 ) {
		echo ".";
	}
}
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/600e749c5b66c6f2a675a07356b65ca2398e9e3e
