### ISSUE TITLE
Autofixing in SlevomatCodingStandard.Exceptions.ReferenceThrowableOnly might break existing code

### ISSUE THREAD

**Issue by paslandau** [slevomat/coding-standard#580]
When `ReferenceThrowableOnly` runs only on some files, changing the type from `Exception` to `Throwable` might lead to breaking code. 

Real world use case: Implement an interface / override a class from a third party library.

Consider the following example:

Foo.php
===
```php
class Foo implements ifoo{
    public function bar(\Exception $e){

    }
}
```

ifoo.php
===
```php
interface ifoo{
    public function bar(\Exception $e);
}
```

Running `vendor/bin/phpcbf Foo.php --standard=error.xml`

will only replace the Exception in Foo.php but not in ifoo.php - making the implementation invalid due to differing types.

==>

Foo.php
===
```php
class Foo implements ifoo{
    public function bar(\Throwable $e){

    }
}
```

Proposed solution
===
Remove auto-fixing / enable only as opt-in.

**Comment by paslandau** [comment]
@kukulich 

Care to elaborate? Imho no rule should "break" existing code by default. If I opt in, I basically "give my blessing" (though a warning of some sort in the docu might still be helpful). But silently breaking code potentially makes me simply disable this check completely as it is too risky for me to let phpcbf do his job.

**Comment by mirsch** [comment]
@kukulich 
stumbled over the same problem.
Method declaration in external library is \Exception changing it to \Throwable in my code will result in a PHP Fatal error:  Declaration of ... must be compatible with ...
Acording to the documentation the Sniff should change only catch statements:
"So, if the catch statement contained Exception on PHP 5.x, it means it should probably be rewritten to reference Throwable on PHP 7.x. This sniff enforces that"
Changing this in method declarations and making them incompatible with there parents forces us to completely disable this Sniff.
