### ISSUE TITLE
[QUESTION] getFullClassNameByPointer helper function

### ISSUE THREAD

**Issue by vladyslavstartsev** [slevomat/coding-standard#581]
Is there any helper function that I can call, that will get 2 params `File $phpcsFile, $classPointer`

let me show an example (it looks ugly and random)

```php
<?php

declare(strict_types=1);


namespace App;


use SlevomatCodingStandard\Helpers\UseStatementHelper;
use SlevomatCodingStandard\Helpers\YodaHelper as YodaHelperAlias;

class FooClass
{
    protected $csFileGetterService;

    public function __construct(App\CsFileGetterService $csFileGetterService)
    {
        $this->csFileGetterService = $csFileGetterService;
    }

    public function barFunction()
    {
        $csFile = $this->csFileGetterService->getCsFile();
        $alias =  UseStatementHelper::getUseStatements($csFile, 123);
        YodaHelperAlias::fix($csFile, [],[]);
    }
}
```

so when analyzing this file with php_codesniffer
I get token number 117, which contains such data
```
array:8 [
  "type" => "T_STRING"
  "code" => 319
  "content" => "UseStatementHelper"
  "line" => 24
  "column" => 19
  "length" => 18
  "level" => 2
  "conditions" => array:2 [
    42 => 361
    89 => 346
  ]
]
```
and also token number 129,  which contains such data
```
array:8 [
  "type" => "T_STRING"
  "code" => 319
  "content" => "YodaHelperAlias"
  "line" => 25
  "column" => 9
  "length" => 15
  "level" => 2
  "conditions" => array:2 [
    42 => 361
    89 => 346
  ]
]
```

what I want is to pass some token number to some function and getFullyQualifiedName of it.
so it should look something like this
`SomeHelper::getFullyQualifiedName($csFile, 117)` returns `SlevomatCodingStandard\Helpers\UseStatementHelper`
`SomeHelper::getFullyQualifiedName($csFile, 129)` returns `SlevomatCodingStandard\Helpers\YodaHelper`

I have looked at other `getFullyQualifiedName` functions but they does not solve my problem

Is there one that solves?

**Comment by kukulich** [comment]
No, it is not.
