### ISSUE TITLE
Sniff to convert @var into typed properties

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#584]
Now that typed properties landed in php-src@master.

**Comment by Majkl578** [comment]
@kukulich Why is this milestoned for 6.0.0? There is no 5.0.0 either.

**Comment by kukulich** [comment]
@Majkl578 Because 5.0.0 is in progress and I will implemented this sniff after https://github.com/slevomat/coding-standard/issues/353

**Comment by Majkl578** [comment]
Hmm I don't understand why, also I need this sooner than _when 7.4 is released_. Already have WIP of the sniff...

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/e54322a9cd82d07437c51bd6bdcb56681d418cd9
