### ISSUE TITLE
Spacing in variadic functions

### ISSUE THREAD

**Issue by Stadly** [slevomat/coding-standard#591]
There seems to be no rules handling whitespace between the variadic indicator and the parameter name. I suggest making a rule that forces consistency. I prefer no whitespace.

You can currently mix it up like this:

```php
function foo1(...$bar);
function foo2(... $bar);
function foo3(...                  $bar);
function foo4(...
$bar);
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/0c1ac60b2f41036a4e4419dccb21ba24cf7aeee5
