### ISSUE TITLE
make sniff configuration to be non autofixable

### ISSUE THREAD

**Issue by vladyslavstartsev** [slevomat/coding-standard#593]
One of the use cases of this is `SlevomatCodingStandard.TypeHints.DeclareStrictTypes.DeclareStrictTypesMissing` in old apps, since you can't guarantee that someone somewhere haven't called a function `baz` with wrong param type.

What I mean can be described as (see also https://3v4l.org/W9XWN) 
```php
<php

declare(strict_types=1);

function baz(string $bar) 
{
    echo $bar;
}

$int = 0;
baz($int);
```

the same but without `declare(strict_types=1);` works perfectly fine https://3v4l.org/KqYKT

add new property that will configure if this sniff show be marked as auto fixable

**Comment by kukulich** [comment]
It does not make sense to me.

I think you should ignore `SlevomatCodingStandard.TypeHints.DeclareStrictTypes.DeclareStrictTypesMissing` directly.
