### ISSUE TITLE
Sniff to disallow `[]` syntax in favour of `<>` in annotations

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#598]

**Comment by Majkl578** [comment]
Title is confusing, is this about arrays or phpDoc types?

**Comment by kukulich** [comment]
About phpDoc types.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/4c37991359cfe1b84cf9a46c106f120464de743e
