### ISSUE TITLE
Automatic fix for UsedLongTypeHint deletes lines below `@return`

### ISSUE THREAD

**Issue by TysonAndre** [slevomat/coding-standard#603]
Expected: The line with ` false - if some other cond` is preserved. (The spacing is unimportant to me.)
Observed: The line with ` false - if some other cond` is deleted.

```
<?php
declare(strict_types=1);

/**
 * @return boolean - true - if some cond
 *                   false - if some other cond
 */
function test()
{
    return rand(0, 1) > 0;
}
```

The result of running phpcbf:

```patch
 /**
- * @return boolean - true - if some cond
- *                   false - if some other cond
+ * @return bool - true - if some cond
  */
```

I'm using dev-master of coding-standard and php_codesniffer

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/afccda9f9f497aaf4b426e88dd5dc744d68e04d9

I'm not able to preserve all whitespace :(
