### ISSUE TITLE
UselessTernaryOperator: Boolean in condition should be inferred when evident

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#604]
```php
<?php

class Foo
{
    public function uselessTernaryWithParameter(bool $condition) : bool
    {
        return $condition ? true : false;
    }

    public function uselessTernaryWithMethod() : bool
    {
        return $this->isFalse() ? true : false;
    }

    private function isFalse() : bool
    {
        return true;
    }
}
```

Here both returns are certainly boolean, it should be possible to infer this even with PHPCS. Right now these will go unfixed.

**Comment by ondrejmirtes** [comment]
It would be easier to do this rule in PHPStan IMHO. But there's no package for CS-like rules yet.

**Comment by carusogabriel** [comment]
@ondrejmirtes In PHPStan itself, or maybe an "CS-like" PHPStan extension?

**Comment by ondrejmirtes** [comment]
Yeah, I mean a CS-like package. PHPStan itself is only about finding bugs and dead code.

**Comment by kukulich** [comment]
This is too complicated to do it in PHPCS with tokens.
