### ISSUE TITLE
UselessParenthesesSniff removing necessary parenthesis

### ISSUE THREAD

**Issue by enumag** [slevomat/coding-standard#608]
In my code I have this line:

```php
return (10 - ($weightedResult % 10)) % 10;
```

The UselessParenthesesSniff changes it to this:

```php
return 10 - ($weightedResult % 10) % 10;
```

This is a bug because the result will be different for `$weightedResult = 0`.

https://3v4l.org/GdlIL

EDIT: Looking at the source code, this might be fixed in 5.0.0 (I'm still using 4.x). I'll try to update.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/bf123f11c40991d19dc5d62a63674c87bf35e453
