### ISSUE TITLE
Use different code for Missing Parameter Type Hint when it is documented in phpdoc

### ISSUE THREAD

**Issue by Billz95** [slevomat/coding-standard#609]
# Feature Request

Is it possible to split code `SlevomatCodingStandard.TypeHints.MissingPropertyTypeHint` into two?

One for the error 
```
 does not have parameter type hint for its parameter %s  but it should be possible to add it based on @param annotation %s
```
and the other one for error
```
%s %s() does not have parameter type hint nor @param annotation for its parameter %s.
```

# Rationale 

The reason that I want to do this is to support working with legacy code. Changing the method signature would mean breaking the inheritance. Also, the first error is much less severe than the second one, therefore it would make sense to give them different severity.

I'm currently using `arcanist` with `phpcs`. Though I'm able to change severity of linting result based on their code, I can't give the above mentioned two errors different severity because they have the same code. 

Also, I would prefer not to suppress this rule in the source code because distributed configuration is harder to be maintained than centralised.

I'm also aware that `code` change might break existing configuration of users.. So if someone has any opinion on how to add this feature, it would be great.

**Comment by dbrekelmans** [comment]
I'm running into the same exact issue with `MissingParameterTypeHint`. Would be very helpful to have two separate sniff codes.

**Comment by kukulich** [comment]
Waiting for https://github.com/slevomat/coding-standard/issues/353

**Comment by kukulich** [comment]
Will be implemented as a part of https://github.com/slevomat/coding-standard/issues/353
