### ISSUE TITLE
Sniff for reference spacing

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#610]
There seems to be no sniff for reference spacing (in parameters, in `use` or standalone).

I'd like to propose one for spacing _after_ reference, with configurable space following `&` (simple true/false for no/one-space should be enough).

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/1629c0be41b1b57f34b0f4d2a4a085063372fd7d
