### ISSUE TITLE
Sniff to forbid references

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#611]
References are often code smell, especially when used within functions/methods for parameters/returns.

I'd like to see a sniff that would (upon configuration) forbid references in specific scopes:
- in function/method signatures,
- in closure `use`s,
- in standalone context (i.e. `$a = &$b`).

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/d1947e22bfc11a111c424f866ace3909500e95d3
