### ISSUE TITLE
Version 5 is significantly slower than previous versions

### ISSUE THREAD

**Issue by marcospassos** [slevomat/coding-standard#612]
We've upgraded to version 5 and noticed a massive impact on performance.

By turning on and off the sniffs one by one we managed to track down the problem to the sniffs
`ReferenceThrowableOnly`, `FullyQualifiedGlobalConstants`, `FullyQualifiedGlobalFunctions` and `UnusedUses`. With these sniffs enabled, the time needed to run all checks increases from 30 seconds to more than 10 minutes, which is impractical.

I've compared the version 4.8.8 against 5.0.0, and there were a lot of changes. Any guess about what may have caused such an impact on performance?

**Comment by kukulich** [comment]
Difficult to guess without the code.

**Comment by amorimjuliana** [comment]
I have published a [repo](https://github.com/amorimjuliana/slevomat-issue612), with a single class that reproduces the problem.

Test with  all `SlevomatCodingStandard` rules:
- Version 4.8.0: 13.88 seconds
- Version 5.0.0: 41.95 seconds

Test with version 5.0.0, excluding the mentioned rules:
- `ReferenceThrowableOnly`: 40.84 seconds
- `FullyQualifiedGlobalConstants`: 35.91 seconds
- `FullyQualifiedGlobalFunctions`: 37.06 seconds
- `UnusedUses`: 34.95 seconds
- All four rules: 23.79 seconds

**Comment by Majkl578** [comment]
I didn't find anyany obvious problem when running the phpcs with `-vv`, the processing log is almost identical.

Here are Blackfire profiles for each run of:
```
vendor/bin/phpcs --standard=all.phpcs.xml --sniffs=SlevomatCodingStandard.Namespaces.FullyQualifiedGlobalFunctions
```
Ran on Windows, PHP 7.3 NTS.

Slevomat CS 4.8.7: https://blackfire.io/profiles/091c61ff-d6eb-482f-b2da-4f08966b3639/graph
Slevomat CS 5.0.0: https://blackfire.io/profiles/fe70c208-dbfe-49c2-bf59-51b5486bbfef/graph

The obvious problem is massive performance hit by calling File::findPrevious().

**Comment by kukulich** [comment]
Hmm, I guess it's caused by https://github.com/slevomat/coding-standard/commit/248bd37cab72cdd383600d165b61378ac655e2c2#diff-fc1ee625359b71f7fe46fd9dc33b8fd6R148

It looks I will have to implement some cache.

**Comment by kukulich** [comment]
Can you please try `dev-master`?

**Comment by amorimjuliana** [comment]
Way better! This version runs in 16.59 seconds.

We're looking forward to the new release :)

**Comment by marcospassos** [comment]
Thank you, @kukulich.
