### ISSUE TITLE
Return self instead of own class name

### ISSUE THREAD

**Issue by stephanvierkant** [slevomat/coding-standard#613]
I'm looking for a sniff that requires fluent setters to return `self` instead of their own class name.

Before:
```
class User
{
    public function setUsername(string $username) : User
    {
        $this->username = $username;
        
        return $this;
    }
}

```
After:
```
class User
{
    public function setUsername(string $username) : self
    {
        $this->username = $username;

        return $this;
    }
}

```

**Comment by kukulich** [comment]
@stephanvierkant you can try 
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/Classes/SelfMemberReferenceSniff.php

**Comment by stephanvierkant** [comment]
Does not work. See https://github.com/squizlabs/PHP_CodeSniffer/issues/2433
