### ISSUE TITLE
Suppress support for DisallowMixedTypeHintSniff

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#615]

**Comment by alcaeus** [comment]
Can be closed for the same reason as #614.

**Comment by kukulich** [comment]
@alcaeus I’m not sure how phpcs:disable work in phpdoc for methods.

**Comment by alcaeus** [comment]
You'll have to use `phpcs:disable` and `phpcs:enable`, `phpcs:ignore` does not work IIRC.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/f7b4e423f4a7c78fbb71e16da45b16a36a9812fc
