### ISSUE TITLE
TraitUseSpacing.IncorrectLinesCountAfterLastUse incorrect in classes with only one trait

### ISSUE THREAD

**Issue by robertfausk** [slevomat/coding-standard#616]
Given class ArticleId.php 
```PHP
<?php
declare(strict_types=1);

namespace App\Entity;

final class ArticleId
{
    use AggregateId;
}

```
throws "Expected 1 lines after last use statement, found 0.(SlevomatCodingStandard.Classes.TraitUseSpacing.IncorrectLinesCountAfterLastUse)" but shouldn't. Or am I wrong?

**Comment by kukulich** [comment]
See README.
