### ISSUE TITLE
ControlStructureSpacing with T_CASE/T_DEFAULT

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#619]
Hi,
I would like to have code like this:
```php
...
switch($asdf)
{
    case 'a:'
        return new A();

    case 'b':
        return new B();

    default:
        throw new InvalidArgumentException('...');
}
```

How should I configure the `SlevomatCodingStandard.ControlStructures.ControlStructureSpacing` sniff?
I actually get to this closest configuration:
```xml
    <rule ref="SlevomatCodingStandard.ControlStructures.ControlStructureSpacing">
        <properties>
            <property name="linesCountAroundControlStructure" type="int" value="1"/>
            <property name="linesCountAfterLastControlStructure" type="int" value="1"/>
            <property name="linesCountBeforeFirstControlStructure" type="int" value="0"/>
            <property name="tokensToCheck" type="array">
                <element value="T_CASE"/>
                <element value="T_DEFAULT"/>
            </property>
        </properties>
    </rule>
```
but it expects 1 line after `default:`, which is not intended for me.

Thanks for help.

**Comment by kukulich** [comment]
The sniff was not intented to check/fix `case` or `default` tokens. It should probably throw error when you use unsupported tokens...

**Comment by kukulich** [comment]
It may be improved by https://github.com/slevomat/coding-standard/commit/9f84eb7b0b50ab5ebce209cd24496fcde9998c58
