### ISSUE TITLE
Documentation of sniffs

### ISSUE THREAD

**Issue by o5** [slevomat/coding-standard#62]
Hello,

any plans to create documentation for these awesome sniffs? I mean documenation in standard format like [UnnecessaryStringConcatStandard](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Docs/Strings/UnnecessaryStringConcatStandard.xml) doc.

When I use this sniff in my `ruleset.xml` and run 

```
phpcs --standard=/etc/php/ruleset.xml --generator=HTML > coding-standards.html
```

documentation in HTML will be generated.
![screen shot 2016-10-19 at 16 48 33](https://cloud.githubusercontent.com/assets/218562/19523910/4d08165e-961c-11e6-917e-939559134398.png)

Thank you!

**Comment by ondrejmirtes** [comment]
Hello, I never heard about this format and I've been using PHP_CodeSniffer for over 5 years :) I'd rather spend time doing more impactful things but feel free to open a PR. Until then, people can refer to the README.
