### ISSUE TITLE
Useless parenthesis on casting array merge

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#621]
Hi,
I have this code
```php
$this->api->post('asdfg', (object)([
    'asdf' => $value,
] + $this->defaults($asdfg)));
```
https://3v4l.org/fWmWk

but I get error `Useless parentheses.`, which is not good. Without parenthesis I got php error: https://3v4l.org/QbLj3

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/b9df642bd8a9b9457b78e5b089bc68d2ca8e3df3
