### ISSUE TITLE
UnusedUses Removes Used Class

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#622]
Running slevomat code-standards 5.0.1

`SlevomatCodingStandard.Namespaces.UnusedUses` given the following file

```php
<?php

use Lang\Misc;

echo htmlentities(Misc::SKIP_TO_CONTENT);

if( $this->header ) { ?>
	<?php echo Misc::BACK_TO_TOP;
}
```

Marks the `use` as unused. If the `if` is removed however, it is not.  

Fairly strange behaviour.

**Comment by kukulich** [comment]
I’ll probably not fix this. I don’t think out sniffs should be used for templates.

**Comment by dg** [comment]
It also affects

```php
<?php

use Lang\Misc;

echo htmlentities(Misc::SKIP_TO_CONTENT);

?> <?php
```
