### ISSUE TITLE
TypeHints.TypeHintDeclaration and array of arrays

### ISSUE THREAD

**Issue by inglar** [slevomat/coding-standard#623]
Hello.
Can't find how to specify phpdoc for array of arrays parameter or return type to stop receiving errors **SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification**, **SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableParameterTypeHintSpecification**.
**array[]**, **array<array>** doesn't work. I have the latest 5.0.1 version.
```
/**
 * @return array[]
 */
public function cgetActionDataProvider(): array
{
    return [
        [],
    ];
}

/**
 * @dataProvider cgetActionDataProvider
 * @param array[] $query
 */
public function testCgetAction(array $query): void
{
}
```

As a temporary solution i use
@phpcsSuppress SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableParameterTypeHintSpecification
@phpcsSuppress SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification

Could someone advise something?

**Comment by kukulich** [comment]
Eg. `@return mixed[][]`
