### ISSUE TITLE
Fatal error: TokenIterator not found

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#632]
We are facing an issue after updating to 5.x here:

> PHP Fatal error:  Uncaught Error: Class 'PHPStan\PhpDocParser\Parser\TokenIterator' not found in /home/travis/build/spryker/spryker/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php:249

Locally this runs fine, but on travis this happens.

We have the same composer install there, working fine. And the same versions as expected:

  - Installing phpdocumentor/graphviz (1.0.4): Loading from cache
  - Installing squizlabs/php_codesniffer (3.4.0): Loading from cache
  - Installing phpstan/phpdoc-parser (0.3.1): Downloading (100%)
  - Installing slevomat/coding-standard (5.0.2): Downloading (100%)
  - Installing spryker/code-sniffer (dev-master eacf253): Downloading (100%)

The command is as always:

> vendor/bin/phpcs Bundles --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -p

**Comment by kukulich** [comment]
I'm sorry but I don't think there's error in our package. PHPCS has its own autoload so there's probably problem somewhere between PHPCS and your environment.
