### ISSUE TITLE
Split ControlStructureSpacingSniff or make it more configurable

### ISSUE THREAD

**Issue by grongor** [slevomat/coding-standard#633]
I would like to configure phpcs to check blank lines only between and after the control structures for cases like `if`, `foreach`, `while`, ... and to require blank line before jump statements `continue`, `return`, ... so that the code like this would be valid:

```php
$things = $this->getBlabla();
foreach ($things as $thing) {
    if ($thing === 1) {
        continue;
    }

    if ($thing === 2) {
        break;
    }

    if ($thing === 3) {
        $x = 1;

        continue;
    }

    break;
}
```

And this code would "autofix" to the previous one:
```php
$things = $this->getBlabla(); // there might or might not be a blank line before, we don't care
foreach ($things as $thing) {
    if ($thing === 1) {

        continue;
    }
    if ($thing === 2) {
        break;
    }
    if ($thing === 3) {
        $x = 1;
        continue;
    }
    break;
}
```

Would you consider accepting such changes if I implement them? Maybe even split the sniff into two (`if`s vs `continue`s)?

**Comment by kukulich** [comment]
@grongor How would you name the new sniffs? And what tokens will they support?

**Comment by grongor** [comment]
I think the two groups should be:
```
T_IF,
T_DO,
T_WHILE,
T_FOR,
T_FOREACH,
T_SWITCH,
T_TRY,
```

```
T_GOTO,
T_BREAK,
T_CONTINUE,
T_RETURN,
T_THROW,
T_YIELD,
T_YIELD_FROM,
```

And named maybe `ControlStructures` and `JumpStatements`?

**Comment by kukulich** [comment]
@grongor The first should be `BlockControlStructures` or something similar so I can release version 5.1.0 with the two new sniffs and with `ControlStructureSpacingSniff` marked as deprecated.

`BlockControlStructures` can probably only extend `ControlStructureSpacing` with different defaults and throwing exception for unsupported tokens.

So yes, I will definitely merge it :)

**Comment by grongor** [comment]
Ok thanks, I'll send PR soon ;-) thx

**Comment by kukulich** [comment]
@grongor Will you have time to send the PR? :)

**Comment by grongor** [comment]
@kukulich sorry, I had other priorities this month. I will look into it next week :)

**Comment by kukulich** [comment]
@grongor Understood :) Thanks.

**Comment by grongor** [comment]
@kukulich ok, done. So sorry for the delay - getting back from vacation was harder then I expected :joy: 

There are two new things:
- instead of "around" you specify "before" and "after"
- all line-count values can be -1 which causes the checks to be skipped
