### ISSUE TITLE
NewSniff: Useless return in switch statements

### ISSUE THREAD

**Issue by amaabdou** [slevomat/coding-standard#636]
I came across this case and seems might be useful to have it
```php
switch($var) {
  case 'A':
    return true

    break;
  case 'B':
    return true

    break;
}
```

**Comment by kukulich** [comment]
I think it’s already in 
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php

**Comment by amaabdou** [comment]
okayyyyy, did not know :D 

thanks @kukulich
