### ISSUE TITLE
Assigment to superglobals reported by UnusedVariableSniff

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [slevomat/coding-standard#638]
```
    protected function setUp() : void {
          $_GET = ['param' => 'pampam']; // unused locally, but used in other code
    }
```
May be add configuration option for this case (ignoreSuperglobals) ?

**Comment by kukulich** [comment]
You can ignore it with `phpcs:disable`

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/e7875e34997c7616ef83f67602d76d5309a3741d
