### ISSUE TITLE
Unused use in return type after space

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#641]
Hi,
I have this code
```php
namespace Abc;
use stdClass;
class Abcd
{
/**
 * @return array<string, stdClass>
 */
public function abc(): array
{}
}
```
and check gives me warning about unused use stdClass.
I think that @param and @var is ok with this.

When I remove space before class it is ok.
```php
/**
 * @return array<string,stdClass>
 */
```

**Comment by kukulich** [comment]
@CZechBoY What version do you use?

**Comment by CZechBoY** [comment]
Looks like I'm still on 4.7.2 :-/
