### ISSUE TITLE
Unused superglobal variable

### ISSUE THREAD

**Issue by CZechBoY** [slevomat/coding-standard#643]
Hi,
for this code
```php
$_ENV = $_GET = $_POST = [];
```
it gives me error `SlevomatCodingStandard.Variables.UnusedVariable.UnusedVariable`, but these are superglobal variables which can be used somewhere else...

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/e7875e34997c7616ef83f67602d76d5309a3741d
