### ISSUE TITLE
Make SlevomatCodingStandard.Functions.StaticClosure suppressable

### ISSUE THREAD

**Issue by vladyslavstartsev** [slevomat/coding-standard#647]
Sometimes `SlevomatCodingStandard.Functions.StaticClosure` rule breaks code because we have anonymous functions that are binded to $this in other class
For example
```php
<?php

declare(strict_types=1);

class A
{
    public function anon(): callable
    {
      // if you make this function static, it will break
        return function () {
            return 1;
        };
    }
}

class B
{
    public function bind(\Closure $a): void
    {
        $a->call($this);
    }
}

$a = new A();
$b = new B();
$b->bind($a->anon());
```

so, sometimes this sniff breaks the code

**Comment by kukulich** [comment]
@vladyslavstartsev You can use `phpcs:disable` and `phpcs:enable` comments.

**Comment by vladyslavstartsev** [comment]
@kukulich didn't know about it.

Works well, thanks!
