### ISSUE TITLE
DeclareStrictTypesSniff: Do not require spaces around equal sign

### ISSUE THREAD

**Issue by gergelypap** [slevomat/coding-standard#648]
Currently the strict_types declaration is required to have spaces around the `=` sign:
`declare(strict_types = 1);`

Official PHP documentation does not use spaces at all in any of the examples:
`declare(strict_types=1);`

See:
- https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict
- https://secure.php.net/manual/en/control-structures.declare.php

Let's stick to the official usage in DeclareStrictTypesSniff.

**Comment by roelofr** [comment]
For those who encounter a race condition between PSR-12 and the default config for the DeclareStrictTypesSniff, use this config:

```xml
<rule ref="SlevomatCodingStandard.TypeHints.DeclareStrictTypes">
    <properties>
      <property name="newlinesCountBetweenOpenTagAndDeclare" type="int" value="2" />
      <property name="spacesCountAroundEqualsSign" type="int" value="0" />
    </properties>
  </rule>
```
