### ISSUE TITLE
RequireCombinedAssignmentOperatorSniff

### ISSUE THREAD

**Issue by marmichalski** [slevomat/coding-standard#649]
This sniff introduces the following change, which is affecting the result:
```diff
-                    $g = $g / $this->ort[$m] / $this->H[$m][$m - 1];
+                    $g /= $this->ort[$m] / $this->H[$m][$m - 1];
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/80e61a068be41707af31996b52d2f7ea16b50022
