### ISSUE TITLE
UselessParenthesesSniff

### ISSUE THREAD

**Issue by marmichalski-zz** [slevomat/coding-standard#650]
This sniff introduces the following change, which is affecting the result:
```diff
-                    $error = ($y - $hX) ** 2;
+                    $error = $y - $hX ** 2;
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/244e6d3f89836fa0e60c7c2fadb4b639c8491f0e
