### ISSUE TITLE
@dataProvider, @throws, @test etc. are useful annotations

### ISSUE THREAD

**Issue by mr-feek** [slevomat/coding-standard#659]
I would like a way to whitelist useful annotations in the `TypeHintDeclaration` rule, like we had in version 4.*.

It is quite standard to use `@dataProvider` annotations in tests, `@throws` annotations in business logic, etc.

This is essentially reopening:
https://github.com/slevomat/coding-standard/issues/299
https://github.com/slevomat/coding-standard/issues/204 
https://github.com/slevomat/coding-standard/issues/108

`usefulAnnotations` was removed in v5, and I believe we should have a way to bring back this functionality. Why was it removed in the first place? If it was removed due to complexity, perhaps useless docblock sniff should be split away from `TypeHintDeclaration`

**Comment by kukulich** [comment]
See README.

**Comment by mr-feek** [comment]
Is the solution really to add `allAnnotationsAreUseful` to every docblock containing a dataProvider, etc?

There is no desire to allow whitelisting?

**Comment by kukulich** [comment]
Read the README again :)

**Comment by virgofx** [comment]
@kukulich I think a lot of us have the same question. It's not clear from the readme as functionality is now different but the same requirement applies --- not allowing all annotations -- only some specific ones. Can you explicitly clarify here to avoid future issues from being created regarding this?

**Comment by acornforth** [comment]
@kukulich I have been reading the readme, over and over again. And it's still not clear to me what the new approach should be now that 'usefulAnnotations` is removed as a config option. Every time i run the checker, many of my important @Route annotations are being removed from my symfony app.
How can i stop this from happening please ?
