### ISSUE TITLE
Uses of traits are not registered

### ISSUE THREAD

**Issue by meridius** [slevomat/coding-standard#66]
The `SlevomatCodingStandard.Namespaces.MultipleUsesPerLine` sniff does not register multiple uses of traits in class. Is that intentional?

This in combination with `SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` sniff gives false hope for secure removal of unused use.

Example:

```
<?php

namespace Project;

use Package\TPhotoGallery;
use Package\TSeoInfo;

class CompetitionEntity 
{
    use TSeoInfo, TPhotoGallery;
}
```

When both mentioned sniffs are enabled, the `UnusedUses` will report TPhotoGallery as unused use available for automatic removal. The `MultipleUsesPerLine` does not register anything.

**Comment by ondrejmirtes** [comment]
Hopefully fixed with https://github.com/slevomat/coding-standard/commit/78d094d20c9a6c8fc8633558fc25376fb88da972. Thanks for the report!
