### ISSUE TITLE
Unexpected behaviour when using phpcs:enable

### ISSUE THREAD

**Issue by davidkmenta** [slevomat/coding-standard#660]
I'm getting a weird error when I'm using partial ignoring.

Here is part of my code:

```
/**
 * @return iterable|BundleInterface[]
 */
public function registerBundles(): iterable
{
	// phpcs:disable Generic.PHP.ForbiddenFunctions
	$contents = require $this->getProjectDir() . '/config/bundles.php';
	// phpcs:enable

	foreach ($contents as $class => $envs) {
		if ($envs[$this->environment] ?? $envs['all'] ?? false) {
			yield new $class();
		}
	}
}
```

The error I'm getting:

`29 | ERROR | [x] Expected 1 lines before "foreach", found 0.`

If I use the `// phpcs:ignore Generic.PHP.ForbiddenFunctions` comment instead, everything is fine.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/a9e9fdde2cacf322b4f92a55ae26cc24b10542de
