### ISSUE TITLE
Fatal error on execution

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#664]
> PHP Fatal error:  Uncaught Error: Call to private method PHPStan\PhpDocParser\Parser\PhpDocParser::parseTagValue() from context 'SlevomatCodingStandard\Helpers\AnnotationHelper' in /.../vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php:250

This happens with normal inclusion. Please make sure it has the right dependencies, in this case the right phpstan one as require.

Manually downgrading to
"slevomat/coding-standard": "^4.0"
here works for our code sniffer ruleset.

**Comment by kukulich** [comment]
Duplicate to https://github.com/slevomat/coding-standard/issues/632
