### ISSUE TITLE
Endless Loop in EarlyExitSniff

### ISSUE THREAD

**Issue by Khartir** [slevomat/coding-standard#665]
There is an endless in the EarlyExitSniff when:

- using alternative syntax
- the statement contains PHP-tags
- there is also an else-block

The following test-script loops forever if tested:
```
<?php

if (1 === 1) :
?>
<?php
else:
endif;
```
Depending on settings an error is thrown instead:
`Undefined index: scope_condition in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php on line 387`

**Comment by kukulich** [comment]
Yes, we don't support alternative syntax.
