### ISSUE TITLE
Add option to ignore SlevomatCodingStandard.Functions.StaticClosure inside of static methods/closures?

### ISSUE THREAD

**Issue by TysonAndre** [slevomat/coding-standard#666]
e.g. 

```php
class X {
    public static function getClosure() {
        return function () {};  // should have a config option to not warn about this
    }
}
```

There's not as much benefit (except consistency) to make it an explicit `static function` when there's no `$this` - it's already within a static method (or another static closure)

**Comment by kukulich** [comment]
I like consistency so I’ve decided to not implement it.
