### ISSUE TITLE
Prevent generics syntax to throw TypeHintDeclaration errors

### ISSUE THREAD

**Issue by PeeHaa** [slevomat/coding-standard#673]
Consider the following code:

```php
/**
 * @return Promise<bool>
 */
public function exists(Key $key): Promise;
```

The generics syntax used here provides more info than can currently be provided by just the PHP return type declaration. However I still get:

> Method \HarmonyIO\Cache\Cache::exists() does not need documentation comment.
> (SlevomatCodingStandard.TypeHints.TypeHintDeclaration.UselessDocComment)

Is there some config I missed to make this work or is there some other way I can make this work?

**Comment by kukulich** [comment]
@PeeHaa what version do you use?

**Comment by PeeHaa** [comment]
Latest: 5.0.4

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/e992d1a1de640fc4dcb45d825506be1840ce7f74

**Comment by PeeHaa** [comment]
Awesome! Thanks for the fast turnaround ❤️
