### ISSUE TITLE
UselessParameterDefaultValue does not take variadics in account

### ISSUE THREAD

**Issue by ostrolucky** [slevomat/coding-standard#683]
```php
public function foo(?stdClass $class = null, int ...$someOtherStuff): void
{        
}
```

>  ERROR | [x] Useless default value of parameter $class.

This is invalid, because specifying second parameter is optional too.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/376198f93cdee0bdcbfbdcd52b40bbf5ef1da57b
