### ISSUE TITLE
SlevomatCodingStandard.Arrays.TrailingArrayComma doesn't require short array syntax

### ISSUE THREAD

**Issue by BHSPitMonkey** [slevomat/coding-standard#684]
**From the README:**

> SlevomatCodingStandard.Arrays.TrailingArrayComma
>
> Commas after last element in an array make adding a new element easier and result in a cleaner versioning diff.
>
> This sniff enforces trailing commas in multi-line arrays **and requires short array syntax []**.

**Actual behavior:**

The sniff does not require the use of short array syntax at all, and the trailing comma rule is _only_ enforced when the input array uses long array syntax.

**Comment by kukulich** [comment]
No, the sniff works only with short arrays, see https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Arrays/TrailingArrayCommaSniff.php#L22

**Comment by BHSPitMonkey** [comment]
The README claims that this sniff requires the use of short array syntax, but the implementation does not require the use of short array syntax. Either the documentation or the implementation is correct, but not both.
