### ISSUE TITLE
Undefined index in UselessInheritDocCommentSniff when TokenHelper::findNext return null

### ISSUE THREAD

**Issue by paul-thebaud** [slevomat/coding-standard#690]
Hello,

I'm having an issue when using this package : `nunomaduro/phpinsights`.

The class of your package `UselessInheritDocCommentSniff` does not check that `$docCommentOwnerPointer` is not null at line 56. But as mentioned in the `TokenHelper` documentation, the return value of `findNext` is integer or null.

I suggest to add the following comparaison `$docCommentOwnerPointer !== null` at line 57 of `UselessInheritDocCommentSniff`.

**Comment by kukulich** [comment]
@paul-thebaud please post a code that throws this error

**Comment by paul-thebaud** [comment]
@kukulich Here is the code which causes the bug (I hide the class name and others names since you wont need them):
```php
<?php

namespace Some\Name\Here;

use Illuminate\Database\Eloquent\Relations\Pivot;

class SomeClass extends Pivot
{
    /**
     * {@inheritDoc}
     */
    protected $casts = [
        '****' => 'array'
    ];

    /**
     * {@inheritDoc}
     */
    protected $fillable = [
        '****'
    ];
}
```

I tested, it seems to be the `{@inheritDoc}` on properties which are causing the error. The `Pivot` class is from the Laravel framework, which is in version 5.8.17 on our project.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/14003cf77628b3f00208c0c32b2fc9c875b70733

**Comment by brunogaspar** [comment]
@kukulich Any chance to create a new tag for the latest fixes that has this one too?

Thanks!
