### ISSUE TITLE
Composer installation conflict

### ISSUE THREAD

**Issue by jrfnl** [slevomat/coding-standard#693]
There is an inconsistency/discrepancy in the `composer.json` file.

In the `require` section it lists `"php": "^7.1",`, but when running `composer install --no-dev` on PHP 7.1.x, it will not install as Composer will still look at `require-dev` and PHPUnit 8 has a minimum PHP requirement of PHP 7.2.

```
Your requirements could not be resolved to an installable set of packages.

Problem 1
  - Installation request for phpunit/phpunit 8.1.4 -> satisfiable by phpunit/phpunit[8.1.4].
  - phpunit/phpunit 8.1.4 requires php ^7.2 -> your PHP version (7.1.25) does not satisfy that requirement.
  
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/fdbac4fa5b79c182b285e26f5308863236fc06c2
