### ISSUE TITLE
Installing globally?

### ISSUE THREAD

**Issue by james2doyle** [slevomat/coding-standard#70]
Is it possible to install this package globally and have it work via the command line when not in a folder?

For example, I have the PHPCS sublime plugin which runs on save. I want to use this over the default PSR2 ruleset. But I believe I would need to install this globally to get it to work properly.

Any thoughts?

**Comment by ondrejmirtes** [comment]
I think it's not a problem. You have to install globally two things:

1) PHP_CodeSniffer
2) This package

You then have to provide the path to `SlevomatCodingStandard/ruleset.xml` when running phpcs.
