### ISSUE TITLE
New sniffs proposal

### ISSUE THREAD

**Issue by grongor** [slevomat/coding-standard#701]
We have some custom sniffs in our company's CS and I think more people could benefit from them if we ported them to your repository. I'd be willing to do such migration myself if it meant only slight changes.

So if you are interested, please take a look at our sniffs at https://github.com/cdn77/coding-standard/tree/master/src/Cdn77/Sniffs (ignore ControlStructures - they are just duplicated from your repository).

**Comment by kukulich** [comment]
@grongor It would be superb :) Please open special PR for each sniff :)

I only don't know why you have `LineLengthSniff`. There's sniff in PHPCS itself.

**Comment by grongor** [comment]
Alright, I will when I find some spare time.

I'm not sure either but I know that there was some reason :D I think that it didn't handle all the situations correctly or something like that ... I will look into it.

Same goes for OperatorSpacingSniff, which has multiple implementations and all are flawed in some way. Mine for example also handles unary operators like `T_INC` and `T_DEC`.

**Comment by kukulich** [comment]
@grongor Understood, we have also our own `TrailingArrayCommaSniff` :) We have also better environment for writing tests than PHPCS itself :)

I'll try to release version 5.1. asap, so all of your PR will be part of 5.2.

**Comment by jrfnl** [comment]
> Mine for example also handles unary operators like T_INC and T_DEC.

PHPCS has a native sniff for spacing of unary operators since PHPCS 3.4.0 `Generic.WhiteSpace.IncrementDecrementSpacing`, so this may not be needed anymore.

**Comment by grongor** [comment]
@jrfnl yeah, indeed the `T_INC` and `T_DEC` are handled by this sniff already... but I'm still missing these features:
- handling of unary `T_MINUS`, eg. `$a = - $b` -> `$a = -$b`
- handling of `T_STRING_CONCAT` and `T_INSTANCEOF` (Squiz sniff doesn't allow me to add these types)

Would you propose a better solution then handling all the operators in a single sniff as I'm doing now?

**Comment by jrfnl** [comment]
> handling of unary T_MINUS, eg. $a = - $b -> $a = -$b

The `Squiz.Formatting.OperatorBracket.SpacingAfterMinus` comes close as it triggers on `$b = - 10;`, so I think that sniff would only need a little adjustent to also handle `$a = - $b`.

> handling of T_STRING_CONCAT and T_INSTANCEOF (Squiz sniff doesn't allow me to add these types)

If you want these to be surrounded by (at least) one space on each side, try the `PSR12.Operators.OperatorSpacing` sniff which does just that.

Alternatively, if you want exactly one space, you could simply overload the `register()` method of the `Squiz.WhiteSpace.OperatorSpacing` sniff, no need for additional logic.

See here for an example which does the same: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php

Also have a look at the `Squiz.Strings.ConcatenationSpacing` sniff and its configuration options: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#squizstringsconcatenationspacing

**Comment by kukulich** [comment]
I agree it's better to have more smaller sniffs.

**Comment by kukulich** [comment]
@grongor Do you still plan this? :)

**Comment by grongor** [comment]
Oh man, totally forgot about this one. Let me go over it again next week.

**Comment by kukulich** [comment]
@grongor Thank you very much for your hard work! I suppose we are done here :)

**Comment by grongor** [comment]
Yep, I guess so :) Thanks for fast merging!
