### ISSUE TITLE
SlevomatCodingStandard.Namespaces.UnusedUses false positive on complex callback phpdoc

### ISSUE THREAD

**Issue by mabar** [slevomat/coding-standard#704]
https://travis-ci.org/nette/forms/jobs/538663894#L605
https://github.com/nette/forms/blob/d9fc6d6/src/Forms/Form.php#L84

Related to nette/forms#223

**Comment by adaamz** [comment]
@mabar nette coding standard uses old slevomat/cs v4, this is fixed in slevomat/cs v5

**Comment by mabar** [comment]
Well, thx
