### ISSUE TITLE
UselessSemicolonSniff.php undefined index

### ISSUE THREAD

**Issue by rjsandim** [slevomat/coding-standard#706]
Hi, I am running phpinsights thats uses coding-standard and I am getting undefined index. 

![image](https://user-images.githubusercontent.com/4038979/58756156-19f09180-84c9-11e9-8d45-a1997003bc8c.png)

Could someone help me?

**Comment by rjsandim** [comment]
I ran it with -v (verbose mode) and found that this code crashes when we have on our code a double ";;".

I delete and let just one and the insights got back working. 

I don't know it you want to make some adjustment to not let the code crashes in this case, otherwise I think the issue could be closed. 

What do you think?

**Comment by kukulich** [comment]
@rjsandim Could you please post the code that throws this error?

**Comment by kukulich** [comment]
Should be fixed in https://github.com/slevomat/coding-standard/commit/945d381ea4d14d64cc9f87cfe593bda28472c998
