### ISSUE TITLE
How to write var comments with MissingVariable sniff / bug?

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#708]
Exploring current master, found this issue:

```php
/** @var stdClass $x */
$y = $x->doSth();
```

It says:

> Missing variable $contract before or after the documentation comment

Is it bug or am I not annotating properly? Thanks

**Comment by kukulich** [comment]
@simPod It expects this type of doccomment before/after assigning to a variable.

**Comment by simPod** [comment]
Oh, smoooooth! 🚀 Thanks!
