### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by novjan** [slevomat/coding-standard#71]
Please can you create full documentaion for all sniffs?

**Comment by ondrejmirtes** [comment]
What exactly do you miss in the readme?

**Comment by novjan** [comment]
Ouch , I was searchin with Sniff in name ...

So missing is only this :)
- AssignmentInCondition

I know this Sniff is easy, but ....

**Comment by kukulich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dokumentace k novým sniffům do README](https://trello.com/c/UEGIpmiU/3-dokumentace-k-novym-sniffum-do-readme)

**Comment by ondrejmirtes** [comment]
AssignmentInCondition is now documented.
