### ISSUE TITLE
Sniff proposal: Spacing after type cast

### ISSUE THREAD

**Issue by Stadly** [slevomat/coding-standard#711]
Enforce a configurable number of spaces between type (e.g. `(bool)` or `(int)`) and whatever is being converted.

``` php
(int)$a;     // Ok when sniff is configured to 0 spaces.
(string) 1;  // Ok when sniff is configured to 1 space.
```

**Comment by kukulich** [comment]
There are sniffs for this directly in PHPCS.

**Comment by Stadly** [comment]
Oh, sorry! Thanks :)
