### ISSUE TITLE
Inherited parameter annotation

### ISSUE THREAD

**Issue by Stadly** [slevomat/coding-standard#712]
Combining [`TypeHints.TypeHintDeclaration`](https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintstypehintdeclaration-) and [`Commenting.UselessInheritDocComment`](https://github.com/slevomat/coding-standard#slevomatcodingstandardcommentinguselessinheritdoccomment-) does not work well when a parameter cannot be typehinted.

The following code generates the error `Method RequestFactory::createRequest() does not have parameter type hint nor @param annotation for its parameter $uri.`, but actually the `@param` annotation exists - through [implicit inheritance](https://github.com/slevomat/coding-standard/issues/399).

```php
interface RequestFactoryInterface
{
    /**
     * Create a new request.
     *
     * @param string $method The HTTP method associated with the request.
     * @param UriInterface|string $uri The URI associated with the request. If
     *     the value is a string, the factory MUST create a UriInterface
     *     instance based on it.
     *
     * @return RequestInterface
     */
    public function createRequest(string $method, $uri): RequestInterface;
}


final class RequestFactory implements RequestFactoryInterface
{
    public function createRequest(string $method, $uri): RequestInterface
    {
        // ...
    }
}
```

**Comment by kukulich** [comment]
It can be solved when you copy the doccomment to the `RequestFactory` class. PHPCS works in one-file scope, there's no other option.
