### ISSUE TITLE
BlockControlStructureSpacing seems to be missing when installed from composer

### ISSUE THREAD

**Issue by jonnylink** [slevomat/coding-standard#714]
Possible (newbie to this package), but unlikely that I've done something wrong. 
```
   "require-dev": {
       ...
        "slevomat/coding-standard": "^5.0"
    },
```
Got a bunch of the rules all set.
```
<?xml version="1.0"?>
<ruleset name="Acme">
    <config name="installed_paths" value="vendor/slevomat/coding-standard/SlevomatCodingStandard"/>
    ...
    <!-- no dead code -->
    <rule ref="SlevomatCodingStandard.Namespaces.UnusedUses"/>
    <rule ref="SlevomatCodingStandard.Classes.UnusedPrivateElements"/>
    <rule ref="SlevomatCodingStandard.Functions.UnusedInheritedVariablePassedToClosure"/>
    <rule ref="SlevomatCodingStandard.Functions.UnusedParameter"/>
    <rule ref="SlevomatCodingStandard.Functions.UselessParameterDefaultValue"/>
    <rule ref="SlevomatCodingStandard.Variables.UnusedVariable"/>
    <rule ref="SlevomatCodingStandard.Variables.UselessVariable"/>

    <!--formatting -->
    <rule ref="SlevomatCodingStandard.ControlStructures.BlockControlStructureSpacing"/>
</ruleset>
```

On that last rule I get the error: 

> phpcs: Referenced sniff "SlevomatCodingStandard.ControlStructures.BlockControlStructureSpacing" does not exist

When I look in the vendor folder I'm not seeing the file, but I do see that it's there when I look in github.
<img width="252" alt="Screen Shot 2019-06-18 at 15 59 27" src="https://user-images.githubusercontent.com/20388240/59715730-80bcbd00-91e2-11e9-8497-2a45f28a427d.png">

**Comment by kukulich** [comment]
The sniff exists only in current master. `ControlStructureSpacingSniff` is the ancestor.

**Comment by jonnylink** [comment]
Sorry, so are you saying the docs are ahead of the current version installed by composer then?

Thanks for the work on this!

**Comment by jonnylink** [comment]
Seems like that is the case. That's a bit confusing. I've never seen it where master is anything but the current version. Usually there's a release or dev branch for the future stuff. 

You guys do you, but I have trouble imagining the value of landing on a docs page for a future version.
