### ISSUE TITLE
Disallow assigning multiple variables on the same line

### ISSUE THREAD

**Issue by ondrejmirtes** [slevomat/coding-standard#718]
```php
$name = $phone = $email = null;
```

**Comment by Hornet-Wing** [comment]
Doesn't `Squiz.PHP.DisallowMultipleAssignments` (included in CS by default) cover this?

**Comment by kukulich** [comment]
It looks it could be used.

**Comment by kukulich** [comment]
Yes, `Squiz.PHP.DisallowMultipleAssignments` looks good.
