### ISSUE TITLE
Publishing helpers as separate package?

### ISSUE THREAD

**Issue by aboks** [slevomat/coding-standard#719]
Thank you for creating such a great collection of helpers for handling PHP_CodeSniffer's internal representation. I think these can really make life easier for most sniff authors, even if they don't use the rest of this coding standard. Of course it would be possible to use the helpers in another standard by requiring `slevomat/coding-standard`, but requiring the entire standard feels a bit like overkill. How would you feel about releasing the helpers as a separate package, so that they can be reused in other sniffs more easily?

**Comment by kukulich** [comment]
I'm sorry I don't want to release helpers as a separate package because it will only make the development harder for me.

**Comment by aboks** [comment]
No problem, that sounds fair. We'll just keep using the helpers by requiring `slevomat/coding-standard` then. Keep up the good work!
