### ISSUE TITLE
Sniff summary

### ISSUE THREAD

**Issue by szepeviktor** [slevomat/coding-standard#720]
Would you welcome a PR with a rule.xml containing all the sniffs categorized as in the README?

**Comment by szepeviktor** [comment]
Something like

`grep '^### \|^#### SlevomatCodingStandard' README.md | cut -d" " -f2`

**Comment by kukulich** [comment]
I'm sorry I don't see any reason for it.

**Comment by szepeviktor** [comment]
Okay.

For googlers: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/phpcs-slevomat.xml
