### ISSUE TITLE
RequireYodaComparison doesn't switch var and function call

### ISSUE THREAD

**Issue by pento** [slevomat/coding-standard#723]
Given this example, I would expect the `SlevomatCodingStandard.ControlStructures.RequireYodaComparison` rule to switch `$foo` and `bar()`, assuming the intent of Yoda Comparisons is to prevent accidental assignment.

```php
<?php

if ( $foo === bar() ) {
	echo 'baz';
}
```

Unfortunately, it doesn't do that.

Would it be possible to change that behaviour, or add an option in the style of PHP-CS-Fixer's [`always_move_variable`](https://mlocati.github.io/php-cs-fixer-configurator/#version:2.15|fixer:yoda_style) option?

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/21719768332fd764ae05c13fc15fbcef836fd775
