### ISSUE TITLE
Using Param annotation inside method crashes sniff

### ISSUE THREAD

**Issue by olivernybroe** [slevomat/coding-standard#732]
I am not sure if this is actually a bug or more categories as a coding mistake, but I'll post it here for you guys to decide.

If you add a `@param` docblock inside a method it crashes, as it thinks this is added to the docblock of the method.

```
<?php

class MyClass
{
    private function method(array $categories): void
    {
        /** @param Category[] $categories */
    }
}
```

**Comment by kukulich** [comment]
It's a coding mistake :)

**Comment by andreasschroth** [comment]
I totally agree with @kukulich that it's a coding mistake, but on the other side... Should the analyser process really crash in such a case? I assume not. I would expect it to always run through even with bad annotations.
