### ISSUE TITLE
Internal Exception for UseStatement

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#733]
```
An error occurred during processing; checking has been
   |       | aborted. The error message was: Undefined index:
   |       | scope_closer in
   |       | /.../vendor/slevomat/codingstandard/SlevomatCodingStandard/Helpers/UseStatementHelper.php
   |       | on line 207 (Internal.Exception)
```

"version": "5.0.4",

**Comment by kukulich** [comment]
It's not possible to fix anything without the code that throws this error.

**Comment by dereuromark** [comment]
I would just ask for a bit more defensive coding in general. Checking on the existence of those array keys would prevent those fatal internal errors.
For the specific code, I can take a look. But this was more a thing I saw happening also in the past a few times.

**Comment by kukulich** [comment]
@dereuromark This array key should be there always in this specific line.

**Comment by dereuromark** [comment]
Interesting. Well for some reason it isn't.
Well, you can close this ticket then if you do not want to change the key check.

**Comment by kukulich** [comment]
I cannot do nothing better that throw internal error.

Does it throw checker or fixer?

**Comment by dereuromark** [comment]
I will close then, sry that I couldn't provide more details.
