### ISSUE TITLE
Idea: forbid duplicating $this for closures

### ISSUE THREAD

**Issue by alcaeus** [slevomat/coding-standard#734]
This came up while working on a pre-PHP 5.4 codebase. Before PHP 5.4, `$this` couldn't be used in closures, which caused people to write things like:
```php
$that = $this;
function () use ($that) {
    $that;
}
```

It would be nice to have a sniff that
* recognises duplications of `$this` (without using `clone`)
* forbids using said duplications in closures
* optionally removes the usage in closures

**Comment by gmponos** [comment]
This is a great idea.. never the less I am not sure if this could be implemented on a codesniffer tool.. not sure if the maintainers can make it happen.

Maybe it is more suitable for a static analysis tool like phpstan and more specifically on the phpstan-strict-rules repo.

**Comment by alcaeus** [comment]
> Maybe it is more suitable for a static analysis tool like phpstan and more specifically on the phpstan-strict-rules repo.

That's true. @ondrejmirtes what do you think?

**Comment by ondrejmirtes** [comment]
Yes, this would work and would be easy to implement as PHPStan rule. `$this` has `ThisType` and it's copied when you assign `$this` to something else, so it would be sufficient to check if the ClosureUse variable has `ThisType` as its type...

**Comment by kukulich** [comment]
@ondrejmirtes Do you already have the rule? :)

**Comment by ondrejmirtes** [comment]
Here it is :) https://github.com/phpstan/phpstan-src/commit/5e8127d632fbae9cdb045bab1771ee535c66c21e

it will be in PHPStan 0.12.6 when you enable bleeding edge. I might enable it for the next major version for everyone, or it will be part of strict-rules, not sure yet.
