### ISSUE TITLE
`@file` header should not be validated as an use statement

### ISSUE THREAD

**Issue by mxr576** [slevomat/coding-standard#735]
![image](https://user-images.githubusercontent.com/1755573/63597159-1b5bc280-c5bd-11e9-8c3f-8380f1578db1.png)

**Comment by mmoll** [comment]
Have a look into the `ignoredAnnotationNames` option of this Sniff.

**Comment by mxr576** [comment]
Thanks for the tip, I have just found it myself as well. :)  Hopefully that solves this but probably `@file` should be a part of the default blacklisted annotation names.
