### ISSUE TITLE
FullyQualifiedClassNameInAnnotation doesn't understand generic/template types

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#736]
If we use generic/template types like `@param T $foo` as supported by [psalm](https://psalm.dev/docs/annotating_code/templated_annotations/) and [phpstan](https://arnaud.le-blanc.net/post/phpstan-generics.html) `FullyQualifiedClassNameInAnnotation` sniff throws error like
```
Class name T in @var should be referenced via a fully qualified name
```

I guess fixing this would require the sniff to check for presence of tag like `@template T` (and other variants) in function/method or class' docblock.

**Comment by ADmad** [comment]
If multiple prominent static analysers support the annotation like `@template`, I don't why the sniff can't be updated to deal with it properly (unless there are technical limitations preventing it).

Often people uses multiple static analysis tools for their codebase and using tool-specific tags would be unnecessary duplication when there's already a commonly supported tag.

IDEs are irrelevant to this discussion, not everyone uses an IDE.

**Comment by ondrejmirtes** [comment]
We haven’t even came to the conclusion that this is the syntax we want to use going forward, so the vendor prefixes are a safe bet for now. See: https://github.com/phpstan/phpstan/issues/2527

This is still a very young area so Slevomat CS shouldn’t spend time on implementing something that might be considered deprecated by the community in a few months.

**Comment by ADmad** [comment]
Based on the 2 sourced I linked in my original post, I thought the tag name was generally agreed upon. But I guess it's not, so Slevomat CS supporting it can wait until there's a consensus again on the name :slightly_smiling_face:.
