### ISSUE TITLE
Request: ignore return type hint errors for closures

### ISSUE THREAD

**Issue by devfrey** [slevomat/coding-standard#742]
I want to suppress "missing return type hint" errors for **closures**  (`SlevomatCodingStandard.TypeHints.TypeHintDeclaration`). Unfortunately it uses the same error code as the regular method return type hints. Would it be possible to get a different error code for closures? I'd be happy to send in a PR.

**Comment by kukulich** [comment]
It does not make sense to me so I'll not implemented it (or accept PR).
