### ISSUE TITLE
AlphabeticallySortedUses: ignore case for order

### ISSUE THREAD

**Issue by boobaa** [slevomat/coding-standard#747]
PhpStorm adds `use` statements alphabetically, but in a case insensitive manner:
```
use Foo\anything;
use Foo\Everything;
use Foo\nothing;
use Foo\Something;
```

Current behavior: AlphabeticallySortedUses reorders this in a case sensitive manner:
```
use Foo\Everything;
use Foo\Something;
use Foo\anything;
use Foo\nothing;
```

Expected behavior: accept the order PhpStorm uses OOTB (or make this configurable).

**Comment by kukulich** [comment]
See README.
