### ISSUE TITLE
New Release Timeline

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#750]
I've been patiently awaiting a release to come out with my two accepted PR's, #656 and #657 since April 4th - any update on when there might be a tagged release?

**Comment by carusogabriel** [comment]
We at https://github.com/doctrine/coding-standard are also interesting on those ones :)

**Comment by shmax** [comment]
Not to pile on, but [webonyx/graphql-php](https://github.com/webonyx/graphql-php) could make good use of the new array shapes support. May I ask why there hasn't been a new release since March?

**Comment by kukulich** [comment]
Nobody paid me for the release.

**Comment by donatj** [comment]
I'd be happy to help maintain this, if time/manpower is the issue.

**Comment by shmax** [comment]
> Nobody paid me for the release.

I'll call your bluff. Produce a donation link and I will produce a donation. 😄
