### ISSUE TITLE
MismatchingCaseSensitivity collision with documented array keys

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#752]
```php
use ASN;

...

/**
 * @param array{
 *     asn: int
 *     } $x
 */
public function a(array $x) : void
{
}
```

SlevomatCodingStandard.Namespaces.UnusedUses.MismatchingCaseSensitivity on `asn: int`

> Case of reference name "asn" and use statement "ASN" does not match

Even though there's no relation between those.

I have `<property name="searchAnnotations" value="true"/>` set.  

Related to https://github.com/slevomat/coding-standard/issues/746.

**Comment by kukulich** [comment]
I don't think it can be solved. So you should disable this specific error.
