### ISSUE TITLE
Suggestion: Create a 5.0.x release supporting php 7.1 with maximum version of phpstan/phpdoc-parser

### ISSUE THREAD

**Issue by TysonAndre** [slevomat/coding-standard#759]
I see that the master branch already specifies an explicit target version of 0.3.4. A lower one might work for a 5.0.x release

Some libraries will still support php 7.1 or have CI running against 7.1, so having a release that continues to work in 7.1 would be convenient. 

It's possible to work around this by explicitly specifying a version of phpdoc-parser, but inconvenient to do so. It's possible to ignore these, it affects a small and the rest of the checks run successfully, so this is a low priority.

The bug in question was fixed in master, but that requires php 7.2+

```xml
    <error line="1" column="1" source="Internal.Exception" severity="5" fixable="0">An error occurred during processing; checking has been aborted. The error message was: Undefined property: PHPStan\
PhpDocParser\Ast\Type\ArrayShapeNode::$name in /path/to/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php on line 167</error>
```

**Comment by kukulich** [comment]
I've just enabled PHP 7.1 in master again. It was easier than expected :)
