### ISSUE TITLE
Namespaces.ReferenceUsedNamesOnly results in conflicting classes

### ISSUE THREAD

**Issue by holtkamp** [slevomat/coding-standard#762]
When using [this sniff](https://github.com/slevomat/coding-standard/#slevomatcodingstandardnamespacesreferenceusednamesonly-):

```xml
<rule ref="SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly"/>
```

a situation like:

```php
namespace A;

class Exception {

}

namespace A\B;

class Exception extends \A\Exception {

}
```

Results in a situation where class names conflict:

```php
namespace A\B;

use A\Exception;

class Exception extends Exception {

}
```

Is this "expected behavior" or a bug? I think in this case the "fix" should be skipped.

**Comment by kukulich** [comment]
See README. The sniff has a lot of options.

**Comment by holtkamp** [comment]
@kukulich thanks for the response, I noticed the [options in the documentation](https://github.com/slevomat/coding-standard/#slevomatcodingstandardnamespacesreferenceusednamesonly-), but "by default" a fix should not break anything, right? 

Will dive into the default values and come up with a PR for the documentation to mention these default settings.
