### ISSUE TITLE
Choose only the rules I'm interested in

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#763]
Hello,

Instead of doing this:

<rule ref="vendor/slevomat/coding-standard/SlevomatCodingStandard/ruleset.xml">
	<exclude name="SlevomatCodingStandard...."/>
	<exclude name="SlevomatCodingStandard...."/>
	<exclude name="SlevomatCodingStandard...."/>
	<exclude name="SlevomatCodingStandard...."/>
	<exclude name="SlevomatCodingStandard...."/>
</rule>

For every single rule I'm not interested in,

Is it possible to explicitly put the rules I am actually interested in, and all others will be disabled by default?

Thank you very much.

**Comment by kukulich** [comment]
See README.
