### ISSUE TITLE
RequireCombinedAssignmentOperator does not respects priority of the operator

### ISSUE THREAD

**Issue by czjvic** [slevomat/coding-standard#767]
Before SlevomatCodingStandard.Operators.RequireCombinedAssignmentOperator
```php
$a = 10;
$a = $a / 2 * 3;
var_dump($a); // Result 15
```
After autofix SlevomatCodingStandard.Operators.RequireCombinedAssignmentOperator
```php
$a = 10;
$a /= 2 * 3;
var_dump($a); // Result 1.666
```

**Comment by kukulich** [comment]
@czjvic Could you try `dev-master` please? I think this is already fixed.

**Comment by czjvic** [comment]
Great. It's working. You are right. It's already fixed in master.
