### ISSUE TITLE
Class alias used in a {@see} annotation is considered unused

### ISSUE THREAD

**Issue by morozov** [slevomat/coding-standard#770]
Consider the following code example:
```php
<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Driver;

use Doctrine\DBAL\ColumnCase;

/**
 * {@see ColumnCase}
 */
abstract class AbstractDB2Driver
{
}
```

[phpDoc](https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.see.pkg.html) doesn't tell whether the element name following the annotation should be fully qualified or not but by the example of `@var` and `@param` we may assume that aliases should be supported. Also, PhpStorm properly recognizes class aliases in `{@see}`.

However, the coding standard reports this example as containing an error:
```
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------
 7 | ERROR | [x] Type Doctrine\DBAL\ColumnCase is not used in this file.
   |       |     (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
------------------------------------------------------------------------------------------------
```

**Comment by kukulich** [comment]
`{@see ColumnCase}` is not supported because https://github.com/phpstan/phpdoc-parser does not support it. You can use `@see ColumnCase`

**Comment by morozov** [comment]
@kukulich the use case is to use this annotation as part of a [sentence](https://github.com/doctrine/dbal/blob/436f2f6c943937abe8544505630e76be4c468ae1/lib/Doctrine/DBAL/Driver/AbstractDB2Driver.php#L15) like:
```php
/**
 * Abstract base implementation of the {@see Doctrine\DBAL\Driver} interface for IBM DB2 based drivers.
 */
```
We have to use an FQN in this case since otherwise, the standard would flag the import as unused.

**Comment by kukulich** [comment]
I understand what you want but I don't to write another phpDoc parser.
