### ISSUE TITLE
Disable BlockControlStructureSpacing before structures

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#773]
As you [pointed out](https://github.com/doctrine/coding-standard/pull/137#issuecomment-558961400), BlockControlStructureSpacing sniff enforces spaces after but also before structures. 

Is there a way to disable the "before" part of it? I only found `linesCountBeforeControlStructure` which enforces concrete amount of spaces.

**Comment by kukulich** [comment]
@simPod You have to disable specific error code: https://github.com/doctrine/coding-standard/blob/master/lib/Doctrine/ruleset.xml#L357

**Comment by simPod** [comment]
Got it, thanks!
