### ISSUE TITLE
ReferenceThrowableOnlySniff is extremely slow

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#777]
I had reported a bug - https://github.com/squizlabs/PHP_CodeSniffer/issues/2723 - about PHPCS hanging on a huge file, but eventually I realized that the problem is in ReferenceThrowableOnlySniff.

> The sniffer "SlevomatCodingStandard\Sniffs\Exceptions\ReferenceThrowableOnlySniff" seems to be the problem.
> 
> In that last part where it was hanging for me, it appears that several things are processed, but every time it hits "ReferenceThrowableOnlySniff", it hangs for ~30 seconds or so.
> Once I removed it, the file took the expected time.

**Comment by kukulich** [comment]
@ghnp5 I'm not able to fix it without the code.

**Comment by kukulich** [comment]
No response.
