### ISSUE TITLE
RequireShortTernaryOperatorSniff gets in an infinite loop with PHP templates

### ISSUE THREAD

**Issue by kanduvisla** [slevomat/coding-standard#780]
`SlevomatCodingStandard\Sniffs\ControlStructures\RequireShortTernaryOperatorSniff` gets in an infinite loop when confronted with inline PHP in a template file. The following example will trigger the loop:

```
<?php /** @var \Vendor\Module\Example $example */ ?>
<script type="text/javascript">
    let foo = {
        bar: <?php echo $example->isBarTrue() ? 'true' : 'false' ?>
    }
</script>
```

**Comment by kukulich** [comment]
Yes, our sniff are not good for templates.
