### ISSUE TITLE
Feature request: Enforce arrow functions where feasible

### ISSUE THREAD

**Issue by WyriHaximus** [slevomat/coding-standard#781]
There already is a `SlevomatCodingStandard.Functions.DisallowArrowFunction` but would love to see a counter part of that rule that forces closures to use arrow functions where it is feasible.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/d26de941cb2a1832194b4fb16ff32c42c23d3176

**Comment by WyriHaximus** [comment]
Thanks 👍 ❤️!
