### ISSUE TITLE
Make FullyQualifiedClassNameInAnnotationSniff aware of "class-string" the

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#787]
Popular static analyzers like psalm, and phpstan allow using special type `class-string` as var type. It would be great if  `FullyQualifiedClassNameInAnnotationSniff` would be made aware of it and not generate an error for it. That would allow one to just user `@var class-string $foo` instead of pslam/phpstan prefixed var annotations.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/issues/736#issuecomment-547500490

**Comment by ADmad** [comment]
I was hoping handling `class-string` would be simpler than supporting templates/generics, given that it's a fixed string, hence I opened a separate issue :).

**Comment by kukulich** [comment]
@ADmad Could you please post code that throws you an error? I'm not able to reproduce it.

**Comment by ADmad** [comment]
Seems this has been resolved in v6.
