### ISSUE TITLE
SlevomatCodingStandard.Functions.RequireArrowFunction.RequiredArrowFunction should not act on PHP < 7.4

### ISSUE THREAD

**Issue by lucasvanlierop** [slevomat/coding-standard#788]
While this rule is a great addition when combined with the fixer tool I think it should not be act on PHP versions lower than 7.4?

What current happens is that:

```php
static function ($value) {
    return $value !== '';
}
```
Is being converted to:

```php
static fn ($value) => $value !== ''
```
Which results in:
`ParseError: syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM)`

Edit:
This is on version `6.0.0`

**Comment by kukulich** [comment]
Just don't use this sniff if you need your code to run on lower PHP versions :)
