### ISSUE TITLE
Suggestion : add possibility to disable useless annotation checks on type hint sniffs

### ISSUE THREAD

**Issue by julien-maurel** [slevomat/coding-standard#794]
Hi,
By default, ParameterTypeHint, PropertyTypeHint, ReturnTypeHint (and perhaps more) sniffs controll useless annotations.
Do you think is it possible to add on option on these sniffs to disable this part only?
Doc is often generated by IDE and I prefer to keep it always instead sometime keep it because really useful, sometime remove it because useless.
If you are agree with this idea and you not have time to do it, I can try to do it for you.
Thanks.

**Comment by kukulich** [comment]
You can exclude specific error code, see https://github.com/slevomat/coding-standard/blob/master/build/phpcs.xml

**Comment by julien-maurel** [comment]
Oh yes, you're rigth!
Sorry for my stupid request, I read report too fast and didn't see specific name.
Thanks for your very fast answer and for your work!
