### ISSUE TITLE
UselessParenthesesSniff Removes Parentheses around Require of Callable

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#798]
We have in our code something like:

```php
(require 'init.php')($di);
```

Where init.php returns a callable expecting an instance of Di, and we call that callable, all inline. e.g. it could be ~more~ less teresely written as:

```php
$callable = require 'init.php';
$callable($di);
```

However, the UselessParenthesesSniff removes the parenthesis around this on both sides and leaves me with the syntax error:

```php
require 'init.php'$di;
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/beea16e33a97884ddfcc5d310b78e0a394538505
