### ISSUE TITLE
The error message was: Undefined index: scope_closer in /var/www/jianghu_entertain/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php

### ISSUE THREAD

**Issue by harrisdt15f** [slevomat/coding-standard#802]
slevomat/coding-standard 6.0.2
squizlabs/php_codesniffer 3.5.3
laravel 6.7.0
php 
PHP 7.3.12-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:36:56) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

```
FILE: ...n/app/Http/Controllers/FrontendApi/FrontendApiMainController.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Undefined index:
   |       | scope_closer in
   |       | /var/www/jianghu_entertain/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php
   |       | on line 385 (Internal.Exception)
----------------------------------------------------------------------
```
php file 

[FrontendApiMainController.php.txt](https://github.com/slevomat/coding-standard/files/3959331/FrontendApiMainController.php.txt)

**Comment by kukulich** [comment]
@harrisdt15f Fix `else if` to `elseif` on line 101. You can use `PSR2.ControlStructures.ElseIfDeclaration` to fix all of you `else if`

**Comment by harrisdt15f** [comment]
thanks

**Comment by harrisdt15f** [comment]
it has already fixed by the way you guide making else if to elseif manually.
but i have alrealy included the rule  PSR2.ControlStructures.ElseIfDeclaration in the file
I think it shouldn't give internal exception.
