### ISSUE TITLE
Generic getIterator() does not have @return annotation for its traversable return value

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#804]
How do you cope with a CS violation that `Method xxx::getIterator() does not have @return annotation for its traversable return value` on IteratorAggregate implementation while having `@phpstan-implements IteratorAggegate<K, V>`? `public function getIterator() : Traversable` has no `@return` annotation.

PHPStan is fine with it as it knows the type hint but phpcs does not of course. Have you encountered such issue and found a solution? AFAIK I can only ignore it with `@phpcsSuppress` annotation.

**Comment by kukulich** [comment]
We still use `@return` annotations because PHPStorm (and other editors) does not understand genererics.

**Comment by simPod** [comment]
But in case of `IteratorAggregate` the `@return` annotation does not help IDE anyway, so there's no point in adding it for that reason, or am I wrong? AFAIK it helps only for static analysis but today both PHPStan and PSalm can infer those types from generic signatures.

So to me it would make sense not to require the annotation there if the type is implicit, that said can be inferred. But don't know if that's doable via PHPCS 🤔 

![image](https://user-images.githubusercontent.com/327717/72247466-3a530380-35f5-11ea-843b-ce7df54f8839.png)

**Comment by kukulich** [comment]
Should be solved in https://github.com/slevomat/coding-standard/issues/907
