### ISSUE TITLE
Idea: Disallow Negative Operator

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#811]
PHP's negative operator can return `true` for a number of values: https://3v4l.org/OPBti.

The rule itself should be easy to create, but I'd like to discuss it first :)

**Comment by ondrejmirtes** [comment]
PHPCS cannot figure this out. It does not do advanced type inference.

This is already implemented by phpstan-strict-rules. It’s fine to have opinionated rules for PHPStan! (Many of them are easier to implement than in PHPCS).

**Comment by carusogabriel** [comment]
@ondrejmirtes The idea would it be to detect the not operator `!` and just report it, now try to fix. As you said, PHPCS cannot infer the type to do it.

**Comment by ondrejmirtes** [comment]
My opinion is that there’s inherently nothing wrong about the operator itself. It’s not like `empty` 😀
