### ISSUE TITLE
Incompatibility with template annotations

### ISSUE THREAD

**Issue by enumag** [slevomat/coding-standard#815]
Since PHPStan 0.12 is out, I started to improve my data structures using the `@template` annotations. The problem is that this package isn't compatible with that.

Input:

```php
/**
 * @template TValue
 */
final class Foo
{
        /**
         * @return TValue
         */
        public function bar()
        {
                ...
        }
}
```

Expected result: no changes

Current result:

```php
/**
 * @template TValue
 */
final class Foo
{
        public function bar(): TValue
        {
                ...
        }
}
```

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/issues/736#issuecomment-547500490

**Comment by enumag** [comment]
@kukulich That wouldn't help in this case. This isn't about `FullyQualifiedClassNameInAnnotationSniff` but about `ParameterTypeHintSniff`, `ReturnTypeHintSniff` and `PropertyTypeHintSniff`. It's not a duplicate issue.

**Comment by enumag** [comment]
It's simply because the sniffs think that TValue is a class/interface name and therefore can be inlined which is not the case. Using `@phpstan-template` has no effect on that. It needs to be implemented in `\SlevomatCodingStandard\Helpers\AnnotationHelper::isAnnotationUseless()` somehow.

**Comment by kukulich** [comment]
The sniff name does not matter. You have to use prefixed annotations.

**Comment by enumag** [comment]
You don't understand. The bug occurs even when I use the prefixed annotations. It has no effect here.

**Comment by kukulich** [comment]
You have to prefix the @return annotation as well.

**Comment by enumag** [comment]
I see... it's kinda ugly since I have to use it like this but at least it works... Same for `@param` and `@var` annotations of course...

```
	/*
	 * @phpstan-return TValue
	 * @return mixed
	 */
