### ISSUE TITLE
RequireNullCoalesceEqualOperatorSniff

### ISSUE THREAD

**Issue by peldax** [slevomat/coding-standard#822]
Hello,
I would like the RequireCombinedAssignmentOperatorSniff to support null coalesce operator in php 7.4+ projects, where ??= operator was added.

Thanks.

**Comment by kukulich** [comment]
It would be probably better to prepare new sniff.

**Comment by peldax** [comment]
Hello, do you mean to completely split RequireCombinedAssignmentOperatorSniff into separated sniffs for each operator, or to create new sniff just for null coalesce?

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/986e7b1ea72c7a7fbcaf508dc09924fb996fffdc
