### ISSUE TITLE
SlevomatCodingStandard.Commenting.RequireOneLineDocComment can't use

### ISSUE THREAD

**Issue by harrisdt15f** [slevomat/coding-standard#824]
slevomat version 6.07
`<rule ref="SlevomatCodingStandard.Commenting.RequireOneLineDocComment"/>`
I got error below with above rule
ERROR: Referenced sniff "SlevomatCodingStandard.Commenting.RequireOneLineDocComment" does not exist

**Comment by kukulich** [comment]
Use dev-master.
