### ISSUE TITLE
UselessFunctionDocCommentSniff conflicts with template syntax

### ISSUE THREAD

**Issue by MidnightDesign** [slevomat/coding-standard#825]
`UselessFunctionDocCommentSniff` reports this doc block as useless even though it contains useful information (a more specific type).

```php
/**
 * @param Foo<string> $foo
 */
function fn(Foo $foo): void {
    // Do something
}
```

This is a problem since more and more projects use type checkers like PHPStan and Psalm which benefit from this kind of type annotation.

**Comment by kukulich** [comment]
@MidnightDesign What version do you use?

**Comment by MidnightDesign** [comment]
@kukulich Well, that could be it. I'm on `^5.0`. I'll have to check if it works with version 6 tomorrow. (And sorry for not checking my version first.)

**Comment by MidnightDesign** [comment]
That fixed the issue. Thank you very much.
