### ISSUE TITLE
SlevomatCodingStandard.Variables.UselessVariable: bug with combined operators

### ISSUE THREAD

**Issue by jrfnl** [slevomat/coding-standard#847]
```php
function foo( $bar ) {
    $bar .= ' more bar';
    return $bar;
}
```

Reports `Useless variable $bar.`

While this may be true if the assignment operator was a `T_EQUAL`/ `=`, it's not useless when it's a combined assignment operator.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/0de6b290a84e72afbf785fd90738f96be02670b1

**Comment by jrfnl** [comment]
@kukulich Excellent. Thanks for the quick turn-around!
