### ISSUE TITLE
Make DisallowEmptyFunction fixable

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#848]

**Comment by Majkl578** [comment]
I wonder how? By adding some content? :trollface:

**Comment by kukulich** [comment]
I was thinking I can remove the empty function... However it's probably nonsense :)

**Comment by Majkl578** [comment]
I think it won't work properly on CS level, in inheritance there could be valid use cases of empty methods, also you can't check where it is called from. 🤔
