### ISSUE TITLE
Additional setting for TraitUseSpacing

### ISSUE THREAD

**Issue by thled** [slevomat/coding-standard#866]
Sniff: SlevomatCodingStandard.Classes.TraitUseSpacing
Setting: linesCountBeforeFirstUseWhenFirstInClass: allows to configure the number of lines before first use when the use is the first statement in the class.

There is already the similar sniff "linesCountAfterLastUseWhenLastInClass", but for me it is way more common to declare the used traits at the beginning of the class. And I do not want to begin the class with an empty line.

It is also recommended by [PSR12 Rule 4.2](https://www.php-fig.org/psr/psr-12/#42-using-traits).

**Comment by kukulich** [comment]
@thled What is your request? I really don't understand.

**Comment by thled** [comment]
I would like to add a setting to the Sniff "SlevomatCodingStandard.Classes.TraitUseSpacing" which allows me to configure the number of lines before the first "use" when that "use" is the first statement in a class.

Example:

```php
final class foo
{
    // x empty lines
    use BarTrait;
    // y empty lines
}
```

We already can configure the "y" ("linesCountAfterLastUseWhenLastInClass") but not the "x" (I propose "linesCountBeforeFirstUseWhenFirstInClass").

**Comment by kukulich** [comment]
You can set it with `EmptyLinesAroundClassBracesSniff`

**Comment by thled** [comment]
If that would be the solution, than why is the "linesCountAfterLastUseWhenLastInClass" setting there? It is effected the same way by your proposed sniff.

Another reason is I should not rely on that other sniff if I just want "use" for traits to be a set number lines after the opening brace of a class.

It feels consistent to offer my proposed setting, but it is Ok if you do not want to add it. I will find ways to cover my use case.

**Comment by kukulich** [comment]
@thled Will you prepare PR?

**Comment by thled** [comment]
I will try it next week. Thank you for your quick responses.
