### ISSUE TITLE
Inconsistent handling of return and break statements in switch/case blocks

### ISSUE THREAD

**Issue by morozov** [slevomat/coding-standard#867]
First of all, I love the addition of the sniffs that control new lines before and after flow control statements! Now, consider the following code example:
```php
<?php

declare(strict_types=1);

function test() : void
{
    switch (true) {
        case 1:
            throw new Exception();

        case 2:
            return;

        case 3:
            break;

        case 4:
            echo 1;
    }
}
```
All cases look similar and have whitespaces between them which creates a certain visual rhythm. Running `phpcs` using the Doctrine Coding Standard against this file produces the following:
```
$ phpcs test.php

------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------
  9 | ERROR | [x] Expected 0 lines after "throw", found 1.
    |       |     (SlevomatCodingStandard.ControlStructures.JumpStatementsSpacing.IncorrectLinesCountAfterLastControlStructure)
 12 | ERROR | [x] Expected 0 lines after "return", found 1.
    |       |     (SlevomatCodingStandard.ControlStructures.JumpStatementsSpacing.IncorrectLinesCountAfterLastControlStructure)
------------------------------------------------------------------------------------------------
```
Fixing the code using `phpcbf` removes the reported empty lines and makes the formatting inconsistent.

**Comment by morozov** [comment]
As was pointed out in https://github.com/doctrine/dbal/pull/3847#discussion_r370971682, there may be something wrong with the sniff configuration in the Doctrine Coding Standard rather than with the standard itself. Please let me know if there's a better way to isolate the issue before reporting it here. I’ll consider it next time.

**Comment by kukulich** [comment]
@morozov It’s difficult to configure it for “case”. I’m trying to find some solution but I’m on vacation this week.

**Comment by morozov** [comment]
Thanks for the heads up, @kukulich.

**Comment by kukulich** [comment]
I think I will add new option `ignoreCaseBlocks` to `JumpStatementsSpacingSniff` and prepare `SwitchSpacingSniff`.

**Comment by morozov** [comment]
Based on this test,

https://github.com/slevomat/coding-standard/blob/34db1f15d973b33a58d559b22165ec2aa653e73a/tests/Sniffs/ControlStructures/JumpStatementsSpacingSniffTest.php#L110-L118

The following configuration applied to [doctrine/dbal](https://github.com/doctrine/dbal) works perfectly and doesn't require the [workaround](https://github.com/doctrine/dbal/pull/3847/files#diff-6758ef1f416bd888bd1a5cad8f97cc2bR25-R26):
```xml
<rule ref="SlevomatCodingStandard.ControlStructures.JumpStatementsSpacing">
    <properties>
        <property name="linesCountBeforeWhenFirstInCaseOrDefault" value="0"/>
        <property name="linesCountAfterWhenLastInCaseOrDefault" value="1"/>
        <property name="linesCountAfterWhenLastInLastCaseOrDefault" value="0"/>
    </properties>
</rule>
```

Thanks you @kukulich!
