### ISSUE TITLE
PHP 7.4 & RequireOneLinePropertyDocCommentSniff processes parent sniffer

### ISSUE THREAD

**Issue by bmoex** [slevomat/coding-standard#877]
Hi, 

As i'm the only one having this in PHP 7.4 I don't know if this is really an issue. However I wanted to mention it here.

I cannot find the explicit reason but since the `RequireOneLineDocCommentSniff` my instance running on PHP 7.4 now parses this sniff without having it enabled. 

If I locally change the `class RequireOneLinePropertyDocCommentSniff extends RequireOneLineDocCommentSniff` to `class RequireOneLinePropertyDocCommentSniff implements Sniff` with the same functions, it works in PHP 7.4 as intended.

You can close this issue if you find this not worth your time! :-)

Example:
Enabled in phpcs;
```xml
<rule ref="SlevomatCodingStandard.Commenting.RequireOneLinePropertyDocComment"/>
```

PHP file:
```php
<?php

namespace Example;

class Example
{
    /** @var string */
    protected $example = '';

    /**
     * @return string
     */
    public function example(): string
    {
        return '';
    }
}

```

Error (ONLY) in PHP7.4
```shell
➜  vendor/bin/phpcs Example.php 

FILE: ./Example.php
------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------
 10 | ERROR | [x] Found multi-line doc comment with single line content, use one-line doc comment
    |       |     instead.
------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------------

Time: 56ms; Memory: 8MB
```

**Comment by kukulich** [comment]
@bmoex Please post your configuration.

**Comment by bmoex** [comment]
I tried it in an empty project, and this problem does not occur. There must be a package in my project that  makes this annoying. 

Deducted to `typo3/testing-framework`. However, need to debug deeper to see which package exactly. Hope to have the answer for you tomorrow

**Comment by bmoex** [comment]
[simple-example.zip](https://github.com/slevomat/coding-standard/files/4129213/simple-example.zip)

**Comment by kukulich** [comment]
It's probably something strange in PHPCS itself but it should be solved with https://github.com/slevomat/coding-standard/commit/247d1a5a4fef15486267ab590d0a43a529d3f728

**Comment by bmoex** [comment]
Thanks @kukulich! Can you tag a new bugfix release version? :-)
