### ISSUE TITLE
Files.TypeNameMatchesFileName  classmap option??

### ISSUE THREAD

**Issue by bkdotcom** [slevomat/coding-standard#882]
Is it possible to specify a non-PSR-4 compliant class / filepath??

I have  
`<element key="src" value="VendorName\LibraryName"/>`

I also have a class  VendorName\LibraryName`   => src/LibraryName.php
how can I specify this class/filename mapping ?

**Comment by kukulich** [comment]
I really don't understand your problem.

**Comment by bkdotcom** [comment]
@kukulich 

My composer.json defines autoload as such:

```
	"autoload": {
		"classmap": [
			"src/Widget.php"
		],
		"psr-4": {
			"vendor\\Widget\\": "src/"
		}
	},
```

how do I handle src/Widget.php ?

TypeNameMatchesFileNameSniff allows me to define the psr-4 mappings, but not "classmap"

I suppose I could exclude the file from the rule??

<rule ref="SlevomatCodingStandard.Files.TypeNameMatchesFileName">
    <exclude-pattern>src/Widget\.php</exclude-pattern>
</rule>

**Comment by kukulich** [comment]
Yes, you can exclude it.
