### ISSUE TITLE
SlevomatCodingStandard.Classes.ClassStructure

### ISSUE THREAD

**Issue by bkdotcom** [slevomat/coding-standard#884]
I'm very confused with SlevomatCodingStandard.Classes.ClassStructure

**My config**
```
<rule ref="SlevomatCodingStandard.Classes.ClassStructure">
        <properties>
            <property name="groups" type="array">
                <element value="uses" />
                <element value="public constants" />
                <element value="protected constants" />
                <element value="private constants" />
                <element value="public static properties, public properties" />
                <element value="protected properties, protected static properties, private properties, private static properties" />
                <element value="constructor " />
                <element value="magic methods" />
                <element value="public methods, public static methods" />
                <element value="protected methods, protected static methods, private methods, private static methods" />
            </property>
        </properties>
</rule>
```
**File I'm sniffin'**
Note the 4 errors in the comments

```php
<?php

namespace vendor\Library;

class Widget
{

    private $options = array();

    public function __construct($options = array())
    {
        $this->options = $options;
    }

    /**
     * Changing (adding lines) / removing this comment seems to affect whether SlevomatCodingStandard.Classes.ClassStructure reports any erros
     *
     * @return static
     */
    public static function factory()
    {
        return new static();
    }

    /**
     * The placement of "public methods" group is invalid.
     */
    public function foo()
    {
    }

    /**
     * The placement of "private static methods" group is invalid
     */
    private static function baz()
    {
    }

    private static function dang()
    {
    }

    /**
     *  The placement of "private methods" group is invalid
     */
    private function dong()
    {
    }

    /**
     * The placement of "private static methods" group is invalid.
     */
    private static function doh()
    {
    }
}
```

I had trouble even creating a reduced test case as simply adding/removing comments seems to affect whether or not issues are reported

**Comment by kukulich** [comment]
@bkdotcom 

I'm not able to reproduce any error. Please try to prepare PR with failing test.

**Comment by bkdotcom** [comment]
this may be user error. :(
I think it would be helpful if the error also includes the group it was expecting (or the last group it found) in addition to the unexpected group

however, [I did find a **BUG**](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php#L235-L238)

```php
$name = strtolower(FunctionHelper::getName($phpcsFile, $pointer));
if (array_key_exists($name, self::SPECIAL_METHODS)) {
    return self::SPECIAL_METHODS[$name];
}
```

not sure if the `strtolower` should be there, but if it remains, "__callStatic", "__debugInfo", & "__toString" need to be lowercased in SPECIAL_METHODS

**Comment by grongor** [comment]
@bkdotcom Imo the issue is that it sometimes considers the method to be a group `public static methods` and sometimes `static constructors`. Method is considered a static constructor if it's public, static and returns an instance of itself.

As you are missing the `static constructors` group entirely in your config, the group is expected to be at the end of the class.

**Comment by bkdotcom** [comment]
@grongor  yes... I made that mistake when creating the reduced test case.  I didn't realize "static constructor" was a thing (and/or didn't know what "static constructor" meant)

I think the documentation could use a bit of help listing all the available groups.   perhaps use a unsorted list or nested list..  and

* "static constructor"  (aka factory method that returns self/static)

I think the underlying problem was the issue with __callStatic, __debugInfo, and __toString (I just didn't realize it / and borked my example above)

**Comment by grongor** [comment]
@kukulich just an idea, but what about requiring user to set all the groups? I think that nobody wants to leave the unconfigured groups at the end of the class, it's either a mistake (as in this case) or they assume that those groups will be ignored (I guess, that's what I feel makes sense). By requiring user to set all the groups when using custom setttings, we could prevent such situations. And I also agree with @bkdotcom that the error message could specify which group was expected in case of a sniff violation. What do you think? I can send PR if it makes sense to you...

**Comment by kukulich** [comment]
@grongor I had the same idea yesterday. I just don't know if we can change it because it's BC break :(

**Comment by grongor** [comment]
Yeah ... your call :)

**Comment by kukulich** [comment]
@grongor If you prepare PR, I will merge it :) Noone probably uses the default settings.

**Comment by grongor** [comment]
https://github.com/slevomat/coding-standard/pull/895
