### ISSUE TITLE
Runtime Error in SlevomatCodingStandard.ControlStructures.EarlyExit

### ISSUE THREAD

**Issue by donatj** [slevomat/coding-standard#889]
When I turn on `SlevomatCodingStandard.ControlStructures.EarlyExit` I am receiving the following error:

> Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_closer in /Users/jdonat/Sites/myon/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 198 in /Users/jdonat/Sites/myon/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

I managed to boil the code triggering it down to this:

```php
<?php

namespace Controller\cli\dev;

class ddl2dbo {

	public function bar($constants) {
		if( $constants ) {
			echo <<<EOT
EOT;
		}
	}

}
```

$token in UseStatmentHelper is 

```
Array
(
    [code] => 361
    [type] => T_CLASS
    [content] => class
    [line] => 5
    [column] => 1
    [length] => 5
    [level] => 0
    [conditions] => Array
        (
        )

)
```

**Comment by kukulich** [comment]
What PHP version do you use?

**Comment by donatj** [comment]
I am on 7.1.32

**Comment by donatj** [comment]
Testing in Docker, it does appear to not occur in 7.3 for me.

**Comment by donatj** [comment]
Actually I take that back. It *does* happen for me in 7.3, but I had broken UseStatementHelper

**Comment by donatj** [comment]
Ok, interesting. I had not upgraded to 6.1.4 - I started the upgrade to 6.1.3 this morning. It does not appear to crop up in  6.1.4

**Comment by donatj** [comment]
I am perfectly happy to close this if you are.
