### ISSUE TITLE
[2.0-dev] Unused use when used only as nullable return type

### ISSUE THREAD

**Issue by mhujer** [slevomat/coding-standard#89]
When use is used only as nullable return type hint, CS thinks that it is unused (2.0-dev - latest):

```php
<?php

declare(strict_types = 1);

namespace Driveto\AppBundle\Catalog;

use DateTimeImmutable;

class Foo
{

	public function getDeleted($entity): ?DateTimeImmutable
	{
		return $entity->getDeleted();
	}

}
```

**Comment by kukulich** [comment]
@mhujer 

Do you really use latest 2.0-dev? I think it should be fixed with this commit: https://github.com/slevomat/coding-standard/commit/56dbb03aad150e4f8ad648a120bdf8f523c9a4a1

I tried to add test with your code now and it works: https://github.com/slevomat/coding-standard/pull/90

**Comment by mhujer** [comment]
Sorry, my bad. I had a constraint for older version of consistence/coding-standard, which had a constraint for codesniffer 2.7, therefore Composer resolved to older slevomat/coding-standard version. It works after proper update.
