### ISSUE TITLE
Add support for final methods in `ClassStructureSniff`

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#894]
It would be nice to have the following additions for the [`ClassStructureSniff`](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php):

- `public final methods`
- `public final static methods`
- `protected final methods`
- `protected final static methods`
- `private final methods`
- `private final static methods`

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/4774eea396d69e90ae4500db9a55ce2383938780

I've not implemented `private final` methods because it does not make sense to me.
