### ISSUE TITLE
SlevomatCodingStandard.Classes.ClassStructure got errors need help

### ISSUE THREAD

**Issue by harrisdt15f** [slevomat/coding-standard#898]
After Updated to slevomat coding Standard v **6.1.5** then I got the below error
php version 7.3.13
os ubuntu

[1mFILE: ...rs/BackendApi/Headquarters/Admin/BackendAdminGroupController.php[0m        
remote: ----------------------------------------------------------------------        
remote: [1mFOUND 1 ERROR AFFECTING 1 LINE[0m        
remote: ----------------------------------------------------------------------        
remote:  1 | [31mERROR[0m | An error occurred during processing; checking has been        
remote:    |       | aborted. The error message was: You need configure all        
remote:    |       | class groups. These groups are missing from your        
remote:    |       | configuration: static constructors, destructor.        
remote: ----------------------------------------------------------------------       

My Rule Configuration

```
<rule ref="SlevomatCodingStandard.Classes.ClassStructure">
        <properties>
            <property name="groups" type="array">
                <element value="uses"/>
                <element value="public constants"/>
                <element value="protected constants"/>
                <element value="private constants"/>
                <element value="public properties, protected properties, private properties"/>
                <element value="public static properties, protected static properties, private static properties"/>
                <element value="constructor"/>
                <element value="public abstract methods, protected abstract methods"/>
                <element value="public static abstract methods, protected static abstract methods"/>
                <element value="public methods, protected methods, private methods"/>
                <element value="public static methods, protected static methods, private static methods"/>
                <element value="magic methods"/>
            </property>
        </properties>
    </rule>
```

Error Reported file
[BackendAdminGroupController.php.txt](https://github.com/slevomat/coding-standard/files/4169192/BackendAdminGroupController.php.txt)

**Comment by kukulich** [comment]
It’s written in the error message what you should do :)

**Comment by harrisdt15f** [comment]
how should i repair my file please guide me.

**Comment by kukulich** [comment]
You should repair your configuration.

**Comment by harrisdt15f** [comment]
thanks
