### ISSUE TITLE
Disallow __invoke call sniff

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#899]

**Comment by asgrim** [comment]
What's the status of editors and static analysis tools understanding "native" invokation of `__invoke`? I believe that's the biggest road blocker here for me, last time I checked (a while ago), PhpStorm didn't understand the types properly. That may have changed since...

**Comment by kukulich** [comment]
@asgrim https://github.com/Roave/BackwardCompatibilityCheck/pull/59#issuecomment-583767492

**Comment by asgrim** [comment]
Very nice! 👍

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/c4779864ba180833f4d8dce5b31df951c5dee7b5
