### ISSUE TITLE
Don't auto enable on system php

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#900]
> enableNativeTypeHint: enforces to transform @var int into native int typehint. It's on by default if you're on PHP 7.4+

    PHP_VERSION_ID >= 70400;

I find this a bit dangerous.
If one person runs already 7.4+ on their system, then they compromise the code by accidently commiting php74+ only code.
It would be better if those would be disabled by default or respect the composer min settings of php if found (reading composer.json require php).

**Comment by kukulich** [comment]
You can disable it in your configuration.

**Comment by dereuromark** [comment]
But thats not a sane/good default. Thats what I am saying.
If you dont know it happens by default.
