### ISSUE TITLE
UselessParenthesesSniff bug

### ISSUE THREAD

**Issue by liepumartins** [slevomat/coding-standard#908]
Another bug I stumbled across

Working code
```php
$output = ($this->someCondition and $this->otherCondition) ? 'yes' : 'nope';
// $output is 'yes' or 'nope'

$output = (($this->someCondition and $this->otherCondition) ? 'yes' : 'nope');
// $output is 'yes' or 'nope'
```
These parentheses around both conditions are considered useless by the sniff.
Sniff suggests removing those and bug happens:
```php
$output = $this->someCondition and $this->otherCondition ? 'yes' : 'nope';
// $output is value of $this->someCondition
$output = ($this->someCondition and $this->otherCondition ? 'yes' : 'nope');
// $output is true or false, depending on conditions
```

**Comment by kukulich** [comment]
@liepumartins We don't support `and` and `or` operators and I'm not sure if it's worth to invest time to the support.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/217215a7932d3e57db15cf5ed1dee078ac66121b
