### ISSUE TITLE
Disallow superglobals

### ISSUE THREAD

**Issue by danepowell** [slevomat/coding-standard#911]
As a wise man once said, "global variables are bad. superglobals are super bad." :smile: 

I'd like a sniff that would catch usage of [superglobal variables](https://www.php.net/manual/en/language.variables.superglobals.php) such as `$_ENV` and `$_SERVER`. 

The motivating factor for us is the painful discovery that many of these superglobals are not portable between environments, depending on the use of [variables_order](https://www.php.net/manual/en/ini.core.php#ini.variables-order). This may not be an issue for projects that have full-stack control of their operating environment, but projects that are distributed as libraries absolutely should not be using superglobals.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/f96c22dd228edb6ff1856cc993b168859357bc2d

P.S. You can now sponsor Slevomat Coding Standard development via [GitHub sponsors](https://github.com/sponsors/kukulich/)

**Comment by danepowell** [comment]
Wow, thanks for such an enthusiastic and immediate response! Duly noted re: sponsorship, I'll see what's possible 😄
