### ISSUE TITLE
Allow Exceptions.ReferenceThrowableOnly to be suppressed locally

### ISSUE THREAD

**Issue by mathieu-bour** [slevomat/coding-standard#915]
In some frameworks, like Laravel or Lumen, we can write a custom error handler which has to implement an interface like in the issue #580.

If I totally agree that the sniff SHOULD change \Exceptions to \Throwable, it might be useful to be allowed to do something like:

```php
interface HandlerContract
{
    public function report(Exception $exception): void;
}

class Handler implements HandlerContract
{
    /**
     * @phpcsSuppress SlevomatCodingStandard.Exceptions.ReferenceThrowableOnly.ReferencedGeneralException
     */
    public function report(Exception $exception): void
    {
    }
}
```

### Current workaround

For now, I'm using the `phpcs:enable` and `phpcs:disable` comments like so:

```php
class Handler implements HandlerContract
{
    /**
     * phpcs:disable SlevomatCodingStandard.Exceptions.ReferenceThrowableOnly
     */
    public function report(Exception $exception): void
    {
        // phpcs:enable SlevomatCodingStandard.Exceptions.ReferenceThrowableOnly
    }
}
```

but I feel that this solution is quite verbose and hard to read and understand.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/7e41c42baf4628edc9ef27b21a1b57e0c7f00be6

P.S: You can now sponsor [Slevomat Coding Standard development](https://github.com/sponsors/kukulich/) via GitHub sponsors.
