### ISSUE TITLE
SlevomatCodingStandard.Variables.UnusedVariable doesn't handle variables in strings with curly brackets

### ISSUE THREAD

**Issue by jacks0n** [slevomat/coding-standard#919]
Example:
```
$foo = ['hello', 2, 3];
echo "${foo[0]} there";
```

The issue appears when curly brackets are used within a string (e.g. `echo "$foo"` works fine).

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/3c5fc9b7e6e2a9818074c3368e13113622a13ef1
