### ISSUE TITLE
Respect PHP_CodeSniffer php_version configuration

### ISSUE THREAD

**Issue by stlrnz** [slevomat/coding-standard#921]
Some Sniffs like `SlevomatCodingStandard.TypeHints.PropertyTypeHint` are PHP version aware (and setting some default configurations depending on the version).

Example:
https://github.com/slevomat/coding-standard/blob/21719768332fd764ae05c13fc15fbcef836fd775/SlevomatCodingStandard/Sniffs/TypeHints/PropertyTypeHintSniff.php#L62

PHP_CodeSniffer supports an option to override the current PHP version ([Documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-php-version)).

Some Sniffs delivered by PHP_CodeSniffer are also version aware respecting the `php_version` configuration. Example: [FunctionCommentSniff ](https://github.com/squizlabs/PHP_CodeSniffer/blob/caddfdea6fc48f30f6a1b0ffe3b91e761bbefabf/src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php#L258-L263)

I think it would be nice (and helpful for me) if the Slevomat Coding Standard would also respect this configuration. Is there any reason not to do this?

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/f54967777673c84706370e1ef0c9819aa1eb5982

**Comment by stlrnz** [comment]
Thank you!
