### ISSUE TITLE
Namespaces.FullyQualifiedExceptions and Namespaces.UnusedUses causing slow checks

### ISSUE THREAD

**Issue by ocean90** [slevomat/coding-standard#929]
For some yet unknown reasons I noticed that the rules `SlevomatCodingStandard.Namespaces.FullyQualifiedExceptions` and `SlevomatCodingStandard.Namespaces.UnusedUses` are causing a much slower check.

In numbers, for the same file (~900 lines): 
* 94ms without any rules
* ~1.3 secs with only `SlevomatCodingStandard.Namespaces.FullyQualifiedExceptions`
* ~4 secs with only `SlevomatCodingStandard.Namespaces.UnusedUses`
* ~5.3 secs with `SlevomatCodingStandard.Namespaces.UnusedUses` and `SlevomatCodingStandard.Namespaces.FullyQualifiedExceptions`

I can't tell if there is a bug in the sniff or if it's just caused by the design of the sniff to detect the errors and the amount of code in a file. For this specific file [`$referencedNames`](https://github.com/slevomat/coding-standard/blob/e27ab09cb23be30388b7c734353f6218a197e49b/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php#L87) has 211 elements.

I'm happy to share the example file by email since it's private code.

PHP_CodeSniffer version: 3.5.4
PHP version: 7.3.16
Slevomat Coding Standard version: 6.1.5

**Comment by kukulich** [comment]
I dont see anything wrong. Some sniffs are slower than others.

**Comment by nightlinus** [comment]
@ocean90 can u check against master?

**Comment by ocean90** [comment]
@nightlinus Thanks, speed is perfect now! I only noticed that the same error is now printed multiple times, to be exact: 60x. Looks like this:

```
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
8 | ERROR | [x] Type Something\FOO is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
```


Do you think the same improvements can be applied to `FullyQualifiedExceptions`?

**Comment by kukulich** [comment]
@ocean90 What commit in master did you test?

**Comment by ocean90** [comment]
@kukulich With 9dac2807b68b7ff3345c0ce81d1c9bca3df17a5c. But I just tested with e2a057b1b639fc803c1e8eb24601073fb7e4c274 and 38f300908a56844d3a318f6bc3451390766dc626 and seeing the same error. I going to continue testing with other commits now.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/commit/38f300908a56844d3a318f6bc3451390766dc626 is before the optimization so it looks it's unrelated to the optimization.

**Comment by kukulich** [comment]
@ocean90 I've just tried to make the same optimization in `FullyQualifiedExceptionsSniff`: https://github.com/slevomat/coding-standard/commit/3c557d5ae0b1ee13824df304fb3dd2165e182654

**Comment by ocean90** [comment]
Thanks, any chance you could merge #934? Makes testing/debugging a bit easier.

**Comment by kukulich** [comment]
I have to check if #934 is useful for me as developer.

**Comment by ocean90** [comment]
@kukulich @kukulich Thanks for your work on this! Running the check with both rules on the same file mentioned in my initial comment takes now only 334ms. Using it together with our other rules, it's now down to 660ms from 8.75 secs. ✨ 

I created #937 for the duplicated error messages which are unrelated to the changes here.
