### ISSUE TITLE
[`UselessParentheses`]: not reporting `instanceof`

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#933]
Looks like the parentheses here aren't really necessary: https://3v4l.org/AvuVp vs. https://3v4l.org/6M8sn.

**Comment by kukulich** [comment]
I'm not sure if it is good to implement it. I'm trying to report parentheses that are useless and the readability will not be worse without them. The second example looks worse to me...

**Comment by carusogabriel** [comment]
> I'm trying to report parentheses that are useless and the readability will not be worse without them

Perfect, thanks for the feedback 👍
