### ISSUE TITLE
[Feature request] Add minimum required for allowing numerical literal separator

### ISSUE THREAD

**Issue by marcospassos** [slevomat/coding-standard#942]
It would be very useful to be able to specify the minimum scale to allow the separator number of literals. For example, if the scale is 6, then the literal separator is mandatory only for numbers equal to or greater than 1,000,000.

**Comment by kukulich** [comment]
@marcospassos number 1,000.123 should be reported or not?

**Comment by marcospassos** [comment]
I would only validate the whole part for now.

**Comment by kukulich** [comment]
Two new options implemented in https://github.com/slevomat/coding-standard/commit/7323c484207b5342bcc00452c8d1157f0794347f

**Comment by marcospassos** [comment]
Thank you!
