### ISSUE TITLE
Sniff to check that special PHP functions are using the root namespace

### ISSUE THREAD

**Issue by ocean90** [slevomat/coding-standard#949]
There's already `SlevomatCodingStandard.PHP.OptimizedFunctionsWithoutUnpacking` to check that the optimized functions don't use unpacking. I'm wondering if a `SlevomatCodingStandard.PHP.OptimizedFunctions` sniff would be a good addition for this. The sniff should check that all the optimized functions are prefixed with the root namespace `\`. I guess it will be possible to provide an auto-fixer for this as well.

I haven't written a sniff before but I'd volunteer to write one for this if it gets accepted. 

I found something similar in [PHP-CS-Fixer]( https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.1/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php).

**Comment by kukulich** [comment]
You can use new option `include` in `FullyQualifiedGlobalFunctionsSniff`, see https://github.com/slevomat/coding-standard/pull/948

It will be part of next release 6.2.0.

**Comment by ocean90** [comment]
What a coincidence! PHP-CS-Fixer also uses the `include` approach but also provides a `@compiler_optimized` placeholder which [gets replaced with the list of the functions](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/c8afb599858876e95e8ebfcd97812d383fa23f02/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L329-L331). Or maybe an `includeSpecialFunctions` setting might be easier to implement. Any thoughts on this? 

Looking at #948, the same would make sense for built-in constants. In PHP-CS-Fixer this is [`native_constant_invocation` with  the`fix_built_in` setting](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.1/src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php#L131-L137).

**Comment by kukulich** [comment]
`FullyQualifiedGlobalConstantsSniff` works for all global constants.

**Comment by ocean90** [comment]
Correct, the idea is to dynamically limit it only to the result of `get_defined_constants()` (without user defined constants).

**Comment by kukulich** [comment]
New option for `FullyQualifiedGlobalFunctions` implemented https://github.com/slevomat/coding-standard/commit/b80a33e8362ef1f4fe022c48e0e40c5c80e4d5e1
