### ISSUE TITLE
Changing trait visibility makes it a property

### ISSUE THREAD

**Issue by mkroeders** [slevomat/coding-standard#950]
The issues fixed with b80a33e also exists in PropertyTypeHintSpacingSniff

Adding the following code seems to fix it:

```php
$asPointer = TokenHelper::findPreviousEffective($phpcsFile, $visibilityPointer - 1);
if ($tokens[$asPointer]['code'] === T_AS) {
   return;
}
```

Seems this issue appeared in 6.1.4, for now running 6.1.3 to solve this

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/d2c9d872940225f9f8e47959f518f8393237f0a7
