### ISSUE TITLE
Errors thrown for generics/templates

### ISSUE THREAD

**Issue by ADmad** [slevomat/coding-standard#954]
As of v6.2.0 it seems `@pslam-*` tags too are being parsed. But the template annotation `@template` is not supported yet.

So for annotations like `@psalm-var array<string, TObject>` where `TObject` is declared using `@template TObject` the `FullyQualifiedClassNameInAnnotation` sniff throws errors like `Class name \Foo\Bar\TObject in @psalm-var should be referenced via a fully qualified name.`

So is there a switch to prevent `@psalm-*` tags from being parsed?

**Comment by kukulich** [comment]
@ADmad Try `dev-master` please.

**Comment by ADmad** [comment]
@kukulich Issue seems to be resolved, thanks.

**Comment by ADmad** [comment]
Sorry to revisit this but while your fix done earlier prevents errors for annotations in docblocks for properties and methods, it still generate errors for inline annotations.

For e.g. code like below within a method

```php
        /** @psalm-var TObject $instance */
        $instance = $this->_create($className, $name, $config);
```
generates error like
```
 Class name \Foo\Bar\TObject in @psalm-var should be referenced via a fully qualified name.
(SlevomatCodingStandard.Namespaces.FullyQualifiedClassNameInAnnotation.NonFullyQualifiedClassName)

**Comment by kukulich** [comment]
@ADmad Please open new issue
