### ISSUE TITLE
Whitespaces.DuplicateSpaces feature request

### ISSUE THREAD

**Issue by paranoiq** [slevomat/coding-standard#965]
pls add `ignoreSpacesInComments` flag.

i really need to draw some tables in doc comments : ]

and also things like this:
```
    /**
     * create_definition:
     *     [CONSTRAINT [symbol]] FOREIGN KEY
     *         [index_name] (index_col_name,...) reference_definition
     */
    private function parseForeignKey(TokenList $tokenList): ForeignKeyDefinition
```

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/c1babae3ef512c03c11384c5bd6e251f49e925c8
