### ISSUE TITLE
Force strict comparisons with in_array(), etc...

### ISSUE THREAD

**Issue by ghnp5** [slevomat/coding-standard#972]
Hello,

This has been requested before: https://github.com/slevomat/coding-standard/issues/270

However, the reason not to implement in this coding standard was because it's existing in phpstan already.

For those who don't use phpstan, including me, this is a check I really miss in PHPCS.
Would you consider adding it to this Standard?

It's a bit overkill to use phpstan just for this purpose, when PHPCS already does pretty much all the validation necessary. This strict check is pretty much the only thing I've been missing since always.

Thank you very much.

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/829e5ca9b8fffda3e702242bd7ba154cd9e122a6
