### ISSUE TITLE
Defining number of newlines between methods and properties

### ISSUE THREAD

**Issue by Ilyes512** [slevomat/coding-standard#973]
Is there a way to define the min/max new lines between methods and class properties? I am already using `SlevomatCodingStandard.Classes.***Spacing`-sniffs and they work! The problem I am trying to solve is between the types of "things" in a class, for example this is currently allowed:

```php
<?php

class Foobar
{
    public string $foobar = 'hello';




    public function hello(): string
    {
        echo 'Hello';
    }
}

```

Is there a way to prevent to number of new lines between the property (or const) and the method (in my case I want exactly 1 empty line between them).

Thanks in advance (awesome sniffs!!)

**Comment by kukulich** [comment]
Implemented in https://github.com/slevomat/coding-standard/commit/a970afd4d180f58474025dcfb74ac307e24433e6

**Comment by Ilyes512** [comment]
Oh damm that was fast :)! Thanks! Looking forward to the next release :D
