### ISSUE TITLE
Don't treat line with comment as an empty line after function

### ISSUE THREAD

**Issue by trboltom** [slevomat/coding-standard#974]
I am using version `6.2.0` and I believe this is a bug, but please correct me if I am wrong and this is intentional feature. On following screenshot I am getting error 
 `Expected 1 blank line after method, found 2. (SlevomatCodingStandard.Classes.MethodSpacing.IncorrectLinesCountBetweenMethods)`

![image](https://user-images.githubusercontent.com/7612146/79114888-bd1a6480-7d84-11ea-9d7e-7825dc8caf55.png)

**Comment by kukulich** [comment]
@trboltom Can you try `dev-master` please?

**Comment by trboltom** [comment]
@kukulich I have bumped it to `dev-master`, but now I am getting this error when I try to run `vendor/bin/phpcs --standard=.coding-standards/ruleset.xml` and wasn't able to resolve it yet, I will get to it later today when I have more free time 

![image](https://user-images.githubusercontent.com/7612146/79120223-b4308f80-7d92-11ea-86bf-6aaab8d865a0.png)

**Comment by trboltom** [comment]
@kukulich To solve my situation i had to run `composer dump-autoload` within coding-standard directory in vendor, that fixed my issue.
 
With `dev-master` it is working as expected and no error is shown, I guess I can close this issue and it will be fixed with next release?
