### ISSUE TITLE
ClassStructureSniff: Undefined index: public final methods

### ISSUE THREAD

**Issue by VasekPurchart** [slevomat/coding-standard#980]
I have been trying to use the new-ish `ClassStructureSniff` but with no luck yet, almost all my attempts to configure this to what I need end in:

```
An error occurred during processing; checking has been aborted. The error message was: Undefined index: public final methods in /workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php on line 655
   |       | (Internal.Exception)
```

My desired configuration:

```xml
	<rule ref="SlevomatCodingStandard.Classes.ClassStructure">
		<properties>
			<property name="groups" type="array">
				<element value="constants"/>
				<element value="properties"/>
				<element value="constructor"/>
				<element value="methods"/>
			</property>
		</properties>
	</rule>
```

I have tested this on `6.2` and also latest master: `dev-master d7a4988`.

Or am I missing something and configuring it improperly?

**Comment by kukulich** [comment]
See options: https://github.com/slevomat/coding-standard#slevomatcodingstandardclassesclassstructure- :)

**Comment by kukulich** [comment]
I know about the notice but was too lazy to fix it. It occurs only in one special situation.

**Comment by VasekPurchart** [comment]
Yea, of course I read the documentation first, but I still do not get it. All the elements are either in the supported shortcuts (constants, properties, methods) or constructor.

I also checked that `enableFinalMethods` is false by default, so that should not make any difference?

So what am I missing? :D

**Comment by kukulich** [comment]
@VasekPurchart Oh, sorry I was confused by the error message.

Just enable `enableFinalMethods` and you would be fine. `methods` shortcut does not work without it. That's the one special situation :D

**Comment by VasekPurchart** [comment]
Oh, ok, thanks, now I semi-get it, the shortcut will probably mention final methods :)

**Comment by kukulich** [comment]
@VasekPurchart Yes :)

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/e4f74a9e502c39ba896e693dcedc2ca4a6fecb04
