### ISSUE TITLE
Broken autoloading with v6.3

### ISSUE THREAD

**Issue by enumag** [slevomat/coding-standard#983]
`symplify/easy-coding-standard` doesn't work at all with the new version, fails to autoload sniffs from this package. After some digging I found out that it's caused by https://github.com/slevomat/coding-standard/commit/c21945c3f2753f4de85b678f3cd01c80324bfcb9.

First please add this to 6.3.0 release notes as it is a massive change.

Secondly, how can we fix ECS now?

**Comment by grossmannmartin** [comment]
For end project is possible to autoload necessary classes. But I see it merely as a "hack solution"

```diff
# composer.json
    "autoload-dev": {
        "psr-4": {
+           "SlevomatCodingStandard\\": "vendor/slevomat/coding-standard/SlevomatCodingStandard"
    }
```

**Comment by enumag** [comment]
@grossmannmartin :+1: Good to know about it but it is indeed a hack.

**Comment by oallain** [comment]
Hi,

I have the same problem, I think it is due to the removal of the autoload.
See at https://github.com/slevomat/coding-standard/compare/6.2.0...6.3.0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L27

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/releases/tag/6.3.2

**Comment by jrfnl** [comment]
Please also see my reply to this in the original PR thread: https://github.com/slevomat/coding-standard/pull/969#issuecomment-616847719
