### ISSUE TITLE
cbf cannot solve some of SlevomatCodingStandard.Variables.UselessVariable.UselessVariable problems 

### ISSUE THREAD

**Issue by harrisdt15f** [slevomat/coding-standard#986]
**slevomat/coding-standard v 6.3.2
php v 7.3.16**
**framework laravel v 7.8.1**
### analyzed file
[AppServiceProvider.php.txt](https://github.com/slevomat/coding-standard/files/4537478/AppServiceProvider.php.txt)

### **expected behavior**
to be solve usless variable at line 40 and161

### **actual behavior** 
only solve usless variable at line 40 but not solve 161

### phpcbf processing log
[phpcbf.log](https://github.com/slevomat/coding-standard/files/4537497/phpcbf.log)

### my rule set
[phpcs.xml.txt](https://github.com/slevomat/coding-standard/files/4537500/phpcs.xml.txt)

i don't know if it's bug or  my rule confliction cause problem.

**Comment by kukulich** [comment]
Improved in https://github.com/slevomat/coding-standard/commit/1a6575c072da9848dffbff95f2e547c08677d8da
