### ISSUE TITLE
Sniff to remove obsolete whitespace around short logic checks in if-blocks (Feature Request)

### ISSUE THREAD

**Issue by spaceemotion** [slevomat/coding-standard#997]
I've got the following case in which my If-clause got fixed due to PSR-12:

```php
if (
    empty($foo)) {
  // ...
}
```
became
```php
if (
    empty($foo)
) {
  // ...
}
```

Is there a way to configure the sniffs so it removes the obsolete whitespace like so instead? Preferably by specifying some kind of line-length?

```php
if (empty($foo)) {
  // ...
}
```

Many thanks in advance!

**Comment by kukulich** [comment]
You can try new sniff: https://github.com/slevomat/coding-standard/commit/65fae6efa41af005375ea7020a74569a08cf9e6b
